# Generated by Django 5.2.15 on 2026-07-22 00:33

import curriculum_standards.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_analytics', '0031_alter_groupingpolicyversion_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('document_type', models.CharField(choices=[('curriculum_plan', '课程方案'), ('subject_standard', '学科课程标准')], max_length=32)),
                ('school_stage', models.CharField(choices=[('k1_k9', '义务教育'), ('k10_k12', '普通高中')], max_length=16)),
                ('subject_code', models.CharField(blank=True, max_length=64)),
                ('subject_name', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_curriculum_standards', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_curriculum_standards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school_stage', 'document_type', 'subject_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumStandardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=80)),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('effective_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title_snapshot', models.CharField(max_length=240)),
                ('official_title', models.CharField(max_length=240)),
                ('document_type_snapshot', models.CharField(choices=[('curriculum_plan', '课程方案'), ('subject_standard', '学科课程标准')], max_length=32)),
                ('school_stage_snapshot', models.CharField(choices=[('k1_k9', '义务教育'), ('k10_k12', '普通高中')], max_length=16)),
                ('subject_code_snapshot', models.CharField(blank=True, max_length=64)),
                ('subject_name_snapshot', models.CharField(blank=True, max_length=80)),
                ('issued_by', models.CharField(default='中华人民共和国教育部', max_length=160)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_note', models.TextField(blank=True)),
                ('pdf_file', models.FileField(max_length=500, upload_to=curriculum_standards.models.curriculum_pdf_upload_path)),
                ('pdf_sha256', models.CharField(db_index=True, max_length=64)),
                ('pdf_size_bytes', models.PositiveBigIntegerField()),
                ('pdf_page_count', models.PositiveIntegerField()),
                ('structured_text', models.TextField(blank=True)),
                ('structured_format', models.CharField(default='page_marked_text_v1', max_length=40)),
                ('structured_text_sha256', models.CharField(blank=True, max_length=64)),
                ('extraction_status', models.CharField(choices=[('pending', '待处理'), ('completed', '已生成结构化文本'), ('needs_ocr', '需要文字识别'), ('failed', '处理失败')], default='pending', max_length=24)),
                ('extraction_message', models.CharField(blank=True, max_length=500)),
                ('extraction_engine', models.CharField(blank=True, max_length=120)),
                ('extraction_engine_version', models.CharField(blank=True, max_length=240)),
                ('extraction_config', models.JSONField(blank=True, default=dict)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('review_pending', '待复核'), ('reviewed', '已复核'), ('published', '已发布'), ('archived', '已归档'), ('discarded', '已丢弃')], default='draft', max_length=24)),
                ('review_note', models.TextField(blank=True)),
                ('independent_review', models.BooleanField(default=False)),
                ('independent_publication', models.BooleanField(default=False)),
                ('governance_waiver_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_curriculum_standard_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_curriculum_standard_versions', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_curriculum_standard_versions', to=settings.AUTH_USER_MODEL)),
                ('replaces_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_versions', to='curriculum_standards.curriculumstandardversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_curriculum_standard_versions', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='curriculum_standards.curriculumstandard')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_curriculum_standard_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source_id', '-publication_year', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumStandardPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('extraction_method', models.CharField(choices=[('embedded_text', 'PDF 内嵌文字'), ('ocr', '文字识别'), ('manual', '人工整理')], max_length=24)),
                ('mean_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('quality_status', models.CharField(choices=[('complete', '文本完整'), ('empty', '未识别到文字'), ('low_confidence', '识别置信度较低'), ('failed', '处理失败')], default='complete', max_length=24)),
                ('quality_message', models.CharField(blank=True, max_length=300)),
                ('review_status', models.CharField(choices=[('needs_review', '待复核'), ('reviewed', '已复核')], default='needs_review', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_curriculum_standard_pages', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='curriculum_standards.curriculumstandardversion')),
            ],
            options={
                'ordering': ['version_id', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumStandardNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('core_competency', '核心素养'), ('course_objective', '课程目标'), ('course_content', '课程内容'), ('academic_quality', '学业质量')], max_length=32)),
                ('code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=240)),
                ('content', models.TextField()),
                ('source_page_start', models.PositiveIntegerField()),
                ('source_page_end', models.PositiveIntegerField()),
                ('source_paragraph', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='curriculum_standards.curriculumstandardnode')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='curriculum_standards.curriculumstandardversion')),
            ],
            options={
                'ordering': ['version_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumStandardAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_standard_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='curriculum_standards.curriculumstandard')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='curriculum_standards.curriculumstandardversion')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='curriculumstandard',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_standards', to='curriculum_standards.curriculumstandardversion'),
        ),
        migrations.CreateModel(
            name='EvaluationPlanCurriculumReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_evaluation_curriculum_references', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_evaluation_plan_references', to='curriculum_standards.curriculumstandardnode')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_references', to='learning_analytics.evaluationplan')),
            ],
            options={
                'ordering': ['node__sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationPlanVersionCurriculumReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_version_hash', models.CharField(max_length=64)),
                ('node_content_hash', models.CharField(max_length=64)),
                ('standard_title', models.CharField(max_length=240)),
                ('version_label', models.CharField(max_length=80)),
                ('node_type', models.CharField(choices=[('core_competency', '核心素养'), ('course_objective', '课程目标'), ('course_content', '课程内容'), ('academic_quality', '学业质量')], max_length=32)),
                ('node_code', models.CharField(max_length=80)),
                ('node_title', models.CharField(max_length=240)),
                ('source_page_start', models.PositiveIntegerField()),
                ('source_page_end', models.PositiveIntegerField()),
                ('source_paragraph', models.CharField(blank=True, max_length=240)),
                ('alignment_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_evaluation_plan_references', to='curriculum_standards.curriculumstandardnode')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_references', to='learning_analytics.evaluationplanversion')),
            ],
            options={
                'ordering': ['node_type', 'node_code', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='curriculumstandardversion',
            index=models.Index(fields=['source', 'status', 'publication_year'], name='curriculum__source__6e15d2_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumstandardversion',
            index=models.Index(fields=['status', 'published_at'], name='curriculum__status_b69b83_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumstandardversion',
            constraint=models.UniqueConstraint(fields=('source', 'version_label'), name='uniq_curriculum_standard_version_label'),
        ),
        migrations.AddConstraint(
            model_name='curriculumstandardversion',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='uniq_curriculum_standard_content_hash'),
        ),
        migrations.AddConstraint(
            model_name='curriculumstandardversion',
            constraint=models.UniqueConstraint(fields=('source', 'pdf_sha256'), name='uniq_curriculum_standard_pdf_hash'),
        ),
        migrations.AddIndex(
            model_name='curriculumstandardpage',
            index=models.Index(fields=['version', 'review_status', 'page_number'], name='curriculum__version_526686_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumstandardpage',
            constraint=models.UniqueConstraint(fields=('version', 'page_number'), name='uniq_curriculum_standard_page_number'),
        ),
        migrations.AddIndex(
            model_name='curriculumstandardnode',
            index=models.Index(fields=['version', 'node_type', 'sort_order'], name='curriculum__version_3bf4ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumstandardnode',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='uniq_curriculum_node_code'),
        ),
        migrations.AddIndex(
            model_name='curriculumstandardauditlog',
            index=models.Index(fields=['version', 'created_at'], name='curriculum__version_c1a5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumstandard',
            index=models.Index(fields=['school_stage', 'document_type', 'subject_code'], name='curriculum__school__ea8e30_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumstandard',
            index=models.Index(fields=['is_active', 'updated_at'], name='curriculum__is_acti_07c5ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumstandard',
            constraint=models.UniqueConstraint(fields=('school_stage', 'document_type', 'subject_code'), name='uniq_curriculum_standard_identity'),
        ),
        migrations.AddConstraint(
            model_name='evaluationplancurriculumreference',
            constraint=models.UniqueConstraint(fields=('plan', 'node'), name='uniq_evaluation_plan_curriculum_node'),
        ),
        migrations.AddConstraint(
            model_name='evaluationplanversioncurriculumreference',
            constraint=models.UniqueConstraint(fields=('plan_version', 'node'), name='uniq_evaluation_plan_version_curriculum_node'),
        ),
    ]
