# Generated by Django 5.2.15 on 2026-07-22 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(default='pdf_text_extraction', max_length=40)),
                ('mode', models.CharField(choices=[('auto', '自动提取（必要时文字识别）'), ('ocr', '全文文字识别')], default='auto', max_length=16)),
                ('priority', models.CharField(choices=[('high', '优先'), ('normal', '普通'), ('low', '后台')], default='low', max_length=16)),
                ('status', models.CharField(choices=[('queued', '等待处理'), ('running', '处理中'), ('succeeded', '处理成功'), ('failed', '处理失败'), ('cancelling', '正在取消'), ('cancelled', '已取消')], db_index=True, default='queued', max_length=16)),
                ('stage', models.CharField(choices=[('queued', '等待处理'), ('preparing', '校验原始文件'), ('extracting', '提取 PDF 文字'), ('ocr', '逐页文字识别'), ('validating', '校验处理结果'), ('committing', '写入处理结果'), ('finished', '处理完成'), ('failed', '处理失败'), ('cancelled', '已取消')], default='queued', max_length=24)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('source_pdf_sha256', models.CharField(max_length=64)),
                ('source_content_hash', models.CharField(max_length=64)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('worker_hostname', models.CharField(blank=True, max_length=255)),
                ('heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_curriculum_processing_jobs', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_curriculum_processing_jobs', to=settings.AUTH_USER_MODEL)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='curriculum_standards.curriculumprocessingjob')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='curriculum_standards.curriculumstandardversion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumProcessingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('extraction_method', models.CharField(choices=[('embedded_text', 'PDF 内嵌文字'), ('ocr', '文字识别'), ('manual', '人工整理')], max_length=24)),
                ('mean_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('quality_status', models.CharField(choices=[('complete', '文本完整'), ('empty', '未识别到文字'), ('low_confidence', '识别置信度较低'), ('failed', '处理失败')], default='complete', max_length=24)),
                ('quality_message', models.CharField(blank=True, max_length=300)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_pages', to='curriculum_standards.curriculumprocessingjob')),
            ],
            options={
                'ordering': ['job_id', 'page_number'],
            },
        ),
        migrations.AddIndex(
            model_name='curriculumprocessingjob',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='curriculum__status_e9aa45_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumprocessingjob',
            index=models.Index(fields=['version', 'created_at'], name='curriculum__version_073070_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumprocessingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running', 'cancelling'])), fields=('version',), name='uniq_active_curriculum_processing_job'),
        ),
        migrations.AddConstraint(
            model_name='curriculumprocessingpage',
            constraint=models.UniqueConstraint(fields=('job', 'page_number'), name='uniq_curriculum_processing_page_number'),
        ),
    ]
