# Generated by Django 5.2.15 on 2026-07-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_standards', '0002_curriculumprocessingjob_curriculumprocessingpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumprocessingjob',
            name='dispatch_attempted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumprocessingjob',
            name='dispatch_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
