# Generated by Django 5.2.15 on 2026-07-22 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_standards', '0003_curriculumprocessingjob_dispatch_attempted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumRetrievalIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('keyword_v1', '关键词检索 v1')], default='keyword_v1', max_length=32)),
                ('strategy', models.CharField(default='char_boundary', max_length=64)),
                ('strategy_version', models.CharField(default='1', max_length=32)),
                ('max_chars', models.PositiveIntegerField(default=1200)),
                ('overlap_chars', models.PositiveIntegerField(default=200)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('index_hash', models.CharField(db_index=True, max_length=64)),
                ('version_content_hash', models.CharField(db_index=True, max_length=64)),
                ('pdf_sha256', models.CharField(db_index=True, max_length=64)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('built_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='built_curriculum_retrieval_indexes', to=settings.AUTH_USER_MODEL)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_index', to='curriculum_standards.curriculumstandardversion')),
            ],
            options={
                'ordering': ['version_id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumRetrievalChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=64, unique=True)),
                ('source_kind', models.CharField(choices=[('page', '逐页原文'), ('content_item', '课程标准内容条目')], max_length=24)),
                ('source_locator', models.CharField(max_length=160)),
                ('source_object_id', models.PositiveBigIntegerField()),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('char_count', models.PositiveIntegerField()),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('source_text_sha256', models.CharField(db_index=True, max_length=64)),
                ('source_content_hash', models.CharField(db_index=True, max_length=64)),
                ('version_content_hash', models.CharField(db_index=True, max_length=64)),
                ('pdf_sha256', models.CharField(db_index=True, max_length=64)),
                ('source_page_start', models.PositiveIntegerField()),
                ('source_page_end', models.PositiveIntegerField()),
                ('source_page_hashes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_chunks', to='curriculum_standards.curriculumstandardnode')),
                ('source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_chunks', to='curriculum_standards.curriculumstandardpage')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_chunks', to='curriculum_standards.curriculumstandardversion')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='curriculum_standards.curriculumretrievalindex')),
            ],
            options={
                'ordering': ['version_id', 'source_kind', 'source_locator', 'ordinal'],
            },
        ),
        migrations.AddIndex(
            model_name='curriculumretrievalindex',
            index=models.Index(fields=['backend', 'built_at'], name='curriculum__backend_57f71a_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumretrievalindex',
            index=models.Index(fields=['version_content_hash', 'index_hash'], name='curriculum__version_30884f_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumretrievalchunk',
            index=models.Index(fields=['version', 'source_kind', 'ordinal'], name='curriculum__version_4d8a67_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumretrievalchunk',
            index=models.Index(fields=['version', 'source_page_start', 'source_page_end'], name='curriculum__version_f07687_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumretrievalchunk',
            constraint=models.UniqueConstraint(fields=('version', 'source_kind', 'source_locator', 'ordinal'), name='uniq_curriculum_retrieval_source_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='curriculumretrievalchunk',
            constraint=models.CheckConstraint(condition=models.Q(('source_page_end__gte', models.F('source_page_start'))), name='curriculum_retrieval_page_range_valid'),
        ),
    ]
