# Generated by Django 5.2.15 on 2026-07-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='school',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('disabled', '停用'), ('archived', '归档')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
