# Generated by Django 5.2.15 on 2026-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_address_school_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('disabled', '停用'), ('archived', '归档')], default='active', max_length=16),
        ),
    ]
