# Generated by Django 5.2.15 on 2026-07-01 15:28

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_students_active(apps, schema_editor):
    StudentProfile = apps.get_model("school", "StudentProfile")
    StudentProfile.objects.filter(class_group__isnull=False, current_layer__isnull=False).update(
        is_first_use=False,
        onboarding_status="active",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_classgroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='class_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_first_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('new', '首次使用'), ('password_updated', '已改密码'), ('class_selected', '已选班级'), ('pretest_completed', '已完成前测'), ('active', '已进入平台')], default='new', max_length=32),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pretest_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.classgroup'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_layer',
            field=models.CharField(blank=True, choices=[('A', '拓展挑战层'), ('B', '核心发展层'), ('C', '基础提升层')], max_length=1, null=True),
        ),
        migrations.RunPython(mark_existing_students_active, migrations.RunPython.noop),
    ]
