# Generated by Django 5.2.15 on 2026-07-01 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_studentprofile_class_selected_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='uniq_student_no_per_class',
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('student_no', ''), _negated=True), fields=('class_group', 'student_no'), name='uniq_student_no_per_class_when_present'),
        ),
    ]
