# Generated by Django 5.2.15 on 2026-07-02 00:58

from django.conf import settings
from django.db import migrations, models


def dedupe_teaching_assignments(apps, schema_editor):
    TeachingAssignment = apps.get_model("school", "TeachingAssignment")
    ClassGroup = apps.get_model("school", "ClassGroup")
    TeachingAssignment.objects.filter(status="disabled").delete()
    seen = set()
    duplicate_ids = []
    for item in TeachingAssignment.objects.order_by("school_id", "class_group_id", "teacher_id", "id"):
        key = (item.school_id, item.class_group_id, item.teacher_id)
        if key in seen:
            duplicate_ids.append(item.id)
        else:
            seen.add(key)
    if duplicate_ids:
        TeachingAssignment.objects.filter(id__in=duplicate_ids).delete()

    for class_group in ClassGroup.objects.all():
        teacher_ids = TeachingAssignment.objects.filter(class_group=class_group).values_list("teacher_id", flat=True)
        class_group.teachers.set(list(teacher_ids))


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_classgroup_graduated_at_classgroup_graduated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'ordering': ['teacher__username', 'class_group__grade', 'class_group__name']},
        ),
        migrations.RemoveConstraint(
            model_name='teachingassignment',
            name='uniq_teaching_assignment',
        ),
        migrations.RunPython(dedupe_teaching_assignments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='teachingassignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teachingassignment',
            name='note',
        ),
        migrations.RemoveField(
            model_name='teachingassignment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='teachingassignment',
            name='status',
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('school', 'class_group', 'teacher'), name='uniq_teaching_assignment_teacher_class'),
        ),
    ]
