# Generated by Django 5.2.15 on 2026-07-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0008_simplify_teaching_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_synthetic",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
