# Generated by Django 5.2.15 on 2026-07-17 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0013_learningwebpage_learningwebpageresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomChatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whole_class_enabled', models.BooleanField(default=False)),
                ('teacher_private_enabled', models.BooleanField(default=False)),
                ('group_chat_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_config', to='courses.classroomsession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_classroom_chat_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('content_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('moderation_status', models.CharField(choices=[('visible', '已发送'), ('pending', '待教师审核'), ('removed', '已撤回')], default='visible', max_length=16)),
                ('severity', models.CharField(choices=[('none', '正常'), ('mild', '轻微'), ('moderate', '一般'), ('severe', '严重')], default='none', max_length=16)),
                ('moderation_categories', models.JSONField(blank=True, default=list)),
                ('matched_rules', models.JSONField(blank=True, default=list)),
                ('review_action', models.CharField(choices=[('none', '未处理'), ('allow', '放行'), ('warn', '警告'), ('remove', '撤回'), ('deduct', '扣分')], default='none', max_length=16)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('deduction_points', models.FloatField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_classroom_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('whole_class', '全班聊天'), ('teacher_private', '与老师聊天'), ('group', '小组聊天')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='courses.classroomgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='courses.classroomsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_classroom_chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by_states', to='realtime.classroomchatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_chat_read_states', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='realtime.classroomchatthread')),
            ],
        ),
        migrations.AddField(
            model_name='classroomchatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='realtime.classroomchatthread'),
        ),
        migrations.AddIndex(
            model_name='classroomchatthread',
            index=models.Index(fields=['session', 'room_type', 'updated_at'], name='realtime_cl_session_15cf13_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomchatthread',
            constraint=models.UniqueConstraint(condition=models.Q(('room_type', 'whole_class')), fields=('session',), name='uniq_whole_class_chat_thread'),
        ),
        migrations.AddConstraint(
            model_name='classroomchatthread',
            constraint=models.UniqueConstraint(condition=models.Q(('room_type', 'teacher_private')), fields=('session', 'student'), name='uniq_private_chat_thread_per_student'),
        ),
        migrations.AddConstraint(
            model_name='classroomchatthread',
            constraint=models.UniqueConstraint(condition=models.Q(('room_type', 'group')), fields=('session', 'group'), name='uniq_group_chat_thread'),
        ),
        migrations.AddConstraint(
            model_name='classroomchatthread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('room_type', 'whole_class'), ('student__isnull', True)), models.Q(('group__isnull', True), ('room_type', 'teacher_private'), ('student__isnull', False)), models.Q(('group__isnull', False), ('room_type', 'group'), ('student__isnull', True)), _connector='OR'), name='valid_classroom_chat_thread_target'),
        ),
        migrations.AddIndex(
            model_name='classroomchatreadstate',
            index=models.Index(fields=['user', 'last_read_at'], name='realtime_cl_user_id_79b61a_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomchatreadstate',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='uniq_classroom_chat_read_state'),
        ),
        migrations.AddIndex(
            model_name='classroomchatmessage',
            index=models.Index(fields=['thread', 'moderation_status', 'created_at'], name='realtime_cl_thread__b221c0_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomchatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='realtime_cl_sender__db30fd_idx'),
        ),
    ]
