# Generated by Django 5.2.15 on 2026-07-18 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0008_simplify_teaching_assignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsOperatingMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("collect_only", "仅采集"),
                            ("shadow", "影子运行"),
                            ("teacher_review", "教师审核"),
                            ("active", "正式投放"),
                            ("suspended", "已暂停"),
                        ],
                        default="collect_only",
                        max_length=24,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_operating_mode",
                        to="school.school",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_analytics_operating_modes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["school_id"],
            },
        ),
        migrations.CreateModel(
            name="SensitiveInferenceAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("actor_role", models.CharField(blank=True, max_length=20)),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("purpose", models.CharField(max_length=128)),
                ("field_categories", models.JSONField(blank=True, default=list)),
                ("export_requested", models.BooleanField(default=False)),
                ("access_granted", models.BooleanField(default=False)),
                ("denial_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensitive_inference_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensitive_inference_access_logs",
                        to="school.classgroup",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensitive_inference_access_logs",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["school", "created_at"],
                        name="learning_an_school__8135d6_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="learning_an_actor_i_dc88ec_idx",
                    ),
                    models.Index(
                        fields=["class_group", "created_at"],
                        name="learning_an_class_g_a78a98_idx",
                    ),
                    models.Index(
                        fields=["access_granted", "created_at"],
                        name="learning_an_access__943e50_idx",
                    ),
                ],
            },
        ),
    ]
