# Generated by Django 5.2.15 on 2026-07-18 11:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_neutralize_automatic_group_names"),
        ("learning_analytics", "0001_initial"),
        ("school", "0008_simplify_teaching_assignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSchemaDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=128)),
                ("schema_version", models.CharField(max_length=16)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "启用"),
                            ("retired", "停用"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "privacy_class",
                    models.CharField(
                        choices=[
                            ("operational", "运行数据"),
                            ("behavioral", "学习行为"),
                            ("assessment", "测评数据"),
                            ("intervention", "教师干预"),
                            ("system_quality", "系统质量"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "analysis_unit",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("group", "小组"),
                            ("class", "班级"),
                            ("content", "学习内容"),
                            ("system", "系统"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload_schema", models.JSONField(default=dict)),
                ("required_context_fields", models.JSONField(blank=True, default=list)),
                ("allowed_sources", models.JSONField(blank=True, default=list)),
                ("requires_target_student", models.BooleanField(default=True)),
                ("requires_opportunity", models.BooleanField(default=False)),
                ("schema_hash", models.CharField(editable=False, max_length=64)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["event_name", "schema_version"],
                "indexes": [
                    models.Index(
                        fields=["status", "event_name"],
                        name="learning_an_status_488bd6_idx",
                    ),
                    models.Index(
                        fields=["privacy_class", "status"],
                        name="learning_an_privacy_337df7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_name", "schema_version"),
                        name="uniq_analytics_event_schema_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LearningEventV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("event_name", models.CharField(max_length=128)),
                ("schema_version", models.CharField(max_length=16)),
                ("source", models.CharField(max_length=64)),
                ("client_version", models.CharField(blank=True, max_length=32)),
                ("object_type", models.CharField(blank=True, max_length=64)),
                ("object_id", models.CharField(blank=True, max_length=128)),
                ("object_version", models.CharField(blank=True, max_length=64)),
                ("opportunity_id", models.UUIDField(blank=True, null=True)),
                ("attempt_id", models.UUIDField(blank=True, null=True)),
                ("client_session_id", models.UUIDField(blank=True, null=True)),
                (
                    "client_sequence",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("client_occurred_at", models.DateTimeField(db_index=True)),
                (
                    "server_received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("score_raw", models.FloatField(blank=True, null=True)),
                ("score_max", models.FloatField(blank=True, null=True)),
                ("delivered_band", models.CharField(blank=True, max_length=8)),
                ("rubric_version", models.CharField(blank=True, max_length=64)),
                ("model_version", models.CharField(blank=True, max_length=128)),
                (
                    "privacy_class",
                    models.CharField(
                        choices=[
                            ("operational", "运行数据"),
                            ("behavioral", "学习行为"),
                            ("assessment", "测评数据"),
                            ("intervention", "教师干预"),
                            ("system_quality", "系统质量"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "analysis_unit",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("group", "小组"),
                            ("class", "班级"),
                            ("content", "学习内容"),
                            ("system", "系统"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("received", "已接收"),
                            ("schema_valid", "模式有效"),
                            ("context_valid", "上下文有效"),
                            ("deduplicated", "已去重"),
                            ("accepted", "已接受"),
                            ("quarantined", "已隔离"),
                            ("legacy_unmapped", "旧事件未映射"),
                        ],
                        default="received",
                        max_length=24,
                    ),
                ),
                ("quality_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_events_v2",
                        to="school.classgroup",
                    ),
                ),
                (
                    "classroom_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_events_v2",
                        to="courses.classroomsession",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_events_v2",
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_events_v2",
                        to="courses.lesson",
                    ),
                ),
                (
                    "lesson_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_events_v2",
                        to="courses.lessonstep",
                    ),
                ),
                (
                    "schema_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="learning_analytics.eventschemadefinition",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_events_v2",
                        to="school.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_events_v2",
                        to="courses.subject",
                    ),
                ),
                (
                    "target_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-server_received_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["school", "server_received_at"],
                        name="learning_an_school__31f8b1_idx",
                    ),
                    models.Index(
                        fields=["target_student", "subject", "client_occurred_at"],
                        name="learning_an_target__9ab809_idx",
                    ),
                    models.Index(
                        fields=["event_name", "server_received_at"],
                        name="learning_an_event_n_5f73c1_idx",
                    ),
                    models.Index(
                        fields=["class_group", "client_occurred_at"],
                        name="learning_an_class_g_8a1c5e_idx",
                    ),
                    models.Index(
                        fields=["quality_status", "server_received_at"],
                        name="learning_an_quality_a97f54_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "event_id"),
                        name="uniq_analytics_event_id_per_school",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("score_max__isnull", True),
                            ("score_max__gt", 0),
                            _connector="OR",
                        ),
                        name="analytics_event_score_max_positive",
                    ),
                ],
            },
        ),
    ]
