# Generated by Django 5.2.15 on 2026-07-18 12:05

import django.db.models.deletion
import django.utils.timezone
import learning_analytics.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_neutralize_automatic_group_names"),
        ("learning_analytics", "0002_eventschemadefinition_learningeventv2"),
        ("school", "0008_simplify_teaching_assignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningEventRejection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rejection_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("event_id", models.UUIDField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=64)),
                ("event_name", models.CharField(blank=True, max_length=128)),
                ("schema_version", models.CharField(blank=True, max_length=16)),
                ("source", models.CharField(blank=True, max_length=64)),
                ("client_occurred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "server_received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("error_code", models.CharField(max_length=64)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("encrypted_envelope", models.TextField()),
                ("envelope_hash", models.CharField(max_length=64)),
                ("envelope_size_bytes", models.PositiveIntegerField(default=0)),
                ("encryption_key_id", models.CharField(max_length=16)),
                ("is_replayable", models.BooleanField(default=True)),
                (
                    "replay_status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("replayed", "已重放"),
                            ("discarded", "已丢弃"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("retention_expires_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-server_received_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="learningeventv2",
            name="event_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="learningeventv2",
            name="idempotency_key",
            field=models.CharField(
                default=learning_analytics.models.new_event_idempotency_key,
                editable=False,
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="learningeventv2",
            constraint=models.UniqueConstraint(
                fields=("school", "idempotency_key"),
                name="uniq_analytics_idempotency_per_school",
            ),
        ),
        migrations.AddField(
            model_name="learningeventrejection",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_event_rejections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="learningeventrejection",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="learning_event_rejections",
                to="school.school",
            ),
        ),
        migrations.AddIndex(
            model_name="learningeventrejection",
            index=models.Index(
                fields=["school", "server_received_at"],
                name="learning_an_school__a95200_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningeventrejection",
            index=models.Index(
                fields=["school", "error_code", "server_received_at"],
                name="learning_an_school__47f0ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningeventrejection",
            index=models.Index(
                fields=["replay_status", "retention_expires_at"],
                name="learning_an_replay__d93782_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningeventrejection",
            index=models.Index(
                fields=["event_id"], name="learning_an_event_i_2e3f23_idx"
            ),
        ),
    ]
