# Generated by Django 5.2.15 on 2026-07-18 12:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_neutralize_automatic_group_names"),
        ("learning_analytics", "0003_learningeventrejection_and_more"),
        ("school", "0008_simplify_teaching_assignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningOpportunity",
            fields=[
                (
                    "opportunity_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("resource", "资源"),
                            ("video", "视频"),
                            ("document", "文档"),
                            ("question", "题目"),
                            ("task", "任务"),
                            ("learning_page", "AI 学习网页"),
                            ("project", "项目"),
                        ],
                        max_length=24,
                    ),
                ),
                ("object_id", models.CharField(max_length=128)),
                ("object_version", models.CharField(max_length=64)),
                ("required", models.BooleanField(default=True)),
                ("delivered_band", models.CharField(default="all", max_length=8)),
                ("support_version", models.CharField(blank=True, max_length=64)),
                ("unit_key", models.CharField(blank=True, max_length=128)),
                (
                    "instructional_phase",
                    models.CharField(
                        choices=[
                            ("orientation", "导入定向"),
                            ("planning", "计划"),
                            ("execution", "执行"),
                            ("monitoring", "监控"),
                            ("revision", "修订"),
                            ("reflection", "反思"),
                            ("unspecified", "未标注"),
                        ],
                        default="unspecified",
                        max_length=24,
                    ),
                ),
                ("group_key", models.CharField(blank=True, max_length=128)),
                ("artifact_key", models.CharField(blank=True, max_length=128)),
                ("role_version", models.CharField(blank=True, max_length=64)),
                ("assigned_at", models.DateTimeField()),
                ("released_at", models.DateTimeField()),
                ("available_from", models.DateTimeField()),
                ("available_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_learning_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_opportunities",
                        to="school.classgroup",
                    ),
                ),
                (
                    "classroom_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_opportunities",
                        to="courses.classroomsession",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_opportunities",
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_opportunities",
                        to="courses.lesson",
                    ),
                ),
                (
                    "lesson_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_opportunities",
                        to="courses.lessonstep",
                    ),
                ),
                (
                    "release_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="released_opportunities",
                        to="learning_analytics.learningeventv2",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_opportunities",
                        to="school.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_opportunities",
                        to="courses.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-released_at", "student_id"],
            },
        ),
        migrations.AddField(
            model_name="learningeventv2",
            name="opportunity_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="learning_analytics.learningopportunity",
            ),
        ),
        migrations.CreateModel(
            name="LearningOpportunityTransitionFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transition_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("assigned", "已分配"),
                            ("released", "已开放"),
                            ("exposed", "已呈现"),
                            ("started", "已开始"),
                            ("submitted", "已提交"),
                            ("graded", "已评分"),
                            ("withdrawn", "已撤回"),
                            ("excused", "已豁免"),
                            ("unavailable", "不可用"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_opportunity_transition_facts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transition_facts",
                        to="learning_analytics.learningopportunity",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunity_transition_facts",
                        to="learning_analytics.learningeventv2",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="learningopportunity",
            index=models.Index(
                fields=["school", "class_group", "released_at"],
                name="learning_an_school__5b569c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningopportunity",
            index=models.Index(
                fields=["student", "subject", "released_at"],
                name="learning_an_student_e80714_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningopportunity",
            index=models.Index(
                fields=["content_type", "object_id", "object_version"],
                name="learning_an_content_57d9ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningopportunity",
            index=models.Index(
                fields=["available_to"], name="learning_an_availab_dba5e6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="learningopportunity",
            constraint=models.UniqueConstraint(
                fields=("student", "release_event"),
                name="uniq_opportunity_student_release_event",
            ),
        ),
        migrations.AddIndex(
            model_name="learningopportunitytransitionfact",
            index=models.Index(
                fields=["opportunity", "occurred_at"],
                name="learning_an_opportu_1aa9c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningopportunitytransitionfact",
            index=models.Index(
                fields=["state", "occurred_at"], name="learning_an_state_bc1014_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningopportunitytransitionfact",
            index=models.Index(
                fields=["source_event"], name="learning_an_source__64cfd9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="learningopportunitytransitionfact",
            constraint=models.UniqueConstraint(
                fields=("opportunity", "state", "source_event"),
                name="uniq_opportunity_state_source_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningopportunitytransitionfact",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ["withdrawn", "excused", "unavailable"])
                ),
                fields=("opportunity",),
                name="uniq_opportunity_terminal_fact",
            ),
        ),
    ]
