# Generated by Django 5.2.15 on 2026-07-18 12:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_neutralize_automatic_group_names"),
        ("learning_analytics", "0004_learningopportunity_and_more"),
        ("school", "0008_simplify_teaching_assignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentResultFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("attempt_id", models.UUIDField()),
                ("object_id", models.CharField(max_length=128)),
                ("object_version", models.CharField(max_length=64)),
                ("grade_version", models.PositiveIntegerField()),
                (
                    "grading_state",
                    models.CharField(
                        choices=[
                            ("pending", "待评分"),
                            ("final", "最终评分"),
                            ("revised", "修订评分"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "score_raw",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("score_max", models.DecimalField(decimal_places=4, max_digits=12)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "grader_type",
                    models.CharField(
                        choices=[
                            ("automatic", "自动评分"),
                            ("teacher", "教师评分"),
                            ("rubric", "量规评分"),
                        ],
                        max_length=16,
                    ),
                ),
                ("graded_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_result_facts",
                        to="school.classgroup",
                    ),
                ),
                (
                    "classroom_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_result_facts",
                        to="courses.classroomsession",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_result_facts",
                        to="courses.course",
                    ),
                ),
                (
                    "grader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_results_graded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_result_facts",
                        to="courses.lesson",
                    ),
                ),
                (
                    "lesson_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_result_facts",
                        to="courses.lessonstep",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_result_facts",
                        to="learning_analytics.learningopportunity",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_result_facts",
                        to="school.school",
                    ),
                ),
                (
                    "source_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_result_fact",
                        to="learning_analytics.learningeventv2",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_result_facts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_result_facts",
                        to="courses.subject",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="learning_analytics.assessmentresultfact",
                    ),
                ),
            ],
            options={
                "ordering": ["opportunity_id", "attempt_id", "grade_version"],
                "indexes": [
                    models.Index(
                        fields=["school", "subject", "graded_at"],
                        name="learning_an_school__52ac6f_idx",
                    ),
                    models.Index(
                        fields=["student", "subject", "graded_at"],
                        name="learning_an_student_07aa44_idx",
                    ),
                    models.Index(
                        fields=["opportunity", "attempt_id", "grade_version"],
                        name="learning_an_opportu_988887_idx",
                    ),
                    models.Index(
                        fields=["grading_state", "recorded_at"],
                        name="learning_an_grading_c7e5d0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("opportunity", "attempt_id", "grade_version"),
                        name="uniq_assessment_result_grade_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score_max__gt", 0)),
                        name="assessment_result_score_max_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("score_raw__isnull", True),
                            ("score_raw__gte", 0),
                            _connector="OR",
                        ),
                        name="assessment_result_score_raw_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("score_raw__isnull", True),
                            ("score_raw__lte", models.F("score_max")),
                            _connector="OR",
                        ),
                        name="assessment_result_score_within_max",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParticipationPointLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("academic_period", models.CharField(blank=True, max_length=32)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("award", "加分"),
                            ("deduction", "扣分"),
                            ("reversal", "冲正"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason_code", models.CharField(max_length=64)),
                ("delta", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("occurred_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participation_points_awarded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participation_point_entries",
                        to="school.classgroup",
                    ),
                ),
                (
                    "classroom_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participation_point_entries",
                        to="courses.classroomsession",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participation_point_entries",
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participation_point_entries",
                        to="courses.lesson",
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal_entries",
                        to="learning_analytics.participationpointledger",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participation_point_entries",
                        to="school.school",
                    ),
                ),
                (
                    "source_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participation_point_entry",
                        to="learning_analytics.learningeventv2",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participation_point_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participation_point_entries",
                        to="courses.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["school", "class_group", "recorded_at"],
                        name="learning_an_school__5f78f6_idx",
                    ),
                    models.Index(
                        fields=["student", "recorded_at"],
                        name="learning_an_student_967bee_idx",
                    ),
                    models.Index(
                        fields=["classroom_session", "recorded_at"],
                        name="learning_an_classro_4de2ab_idx",
                    ),
                    models.Index(
                        fields=["reason_code", "recorded_at"],
                        name="learning_an_reason__7f7f0b_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("delta", 0), _negated=True),
                        name="participation_point_delta_nonzero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("delta__gte", -100), ("delta__lte", 100)),
                        name="participation_point_delta_bounded",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("balance_before__gte", 0), ("balance_after__gte", 0)
                        ),
                        name="participation_point_balance_nonnegative",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("reversal_of__isnull", False)),
                        fields=("reversal_of",),
                        name="uniq_participation_point_reversal",
                    ),
                ],
            },
        ),
    ]
