# Generated by Django 5.2.15 on 2026-07-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_testassessment_randomization"),
        ("learning_analytics", "0005_assessmentresultfact_participationpointledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningeventv2",
            name="legacy_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analytics_event_v2",
                to="learning.learningevent",
            ),
        ),
    ]
