# Generated by Django 5.2.15 on 2026-07-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_analytics", "0006_learningeventv2_legacy_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningopportunity",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("resource", "资源"),
                    ("video", "视频"),
                    ("document", "文档"),
                    ("question", "题目"),
                    ("task", "任务"),
                    ("learning_page", "AI 学习网页"),
                    ("project", "项目"),
                    ("attendance", "签到考勤"),
                ],
                max_length=24,
            ),
        ),
    ]
