# Generated by Django 5.2.15 on 2026-07-19 01:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0008_classroom_interaction_type'),
        ('school', '0008_simplify_teaching_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pipeline_type', models.CharField(choices=[('data_quality', '数据质量')], default='data_quality', max_length=32)),
                ('trigger', models.CharField(choices=[('scheduled', '定时'), ('manual', '手动'), ('retry', '重试')], default='scheduled', max_length=16)),
                ('status', models.CharField(choices=[('pending', '等待'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败'), ('blocked', '质量阻断')], default='pending', max_length=16)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('methodology_version', models.CharField(max_length=32)),
                ('code_version', models.CharField(blank=True, max_length=64)),
                ('config_hash', models.CharField(max_length=64)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='learning_analytics.analyticspipelinerun')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_pipeline_runs', to='school.school')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('task_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', '等待'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=16)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='learning_analytics.analyticspipelinerun')),
            ],
            options={
                'ordering': ['pipeline_run_id', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('methodology_version', models.CharField(max_length=32)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('green', '正常'), ('amber', '关注'), ('red', '阻断')], max_length=16)),
                ('gate_passed', models.BooleanField(default=False)),
                ('event_count', models.PositiveBigIntegerField(default=0)),
                ('ingestion_attempt_count', models.PositiveBigIntegerField(default=0)),
                ('rejection_count', models.PositiveBigIntegerField(default=0)),
                ('legacy_unmapped_count', models.PositiveBigIntegerField(default=0)),
                ('unlinked_legacy_count', models.PositiveBigIntegerField(default=0)),
                ('duplicate_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                ('invalid_event_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                ('late_event_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                ('semantic_missing_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                ('opportunity_coverage_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                ('client_offline_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                ('v1_v2_difference_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                ('thresholds', models.JSONField(default=dict)),
                ('counts', models.JSONField(default=dict)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quality_report', to='learning_analytics.analyticspipelinerun')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_quality_reports', to='school.school')),
            ],
            options={
                'ordering': ['-window_end', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventIngestionDailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_date', models.DateField()),
                ('source', models.CharField(max_length=64)),
                ('accepted_count', models.PositiveBigIntegerField(default=0)),
                ('duplicate_count', models.PositiveBigIntegerField(default=0)),
                ('rejected_count', models.PositiveBigIntegerField(default=0)),
                ('late_count', models.PositiveBigIntegerField(default=0)),
                ('offline_count', models.PositiveBigIntegerField(default=0)),
                ('schema_error_count', models.PositiveBigIntegerField(default=0)),
                ('context_error_count', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_ingestion_daily_counters', to='school.school')),
            ],
            options={
                'ordering': ['-counter_date', 'school_id', 'source'],
            },
        ),
        migrations.AddIndex(
            model_name='analyticspipelinerun',
            index=models.Index(fields=['school', 'pipeline_type', 'created_at'], name='learning_an_school__281b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticspipelinerun',
            index=models.Index(fields=['status', 'created_at'], name='learning_an_status_8f8088_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticspipelinerun',
            index=models.Index(fields=['window_end', 'pipeline_type'], name='learning_an_window__ea2485_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticspipelinerun',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger', 'scheduled')), fields=('school', 'pipeline_type', 'window_start', 'window_end'), name='uniq_scheduled_pipeline_school_window'),
        ),
        migrations.AddIndex(
            model_name='analyticstaskrun',
            index=models.Index(fields=['pipeline_run', 'status'], name='learning_an_pipelin_4c63d9_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticstaskrun',
            index=models.Index(fields=['task_name', 'created_at'], name='learning_an_task_na_1ed982_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticstaskrun',
            constraint=models.UniqueConstraint(fields=('pipeline_run', 'task_name', 'attempt_no'), name='uniq_analytics_task_run_attempt'),
        ),
        migrations.AddIndex(
            model_name='dataqualityreport',
            index=models.Index(fields=['school', 'window_end', 'status'], name='learning_an_school__51867a_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualityreport',
            index=models.Index(fields=['gate_passed', 'window_end'], name='learning_an_gate_pa_8d645d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventingestiondailycounter',
            index=models.Index(fields=['school', 'counter_date'], name='learning_an_school__dc209b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventingestiondailycounter',
            index=models.Index(fields=['source', 'counter_date'], name='learning_an_source_4db1da_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventingestiondailycounter',
            constraint=models.UniqueConstraint(fields=('school', 'counter_date', 'source'), name='uniq_event_ingestion_counter_school_date_source'),
        ),
    ]
