# Generated by Django 5.2.15 on 2026-07-19 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_analytics", "0009_analyticspipelinerun_analyticstaskrun_and_more"),
        ("school", "0009_school_is_synthetic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyntheticDatasetRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("dataset_key", models.CharField(max_length=64, unique=True)),
                ("generator_version", models.CharField(max_length=32)),
                ("seed", models.PositiveBigIntegerField()),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("configuration", models.JSONField(default=dict)),
                ("manifest_hash", models.CharField(blank=True, max_length=64)),
                ("counts", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待生成"),
                            ("running", "生成中"),
                            ("succeeded", "生成成功"),
                            ("failed", "生成失败"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=1000)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="synthetic_dataset_runs",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="learningeventv2",
            name="synthetic_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="learning_analytics.syntheticdatasetrun",
            ),
        ),
        migrations.CreateModel(
            name="SyntheticStudentTruth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prior_mastery", models.DecimalField(decimal_places=4, max_digits=5)),
                ("engagement", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "self_regulation",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("response_speed", models.DecimalField(decimal_places=4, max_digits=5)),
                ("growth_rate", models.DecimalField(decimal_places=5, max_digits=6)),
                ("class_effect", models.DecimalField(decimal_places=5, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="synthetic_truth_records",
                        to="school.classgroup",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="synthetic_truth_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "synthetic_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_truths",
                        to="learning_analytics.syntheticdatasetrun",
                    ),
                ),
            ],
            options={
                "ordering": ["synthetic_run_id", "class_group_id", "student_id"],
            },
        ),
        migrations.AddIndex(
            model_name="syntheticdatasetrun",
            index=models.Index(
                fields=["school", "status", "created_at"],
                name="learning_an_school__da3560_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syntheticdatasetrun",
            index=models.Index(
                fields=["generator_version", "created_at"],
                name="learning_an_generat_49eec8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syntheticstudenttruth",
            index=models.Index(
                fields=["synthetic_run", "class_group"],
                name="learning_an_synthet_fa4c88_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="syntheticstudenttruth",
            constraint=models.UniqueConstraint(
                fields=("synthetic_run", "student"),
                name="uniq_synthetic_truth_run_student",
            ),
        ),
    ]
