# Generated by Django 5.2.15 on 2026-07-19 04:16

import django.db.models.deletion
from datetime import date
from django.db import migrations, models


def backfill_synthetic_quality_scope(apps, schema_editor):
    SyntheticDatasetRun = apps.get_model("learning_analytics", "SyntheticDatasetRun")
    AnalyticsPipelineRun = apps.get_model("learning_analytics", "AnalyticsPipelineRun")
    DataQualityReport = apps.get_model("learning_analytics", "DataQualityReport")
    EventIngestionDailyCounter = apps.get_model(
        "learning_analytics", "EventIngestionDailyCounter"
    )
    for run in SyntheticDatasetRun.objects.select_related("school").filter(
        school__is_synthetic=True
    ):
        pipelines = AnalyticsPipelineRun.objects.filter(
            school_id=run.school_id,
            window_start=run.window_start,
            window_end=run.window_end,
        )
        pipeline_ids = list(pipelines.values_list("id", flat=True))
        pipelines.update(synthetic_run_id=run.id)
        DataQualityReport.objects.filter(pipeline_run_id__in=pipeline_ids).update(
            synthetic_run_id=run.id
        )
        configuration = run.configuration if isinstance(run.configuration, dict) else {}
        start_text = configuration.get("start_date")
        end_text = configuration.get("end_date")
        if start_text and end_text:
            EventIngestionDailyCounter.objects.filter(
                school_id=run.school_id,
                counter_date__gte=date.fromisoformat(start_text),
                counter_date__lte=date.fromisoformat(end_text),
            ).update(synthetic_run_id=run.id)


def clear_synthetic_quality_scope(apps, schema_editor):
    apps.get_model("learning_analytics", "DataQualityReport").objects.update(
        synthetic_run_id=None
    )
    apps.get_model("learning_analytics", "AnalyticsPipelineRun").objects.update(
        synthetic_run_id=None
    )
    apps.get_model("learning_analytics", "EventIngestionDailyCounter").objects.update(
        synthetic_run_id=None
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning_analytics",
            "0010_syntheticdatasetrun_learningeventv2_synthetic_run_and_more",
        ),
        ("school", "0009_school_is_synthetic"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventingestiondailycounter",
            name="uniq_event_ingestion_counter_school_date_source",
        ),
        migrations.AddField(
            model_name="analyticspipelinerun",
            name="synthetic_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analytics_pipeline_runs",
                to="learning_analytics.syntheticdatasetrun",
            ),
        ),
        migrations.AddField(
            model_name="dataqualityreport",
            name="synthetic_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="data_quality_reports",
                to="learning_analytics.syntheticdatasetrun",
            ),
        ),
        migrations.AddField(
            model_name="eventingestiondailycounter",
            name="synthetic_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingestion_daily_counters",
                to="learning_analytics.syntheticdatasetrun",
            ),
        ),
        migrations.AddField(
            model_name="syntheticdatasetrun",
            name="mode",
            field=models.CharField(
                choices=[
                    ("isolated_school", "独立模拟学校"),
                    ("school_overlay", "校内测试叠加"),
                ],
                default="isolated_school",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="syntheticdatasetrun",
            name="purge_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="syntheticdatasetrun",
            name="purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="syntheticdatasetrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待生成"),
                    ("running", "生成中"),
                    ("succeeded", "生成成功"),
                    ("failed", "生成失败"),
                    ("purged", "已清理"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.RunPython(
            backfill_synthetic_quality_scope,
            clear_synthetic_quality_scope,
        ),
        migrations.AddConstraint(
            model_name="eventingestiondailycounter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("synthetic_run__isnull", True)),
                fields=("school", "counter_date", "source"),
                name="uniq_operational_ingest_counter_day_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventingestiondailycounter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("synthetic_run__isnull", False)),
                fields=("school", "counter_date", "source", "synthetic_run"),
                name="uniq_synthetic_ingest_counter_day_source",
            ),
        ),
    ]
