# Generated by Django 5.2.15 on 2026-07-19 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_group_collaboration_evidence'),
        ('learning_analytics', '0011_remove_eventingestiondailycounter_uniq_event_ingestion_counter_school_date_source_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricCriterionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('module', models.CharField(choices=[('P', 'P 成果与任务质量'), ('S', 'S 策略质量'), ('R', 'R 调节过程'), ('C', 'C 协作与反馈'), ('D', 'D 学科实践'), ('E', 'E 伦理与责任实践')], max_length=1)),
                ('title', models.CharField(max_length=160)),
                ('evaluation_object', models.CharField(max_length=300)),
                ('evidence_sources', models.JSONField(default=list)),
                ('observable_evidence', models.TextField()),
                ('not_assessed_condition', models.TextField()),
                ('allowed_supports', models.JSONField(blank=True, default=list)),
                ('counter_examples', models.JSONField(default=list)),
                ('anchor_level_1', models.TextField()),
                ('anchor_level_2', models.TextField()),
                ('anchor_level_3', models.TextField()),
                ('anchor_level_4', models.TextField()),
                ('anchor_level_5', models.TextField()),
                ('next_formative_action', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('intended_use', models.CharField(choices=[('local_formative', '本地形成性'), ('school_common', '校级共同测量'), ('research_linked', '研究链接')], default='local_formative', max_length=32)),
                ('task_version', models.CharField(blank=True, max_length=64)),
                ('target_population', models.CharField(blank=True, max_length=300)),
                ('course_goal', models.TextField(blank=True)),
                ('claims', models.JSONField(blank=True, default=list)),
                ('evidence_rules', models.JSONField(blank=True, default=list)),
                ('task_specifications', models.JSONField(blank=True, default=list)),
                ('content_coverage', models.JSONField(blank=True, default=list)),
                ('cognitive_complexity', models.JSONField(blank=True, default=list)),
                ('allowed_supports', models.JSONField(blank=True, default=list)),
                ('scoring_model', models.JSONField(blank=True, default=dict)),
                ('next_formative_action', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('unvalidated', '尚未验证'), ('content_review_pending', '待内容审查'), ('content_reviewed', '已完成内容审查'), ('pilot_scheduled', '已安排试测'), ('pilot_completed', '已完成试测'), ('validated', '已验证')], default='unvalidated', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_blueprints', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessment_blueprints', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_blueprints', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_blueprints', to='courses.subject')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_assessment_blueprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentBlueprintVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('intended_use', models.CharField(choices=[('local_formative', '本地形成性'), ('school_common', '校级共同测量'), ('research_linked', '研究链接')], max_length=32)),
                ('task_version', models.CharField(max_length=64)),
                ('target_population', models.CharField(max_length=300)),
                ('course_goal', models.TextField()),
                ('claims', models.JSONField(default=list)),
                ('evidence_rules', models.JSONField(default=list)),
                ('task_specifications', models.JSONField(default=list)),
                ('content_coverage', models.JSONField(default=list)),
                ('cognitive_complexity', models.JSONField(default=list)),
                ('allowed_supports', models.JSONField(blank=True, default=list)),
                ('scoring_model', models.JSONField(default=dict)),
                ('next_formative_action', models.TextField()),
                ('validation_status', models.CharField(choices=[('unvalidated', '尚未验证'), ('content_review_pending', '待内容审查'), ('content_reviewed', '已完成内容审查'), ('pilot_scheduled', '已安排试测'), ('pilot_completed', '已完成试测'), ('validated', '已验证')], default='unvalidated', max_length=32)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_blueprint_versions', to='courses.course')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_assessment_blueprint_versions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_blueprint_versions', to='school.school')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='learning_analytics.assessmentblueprint')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_blueprint_versions', to='courses.subject')),
            ],
            options={
                'ordering': ['source_id', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='RubricAnchorExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('evidence_summary', models.TextField()),
                ('artifact_reference', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anchor_examples', to='learning_analytics.rubriccriterionversion')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RubricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('intended_use', models.CharField(choices=[('local_formative', '本地形成性'), ('school_common', '校级共同测量'), ('research_linked', '研究链接')], default='local_formative', max_length=32)),
                ('evaluation_object', models.CharField(blank=True, max_length=300)),
                ('criteria', models.JSONField(blank=True, default=list)),
                ('validation_status', models.CharField(choices=[('unvalidated', '尚未验证'), ('content_review_pending', '待内容审查'), ('content_reviewed', '已完成内容审查'), ('pilot_scheduled', '已安排试测'), ('pilot_completed', '已完成试测'), ('validated', '已验证')], default='unvalidated', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_drafts', to='learning_analytics.assessmentblueprint')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubric_definitions', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rubric_definitions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_definitions', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_definitions', to='courses.subject')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_rubric_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RubricDefinitionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('intended_use', models.CharField(choices=[('local_formative', '本地形成性'), ('school_common', '校级共同测量'), ('research_linked', '研究链接')], max_length=32)),
                ('evaluation_object', models.CharField(max_length=300)),
                ('validation_status', models.CharField(choices=[('unvalidated', '尚未验证'), ('content_review_pending', '待内容审查'), ('content_reviewed', '已完成内容审查'), ('pilot_scheduled', '已安排试测'), ('pilot_completed', '已完成试测'), ('validated', '已验证')], default='unvalidated', max_length=32)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_versions', to='learning_analytics.assessmentblueprintversion')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubric_definition_versions', to='courses.course')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_rubric_definition_versions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_definition_versions', to='school.school')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='learning_analytics.rubricdefinition')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_definition_versions', to='courses.subject')),
            ],
            options={
                'ordering': ['source_id', '-version_no'],
            },
        ),
        migrations.AddField(
            model_name='rubriccriterionversion',
            name='rubric_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criteria', to='learning_analytics.rubricdefinitionversion'),
        ),
        migrations.AddIndex(
            model_name='assessmentblueprint',
            index=models.Index(fields=['school', 'subject', 'updated_at'], name='learning_an_school__1a117e_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentblueprint',
            index=models.Index(fields=['created_by', 'updated_at'], name='learning_an_created_774f60_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentblueprintversion',
            index=models.Index(fields=['school', 'subject', 'published_at'], name='learning_an_school__67d5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentblueprintversion',
            index=models.Index(fields=['intended_use', 'validation_status'], name='learning_an_intende_46c7ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentblueprintversion',
            constraint=models.UniqueConstraint(fields=('source', 'version_no'), name='uniq_blueprint_version_no'),
        ),
        migrations.AddConstraint(
            model_name='assessmentblueprintversion',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='uniq_blueprint_content_hash'),
        ),
        migrations.AddConstraint(
            model_name='rubricanchorexample',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 5)), name='rubric_anchor_example_level_1_5'),
        ),
        migrations.AddConstraint(
            model_name='rubricanchorexample',
            constraint=models.UniqueConstraint(fields=('criterion', 'sort_order'), name='uniq_rubric_anchor_example_order'),
        ),
        migrations.AddIndex(
            model_name='rubricdefinition',
            index=models.Index(fields=['school', 'subject', 'updated_at'], name='learning_an_school__d8fdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricdefinition',
            index=models.Index(fields=['created_by', 'updated_at'], name='learning_an_created_fb5f60_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricdefinitionversion',
            index=models.Index(fields=['school', 'subject', 'published_at'], name='learning_an_school__662c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricdefinitionversion',
            index=models.Index(fields=['intended_use', 'validation_status'], name='learning_an_intende_9bbd87_idx'),
        ),
        migrations.AddConstraint(
            model_name='rubricdefinitionversion',
            constraint=models.UniqueConstraint(fields=('source', 'version_no'), name='uniq_rubric_version_no'),
        ),
        migrations.AddConstraint(
            model_name='rubricdefinitionversion',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='uniq_rubric_content_hash'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterionversion',
            constraint=models.UniqueConstraint(fields=('rubric_version', 'code'), name='uniq_rubric_criterion_code'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterionversion',
            constraint=models.UniqueConstraint(fields=('rubric_version', 'sort_order'), name='uniq_rubric_criterion_order'),
        ),
    ]
