# Generated by Django 5.2.15 on 2026-07-19 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_group_collaboration_evidence'),
        ('learning_analytics', '0013_rename_measurement_to_evaluation'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evaluationplan',
            new_name='learning_an_school__668f4d_idx',
            old_name='learning_an_school__1a117e_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluationplan',
            new_name='learning_an_created_0adb19_idx',
            old_name='learning_an_created_774f60_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluationplanversion',
            new_name='learning_an_school__8be976_idx',
            old_name='learning_an_school__67d5ad_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluationstandard',
            new_name='learning_an_school__1644da_idx',
            old_name='learning_an_school__d8fdf7_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluationstandard',
            new_name='learning_an_created_9418d6_idx',
            old_name='learning_an_created_fb5f60_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluationstandardversion',
            new_name='learning_an_school__966a5b_idx',
            old_name='learning_an_school__662c2f_idx',
        ),
        migrations.AlterField(
            model_name='evaluationplan',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_plans', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='evaluationplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_evaluation_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluationplan',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_plans', to='school.school'),
        ),
        migrations.AlterField(
            model_name='evaluationplan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_plans', to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='evaluationplan',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_evaluation_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluationplanversion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_plan_versions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='evaluationplanversion',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_evaluation_plan_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluationplanversion',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_plan_versions', to='school.school'),
        ),
        migrations.AlterField(
            model_name='evaluationplanversion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_plan_versions', to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='evaluationscoringexample',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoring_examples', to='learning_analytics.evaluationcriterionversion'),
        ),
        migrations.AlterField(
            model_name='evaluationstandard',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_standards', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='evaluationstandard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_evaluation_standards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluationstandard',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_standards', to='learning_analytics.evaluationplan'),
        ),
        migrations.AlterField(
            model_name='evaluationstandard',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_standards', to='school.school'),
        ),
        migrations.AlterField(
            model_name='evaluationstandard',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_standards', to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='evaluationstandard',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_evaluation_standards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluationstandardversion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_standard_versions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='evaluationstandardversion',
            name='plan_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_standard_versions', to='learning_analytics.evaluationplanversion'),
        ),
        migrations.AlterField(
            model_name='evaluationstandardversion',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_evaluation_standard_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluationstandardversion',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_standard_versions', to='school.school'),
        ),
        migrations.AlterField(
            model_name='evaluationstandardversion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_standard_versions', to='courses.subject'),
        ),
        migrations.AddIndex(
            model_name='evaluationplanversion',
            index=models.Index(fields=['scope', 'review_status'], name='learning_an_scope_64210a_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationstandardversion',
            index=models.Index(fields=['scope', 'review_status'], name='learning_an_scope_7ea0d1_idx'),
        ),
    ]
