# Generated by Django 5.2.15 on 2026-07-19 07:14

from django.db import migrations, models


REPORT_KEY_RENAMES = {
    "gate_passed": "checks_passed",
    "quality_status": "check_status",
    "issue_count": "problem_count",
    "ingestion_attempt_count": "receive_attempt_count",
    "rejection_count": "rejected_event_count",
    "legacy_unmapped_count": "unconverted_old_event_count",
    "unlinked_legacy_count": "unlinked_old_event_count",
    "semantic_missing_rate": "unconverted_old_event_rate",
    "opportunity_coverage_rate": "learning_task_link_rate",
    "v1_v2_difference_rate": "old_new_event_difference_rate",
    "operational_event_count": "non_migration_event_count",
    "counter_accepted_count": "recorded_accepted_event_count",
    "rejection_fact_count": "stored_rejection_count",
    "counter_rejected_count": "recorded_rejection_count",
    "opportunity_expected_count": "learning_task_expected_count",
    "opportunity_linked_count": "learning_task_linked_count",
    "telemetry_complete": "receive_counts_complete",
    "explicit_offline_count": "reported_offline_count",
    "student_web_count": "student_web_event_count",
    "v1_total_count": "old_event_total_count",
    "v1_v2_difference_count": "old_new_event_difference_count",
}

RECONCILIATION_KEY_RENAMES = {
    "unlinked_legacy_count": "unlinked_old_event_count",
    "legacy_dual_write_count": "old_event_live_write_count",
    "analytics_mapped_count": "new_event_linked_count",
    "historical_mapped_count": "converted_old_event_count",
    "historical_unmapped_count": "unconverted_old_event_count",
    "missing_v2_count": "missing_new_event_count",
    "mapping_mismatch_count": "conversion_mismatch_count",
    "missing_v2_examples": "missing_new_event_examples",
    "mapping_mismatch_examples": "conversion_mismatch_examples",
    "legacy_event_id": "old_event_id",
    "analytics_event_id": "new_event_id",
    "consistent": "records_match",
}

TASK_NAME_RENAMES = {
    "collect_event_quality": "collect_learning_data",
    "reconcile_v1_v2": "compare_old_new_records",
    "publish_quality_report": "save_data_check_report",
}

ISSUE_CODE_RENAMES = {
    "ingestion_telemetry_incomplete": "receive_counts_incomplete",
}


def _rename_mapping_keys(value, mapping):
    if isinstance(value, list):
        return [_rename_mapping_keys(item, mapping) for item in value]
    if not isinstance(value, dict):
        return value
    renamed = {}
    for key, item in value.items():
        renamed[mapping.get(key, key)] = _rename_mapping_keys(item, mapping)
    return renamed


def _rename_issue(issue, mapping, code_mapping):
    if not isinstance(issue, dict):
        return issue
    renamed = _rename_mapping_keys(issue, mapping)
    metric = renamed.get("metric")
    old_code = str(renamed.get("code") or "")
    renamed["code"] = code_mapping.get(old_code, old_code)
    for old_metric, new_metric in mapping.items():
        if old_code.startswith(f"{old_metric}_"):
            renamed["code"] = f"{new_metric}_{old_code[len(old_metric) + 1:]}"
            break
    if metric in mapping:
        renamed["metric"] = mapping[metric]
    return renamed


def _convert_saved_data(apps, schema_editor, *, reverse=False):
    DataQualityReport = apps.get_model("learning_analytics", "DataQualityReport")
    AnalyticsPipelineRun = apps.get_model(
        "learning_analytics", "AnalyticsPipelineRun"
    )
    AnalyticsTaskRun = apps.get_model("learning_analytics", "AnalyticsTaskRun")

    key_mapping = (
        {value: key for key, value in REPORT_KEY_RENAMES.items()}
        if reverse
        else REPORT_KEY_RENAMES
    )
    task_mapping = (
        {value: key for key, value in TASK_NAME_RENAMES.items()}
        if reverse
        else TASK_NAME_RENAMES
    )
    issue_code_mapping = (
        {value: key for key, value in ISSUE_CODE_RENAMES.items()}
        if reverse
        else ISSUE_CODE_RENAMES
    )

    for report in DataQualityReport.objects.all().iterator():
        thresholds = _rename_mapping_keys(report.thresholds, key_mapping)
        counts = _rename_mapping_keys(report.counts, key_mapping)
        issues = [
            _rename_issue(issue, key_mapping, issue_code_mapping)
            for issue in report.issues
        ]
        DataQualityReport.objects.filter(pk=report.pk).update(
            thresholds=thresholds,
            counts=counts,
            issues=issues,
        )

    for run in AnalyticsPipelineRun.objects.all().iterator():
        AnalyticsPipelineRun.objects.filter(pk=run.pk).update(
            summary=_rename_mapping_keys(run.summary, key_mapping)
        )

    for task in AnalyticsTaskRun.objects.all().iterator():
        reconciliation_task = task.task_name in {
            "reconcile_v1_v2",
            "compare_old_new_records",
        }
        task_key_source = (
            RECONCILIATION_KEY_RENAMES
            if reconciliation_task
            else REPORT_KEY_RENAMES
        )
        task_key_mapping = (
            {value: key for key, value in task_key_source.items()}
            if reverse
            else task_key_source
        )
        AnalyticsTaskRun.objects.filter(pk=task.pk).update(
            task_name=task_mapping.get(task.task_name, task.task_name),
            metrics=_rename_mapping_keys(task.metrics, task_key_mapping),
        )


def convert_saved_data(apps, schema_editor):
    _convert_saved_data(apps, schema_editor)


def restore_saved_data(apps, schema_editor):
    _convert_saved_data(apps, schema_editor, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0016_cleanup_evaluation_wording_and_hashes'),
        ('school', '0009_school_is_synthetic'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dataqualityreport',
            name='learning_an_gate_pa_8d645d_idx',
        ),
        migrations.RenameField(
            model_name='dataqualityreport',
            old_name='gate_passed',
            new_name='checks_passed',
        ),
        migrations.RenameField(
            model_name='dataqualityreport',
            old_name='opportunity_coverage_rate',
            new_name='learning_task_link_rate',
        ),
        migrations.RenameField(
            model_name='dataqualityreport',
            old_name='semantic_missing_rate',
            new_name='unconverted_old_event_rate',
        ),
        migrations.RenameField(
            model_name='dataqualityreport',
            old_name='ingestion_attempt_count',
            new_name='receive_attempt_count',
        ),
        migrations.RenameField(
            model_name='dataqualityreport',
            old_name='legacy_unmapped_count',
            new_name='unconverted_old_event_count',
        ),
        migrations.RenameField(
            model_name='dataqualityreport',
            old_name='rejection_count',
            new_name='rejected_event_count',
        ),
        migrations.RenameField(
            model_name='dataqualityreport',
            old_name='v1_v2_difference_rate',
            new_name='old_new_event_difference_rate',
        ),
        migrations.RenameField(
            model_name='dataqualityreport',
            old_name='unlinked_legacy_count',
            new_name='unlinked_old_event_count',
        ),
        migrations.RenameField(
            model_name='analyticspipelinerun',
            old_name='methodology_version',
            new_name='check_version',
        ),
        migrations.RenameField(
            model_name='dataqualityreport',
            old_name='methodology_version',
            new_name='check_version',
        ),
        migrations.RenameField(
            model_name='dataqualityreport',
            old_name='source_fingerprint',
            new_name='source_checksum',
        ),
        migrations.AlterField(
            model_name='analyticspipelinerun',
            name='pipeline_type',
            field=models.CharField(
                choices=[('data_quality', '数据检查')],
                default='data_quality',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='analyticspipelinerun',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', '等待'),
                    ('running', '运行中'),
                    ('succeeded', '成功'),
                    ('failed', '失败'),
                    ('blocked', '检查未通过'),
                ],
                default='pending',
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='dataqualityreport',
            name='status',
            field=models.CharField(
                choices=[
                    ('green', '正常'),
                    ('amber', '需关注'),
                    ('red', '未通过'),
                ],
                max_length=16,
            ),
        ),
        migrations.RunPython(convert_saved_data, restore_saved_data),
        migrations.AddIndex(
            model_name='dataqualityreport',
            index=models.Index(fields=['checks_passed', 'window_end'], name='learning_an_checks__3c7ee2_idx'),
        ),
    ]
