# Generated by Django 5.2.15 on 2026-07-19 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0017_rename_data_check_fields'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTrialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('content_review', '内容审核'), ('classroom_trial', '课堂试用'), ('scorer_training', '评分培训'), ('scoring_check', '评分一致性检查')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('planned', '待进行'), ('in_progress', '进行中'), ('completed', '已完成')], default='planned', max_length=24)),
                ('activity_date', models.DateField()),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('agreement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conclusion', models.CharField(choices=[('pending', '待确认'), ('ready', '可使用'), ('revise', '需要修改'), ('hold', '暂不使用')], default='pending', max_length=24)),
                ('summary', models.TextField(blank=True)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_evaluation_trial_records', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_trial_records', to='school.school')),
                ('standard_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_records', to='learning_analytics.evaluationstandardversion')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_evaluation_trial_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', '-id'],
                'indexes': [models.Index(fields=['school', 'activity_date'], name='learning_an_school__86b928_idx'), models.Index(fields=['school', 'record_type', 'status'], name='learning_an_school__757c03_idx'), models.Index(fields=['standard_version', 'activity_date'], name='learning_an_standar_504414_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('agreement_rate__isnull', True), models.Q(('agreement_rate__gte', 0), ('agreement_rate__lte', 100)), _connector='OR'), name='evaluation_trial_agreement_rate_0_100')],
            },
        ),
    ]
