# Generated by Django 5.2.15 on 2026-07-19 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_rename_rubric_version_to_evaluation_version'),
        ('learning', '0008_lesson_step_attempts_and_attachment_versions'),
        ('learning_analytics', '0018_evaluationtrialrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStepEvaluationBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_self', models.BooleanField(default=False)),
                ('enable_peer', models.BooleanField(default=False)),
                ('enable_teacher', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_lesson_step_evaluation_bindings', to=settings.AUTH_USER_MODEL)),
                ('lesson_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_standard_binding', to='courses.lessonstep')),
                ('standard_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_step_bindings', to='learning_analytics.evaluationstandardversion')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_lesson_step_evaluation_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lesson_step_id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomEvaluationStandardUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_config_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_uses', to='courses.classroomevaluationconfigversion')),
                ('lesson_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_evaluation_uses', to='courses.lessonstep')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_classroom_evaluation_standard_uses', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_standard_use', to='courses.classroomsession')),
                ('standard_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_uses', to='learning_analytics.evaluationstandardversion')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_uses', to='learning_analytics.lessonstepevaluationbinding')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSubmissionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_step_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_evidence', to='learning.lessonstepattempt')),
                ('standard_use', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_evidence', to='learning_analytics.classroomevaluationstandarduse')),
                ('student_work_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_evidence', to='learning.studentworkattachment')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='standard_evidence', to='courses.classroomevaluationsubmission')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['standard_use', 'created_at'], name='learning_an_standar_25b03e_idx'), models.Index(fields=['lesson_step_attempt', 'created_at'], name='learning_an_lesson__3e2bda_idx'), models.Index(fields=['student_work_attachment', 'created_at'], name='learning_an_student_c3d2d7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lessonstepevaluationbinding',
            index=models.Index(fields=['standard_version', 'updated_at'], name='learning_an_standar_043b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomevaluationstandarduse',
            index=models.Index(fields=['standard_version', 'created_at'], name='learning_an_standar_ea898e_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomevaluationstandarduse',
            index=models.Index(fields=['lesson_step', 'created_at'], name='learning_an_lesson__ebef81_idx'),
        ),
    ]
