# Generated by Django 5.2.15 on 2026-07-19 15:07

import hashlib
import json

import django.db.models.deletion
from django.db import migrations, models


def migrate_evaluation_runtime(apps, schema_editor):
    StandardUse = apps.get_model("learning_analytics", "ClassroomEvaluationStandardUse")
    Submission = apps.get_model("courses", "ClassroomEvaluationSubmission")
    Session = apps.get_model("courses", "ClassroomSession")

    for use in StandardUse.objects.select_related(
        "binding", "standard_version", "evaluation_config_version"
    ).iterator():
        criteria = use.criteria_snapshot if isinstance(use.criteria_snapshot, list) else []
        legacy_version = use.evaluation_config_version
        enable_self = bool(use.binding.enable_self)
        enable_peer = bool(use.binding.enable_peer)
        enable_teacher = bool(use.binding.enable_teacher)
        snapshot = {
            "standard_version_id": use.standard_version_id,
            "standard_version_no": use.standard_version.version_no,
            "standard_content_hash": use.standard_version.content_hash,
            "enable_self": enable_self,
            "enable_peer": enable_peer,
            "enable_teacher": enable_teacher,
            "self_criteria": (
                legacy_version.self_criteria if legacy_version and enable_self else criteria if enable_self else []
            ),
            "peer_criteria": (
                legacy_version.peer_criteria if legacy_version and enable_peer else criteria if enable_peer else []
            ),
            "teacher_criteria": (
                legacy_version.teacher_criteria if legacy_version and enable_teacher else criteria if enable_teacher else []
            ),
        }
        encoded = json.dumps(
            snapshot, ensure_ascii=False, sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
        use.configuration_snapshot = snapshot
        use.content_hash = hashlib.sha256(encoded).hexdigest()
        use.enable_self = enable_self
        use.enable_peer = enable_peer
        use.enable_teacher = enable_teacher
        use.legacy_compatible = bool(legacy_version)
        use.save(
            update_fields=[
                "configuration_snapshot",
                "content_hash",
                "enable_self",
                "enable_peer",
                "enable_teacher",
                "legacy_compatible",
            ]
        )
        Submission.objects.filter(session_id=use.session_id).update(
            standard_use_id=use.id,
            legacy_compatible=False,
        )
        Session.objects.filter(pk=use.session_id).update(evaluation_config_version_id=None)

    Submission.objects.filter(standard_use__isnull=True).update(legacy_compatible=True)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_classroomevaluationconfig_legacy_only_and_more'),
        ('learning_analytics', '0020_repair_evaluation_schema_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomevaluationstandarduse',
            name='configuration_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='classroomevaluationstandarduse',
            name='content_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='classroomevaluationstandarduse',
            name='enable_peer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroomevaluationstandarduse',
            name='enable_self',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroomevaluationstandarduse',
            name='enable_teacher',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroomevaluationstandarduse',
            name='legacy_compatible',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='classroomevaluationstandarduse',
            name='evaluation_config_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standard_uses', to='courses.classroomevaluationconfigversion'),
        ),
        migrations.RunPython(migrate_evaluation_runtime, migrations.RunPython.noop),
    ]
