# Generated by Django 5.2.15 on 2026-07-19 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_classroomevaluationconfig_legacy_only_and_more'),
        ('learning_analytics', '0021_classroomevaluationstandarduse_configuration_snapshot_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLearningSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_type', models.CharField(choices=[('day', '当日'), ('7d', '近 7 日'), ('30d', '近 30 日'), ('unit', '单元')], max_length=16)),
                ('period_key', models.CharField(max_length=128)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('data_status', models.CharField(choices=[('available', '材料可用'), ('insufficient', '材料不足'), ('no_opportunity', '没有学习任务'), ('quality_blocked', '学习记录需检查')], max_length=24)),
                ('metrics', models.JSONField(default=dict)),
                ('missing_data', models.JSONField(blank=True, default=list)),
                ('source_hash', models.CharField(max_length=64)),
                ('generator_version', models.CharField(default='summary-v1', max_length=32)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_learning_summaries', to='school.classgroup')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_learning_summaries', to='courses.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_learning_summaries', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_summaries', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_learning_summaries', to='courses.subject')),
            ],
            options={
                'ordering': ['-window_end', 'student_id', 'subject_id'],
                'indexes': [models.Index(fields=['school', 'class_group', 'window_type', 'window_end'], name='learning_an_school__999bb6_idx'), models.Index(fields=['student', 'subject', 'window_end'], name='learning_an_student_5540f6_idx'), models.Index(fields=['data_status', 'generated_at'], name='learning_an_data_st_cfcd6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'course', 'window_type', 'period_key'), name='uniq_student_learning_summary_scope')],
            },
        ),
    ]
