# Generated by Django 5.2.15 on 2026-07-19 17:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0026_classroomevaluationconfig_legacy_only_and_more"),
        ("learning_analytics", "0022_studentlearningsummary"),
        ("school", "0009_school_is_synthetic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_key", models.CharField(max_length=96)),
                ("version", models.CharField(max_length=16)),
                ("label", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "evidence_group",
                    models.CharField(
                        choices=[
                            ("F0", "基础情况"),
                            ("E1", "直接行为"),
                            ("E2", "研究候选"),
                            ("E3", "评价派生"),
                            ("F4", "数据与教学条件"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "causal_role",
                    models.CharField(
                        choices=[
                            ("baseline_state", "既往状态"),
                            ("instructional_opportunity", "学习机会"),
                            ("behavior_evidence", "行为事实"),
                            ("treatment", "教师支持"),
                            ("post_treatment", "支持后变化"),
                            ("outcome", "未来结果"),
                            ("data_quality", "数据质量"),
                            ("protected_audit", "受限审查字段"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("ratio", "比例"),
                            ("count", "数量"),
                            ("duration", "时长"),
                            ("continuous", "连续值"),
                        ],
                        max_length=24,
                    ),
                ),
                ("formula", models.TextField()),
                ("windows", models.JSONField(default=list)),
                ("min_n", models.PositiveIntegerField(default=0)),
                ("allowed_events", models.JSONField(blank=True, default=list)),
                ("allowed_uses", models.JSONField(default=list)),
                ("missing_codes", models.JSONField(default=list)),
                ("competing_explanations", models.JSONField(blank=True, default=list)),
                ("fairness_note", models.CharField(blank=True, max_length=500)),
                ("model_input_allowed", models.BooleanField(default=False)),
                ("generator_key", models.CharField(max_length=96)),
                ("code_hash", models.CharField(max_length=64)),
                ("definition_hash", models.CharField(editable=False, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "启用"),
                            ("retired", "停用"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["evidence_group", "feature_key", "version"],
                "indexes": [
                    models.Index(
                        fields=["status", "evidence_group"],
                        name="learning_an_status_d2f9ae_idx",
                    ),
                    models.Index(
                        fields=["causal_role", "status"],
                        name="learning_an_causal__b6d8ff_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feature_key", "version"),
                        name="uniq_feature_definition_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeatureSetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_key", models.CharField(max_length=64)),
                ("version", models.CharField(max_length=16)),
                ("label", models.CharField(max_length=128)),
                ("definition_manifest", models.JSONField(default=list)),
                ("allowed_views", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "启用"),
                            ("retired", "停用"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("manifest_hash", models.CharField(editable=False, max_length=64)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["set_key", "version"],
            },
        ),
        migrations.CreateModel(
            name="DecisionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "scope_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "point_type",
                    models.CharField(
                        choices=[
                            ("weekly", "周度"),
                            ("unit", "单元"),
                            ("manual", "手动"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("operational", "日常教学"),
                            ("pilot", "试运行"),
                            ("research", "正式研究"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "已计划"),
                            ("frozen", "已冻结"),
                            ("cancelled", "已取消"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                (
                    "prediction_horizon_days",
                    models.PositiveSmallIntegerField(default=7),
                ),
                ("allowed_lateness_minutes", models.PositiveIntegerField(default=1440)),
                ("source", models.CharField(default="manual", max_length=32)),
                ("context_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "context_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_decision_points",
                        to="school.classgroup",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_decision_points",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_analysis_decision_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_decision_points",
                        to="school.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_decision_points",
                        to="courses.subject",
                    ),
                ),
                (
                    "synthetic_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_decision_points",
                        to="learning_analytics.syntheticdatasetrun",
                    ),
                ),
                (
                    "feature_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_points",
                        to="learning_analytics.featuresetversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OutcomeDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outcome_key", models.CharField(max_length=96)),
                ("version", models.CharField(max_length=16)),
                ("label", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "outcome_type",
                    models.CharField(
                        choices=[
                            ("ratio", "比例"),
                            ("count", "数量"),
                            ("continuous", "连续值"),
                        ],
                        max_length=24,
                    ),
                ),
                ("horizon_days", models.PositiveSmallIntegerField()),
                ("min_denominator", models.PositiveIntegerField(default=0)),
                ("formula", models.TextField()),
                ("eligibility_rule", models.TextField()),
                ("allowed_evidence", models.JSONField(default=list)),
                ("missing_codes", models.JSONField(default=list)),
                ("generator_key", models.CharField(max_length=96)),
                ("code_hash", models.CharField(max_length=64)),
                ("definition_hash", models.CharField(editable=False, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "启用"),
                            ("retired", "停用"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["outcome_key", "version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("outcome_key", "version"),
                        name="uniq_outcome_definition_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutcomeObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("observation_version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待观察"),
                            ("observed", "已观察"),
                            ("unobserved", "无可用结果"),
                            ("excluded", "已排除"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "eligibility_status",
                    models.CharField(
                        choices=[
                            ("eligible", "符合条件"),
                            ("not_mature", "尚未到期"),
                            ("no_opportunity", "没有对应任务"),
                            ("insufficient_n", "材料数量不足"),
                            ("competing_event", "存在转班等情况"),
                            ("data_error", "学习记录需检查"),
                        ],
                        max_length=24,
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                (
                    "numerator",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                (
                    "denominator",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                ("missing_code", models.CharField(blank=True, max_length=32)),
                ("exclusion_reason", models.CharField(blank=True, max_length=255)),
                ("evidence_refs", models.JSONField(blank=True, default=list)),
                ("source_hash", models.CharField(max_length=64)),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "decision_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcome_observations",
                        to="learning_analytics.decisionpoint",
                    ),
                ),
                (
                    "outcome_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="learning_analytics.outcomedefinition",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_outcome_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="learning_analytics.outcomeobservation",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "decision_point_id",
                    "student_id",
                    "outcome_definition_id",
                    "observation_version",
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentFeatureSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("operational_available", "当时可用数据"),
                            ("reconstructed_complete", "事后完整数据"),
                        ],
                        max_length=32,
                    ),
                ),
                ("as_of", models.DateTimeField()),
                ("values", models.JSONField(default=dict)),
                ("numerators", models.JSONField(default=dict)),
                ("denominators", models.JSONField(default=dict)),
                ("missing_codes", models.JSONField(default=dict)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("window_starts", models.JSONField(default=dict)),
                ("source_watermark", models.JSONField(default=dict)),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("ready", "可用"),
                            ("degraded", "部分可用"),
                            ("blocked", "不可用于分析"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_hash", models.CharField(max_length=64)),
                ("generator_version", models.CharField(max_length=32)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_feature_snapshots",
                        to="school.classgroup",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_feature_snapshots",
                        to="courses.course",
                    ),
                ),
                (
                    "decision_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feature_snapshots",
                        to="learning_analytics.decisionpoint",
                    ),
                ),
                (
                    "feature_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="learning_analytics.featuresetversion",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_feature_snapshots",
                        to="school.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_feature_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_feature_snapshots",
                        to="courses.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of", "student_id", "view_type"],
            },
        ),
        migrations.CreateModel(
            name="TrainingDatasetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("dataset_key", models.CharField(max_length=96, unique=True)),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("operational_available", "当时可用数据"),
                            ("reconstructed_complete", "事后完整数据"),
                        ],
                        default="operational_available",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "生成中"),
                            ("frozen", "已冻结"),
                            ("failed", "生成失败"),
                        ],
                        default="building",
                        max_length=16,
                    ),
                ),
                ("decision_start", models.DateTimeField()),
                ("decision_end", models.DateTimeField()),
                ("split_strategy", models.CharField(max_length=64)),
                ("generator_version", models.CharField(max_length=32)),
                ("manifest", models.JSONField(default=dict)),
                ("manifest_hash", models.CharField(blank=True, max_length=64)),
                ("source_hash", models.CharField(max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("observed_count", models.PositiveIntegerField(default=0)),
                ("unobserved_count", models.PositiveIntegerField(default=0)),
                ("excluded_count", models.PositiveIntegerField(default=0)),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_dataset_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_datasets",
                        to="learning_analytics.featuresetversion",
                    ),
                ),
                (
                    "outcome_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_datasets",
                        to="learning_analytics.outcomedefinition",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_dataset_versions",
                        to="school.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_dataset_versions",
                        to="courses.subject",
                    ),
                ),
                (
                    "synthetic_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_dataset_versions",
                        to="learning_analytics.syntheticdatasetrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingDatasetRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudonymous_key", models.CharField(max_length=64)),
                (
                    "split",
                    models.CharField(
                        choices=[
                            ("train", "训练"),
                            ("validation", "验证"),
                            ("test", "测试"),
                            ("unassigned", "未分配"),
                        ],
                        max_length=16,
                    ),
                ),
                ("split_group_key", models.CharField(max_length=96)),
                ("split_assignments", models.JSONField(default=dict)),
                ("feature_values", models.JSONField(default=dict)),
                ("feature_numerators", models.JSONField(default=dict)),
                ("feature_denominators", models.JSONField(default=dict)),
                ("feature_missing_codes", models.JSONField(default=dict)),
                ("outcome_status", models.CharField(max_length=16)),
                (
                    "outcome_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                (
                    "outcome_numerator",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                (
                    "outcome_denominator",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                ("outcome_missing_code", models.CharField(blank=True, max_length=32)),
                ("row_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_dataset_rows",
                        to="learning_analytics.decisionpoint",
                    ),
                ),
                (
                    "outcome_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_dataset_rows",
                        to="learning_analytics.outcomeobservation",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_dataset_rows",
                        to="learning_analytics.studentfeaturesnapshot",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="learning_analytics.trainingdatasetversion",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_id", "decision_point_id", "pseudonymous_key"],
            },
        ),
        migrations.CreateModel(
            name="DecisionPointStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eligibility_status",
                    models.CharField(
                        choices=[
                            ("eligible", "可纳入"),
                            ("inactive", "账号停用"),
                            ("no_class", "未分班"),
                            ("excluded", "不纳入"),
                        ],
                        default="eligible",
                        max_length=24,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("included", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_scope",
                        to="learning_analytics.decisionpoint",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_decision_point_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["decision_point_id", "student_id"],
                "indexes": [
                    models.Index(
                        fields=["decision_point", "included"],
                        name="learning_an_decisio_2c8af2_idx",
                    ),
                    models.Index(
                        fields=["student", "created_at"],
                        name="learning_an_student_3aa967_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("decision_point", "student"),
                        name="uniq_decision_point_student",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="featuresetversion",
            constraint=models.UniqueConstraint(
                fields=("set_key", "version"), name="uniq_feature_set_version"
            ),
        ),
        migrations.AddIndex(
            model_name="decisionpoint",
            index=models.Index(
                fields=["school", "status", "scheduled_for"],
                name="learning_an_school__527d78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionpoint",
            index=models.Index(
                fields=["class_group", "subject", "scheduled_for"],
                name="learning_an_class_g_f51807_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outcomeobservation",
            index=models.Index(
                fields=["decision_point", "status"],
                name="learning_an_decisio_f4f657_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outcomeobservation",
            index=models.Index(
                fields=["outcome_definition", "window_end", "status"],
                name="learning_an_outcome_b704a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outcomeobservation",
            index=models.Index(
                fields=["student", "window_end"], name="learning_an_student_1c4e7e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="outcomeobservation",
            constraint=models.UniqueConstraint(
                fields=(
                    "decision_point",
                    "student",
                    "outcome_definition",
                    "observation_version",
                ),
                name="uniq_outcome_observation_version",
            ),
        ),
        migrations.AddIndex(
            model_name="studentfeaturesnapshot",
            index=models.Index(
                fields=["school", "subject", "as_of"],
                name="learning_an_school__f8d5f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentfeaturesnapshot",
            index=models.Index(
                fields=["class_group", "quality_status", "as_of"],
                name="learning_an_class_g_bef0ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentfeaturesnapshot",
            index=models.Index(
                fields=["student", "subject", "as_of"],
                name="learning_an_student_e69e38_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentfeaturesnapshot",
            constraint=models.UniqueConstraint(
                fields=("decision_point", "student", "view_type"),
                name="uniq_student_feature_snapshot_view",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingdatasetversion",
            index=models.Index(
                fields=["school", "subject", "created_at"],
                name="learning_an_school__241e3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingdatasetversion",
            index=models.Index(
                fields=["status", "created_at"], name="learning_an_status_2c391c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingdatasetrow",
            index=models.Index(
                fields=["dataset", "split"], name="learning_an_dataset_99e6c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingdatasetrow",
            index=models.Index(
                fields=["decision_point", "split"],
                name="learning_an_decisio_e6c187_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingdatasetrow",
            constraint=models.UniqueConstraint(
                fields=("dataset", "snapshot", "outcome_observation"),
                name="uniq_training_dataset_snapshot_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingdatasetrow",
            constraint=models.UniqueConstraint(
                fields=("dataset", "pseudonymous_key", "decision_point"),
                name="uniq_training_dataset_pseudonym_point",
            ),
        ),
    ]
