# Generated by Django 5.2.15 on 2026-07-19 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_classroomevaluationconfig_legacy_only_and_more'),
        ('learning_analytics', '0023_featuredefinition_featuresetversion_decisionpoint_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LongitudinalAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('run_key', models.CharField(max_length=96, unique=True)),
                ('analysis_version', models.CharField(default='longitudinal-v1', max_length=32)),
                ('status', models.CharField(choices=[('building', '计算中'), ('completed', '已完成'), ('blocked', '数据不足'), ('failed', '计算失败')], default='building', max_length=16)),
                ('manifest', models.JSONField(default=dict)),
                ('manifest_hash', models.CharField(blank=True, max_length=64)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('ready_feature_count', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('class_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_longitudinal_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='longitudinal_runs', to='learning_analytics.trainingdatasetversion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='longitudinal_runs', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='longitudinal_runs', to='courses.subject')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LongitudinalFeatureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=96)),
                ('status', models.CharField(choices=[('ready', '材料足够'), ('insufficient_n', '数据不足'), ('not_applicable', '暂不适用')], max_length=24)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('class_count', models.PositiveIntegerField(default=0)),
                ('total_variance', models.FloatField(blank=True, null=True)),
                ('between_variance', models.FloatField(blank=True, null=True)),
                ('within_variance', models.FloatField(blank=True, null=True)),
                ('intraclass_correlation', models.FloatField(blank=True, null=True)),
                ('overall_association', models.FloatField(blank=True, null=True)),
                ('within_association', models.FloatField(blank=True, null=True)),
                ('between_association', models.FloatField(blank=True, null=True)),
                ('interval_low', models.FloatField(blank=True, null=True)),
                ('interval_high', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=24)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_results', to='learning_analytics.longitudinalanalysisrun')),
            ],
            options={
                'ordering': ['run_id', 'feature_key'],
            },
        ),
        migrations.CreateModel(
            name='ModelComparisonRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('run_key', models.CharField(max_length=96, unique=True)),
                ('comparison_version', models.CharField(default='model-01-v1', max_length=32)),
                ('status', models.CharField(choices=[('building', '计算中'), ('shadow_only', '影子比较'), ('blocked', '暂不输出'), ('failed', '计算失败')], default='building', max_length=16)),
                ('target_type', models.CharField(default='continuous', max_length=24)),
                ('model_keys', models.JSONField(default=list)),
                ('validation_keys', models.JSONField(default=list)),
                ('manifest', models.JSONField(default=dict)),
                ('model_card', models.JSONField(default=dict)),
                ('manifest_hash', models.CharField(blank=True, max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('observed_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_comparison_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_comparison_runs', to='learning_analytics.trainingdatasetversion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_comparison_runs', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_comparison_runs', to='courses.subject')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=16)),
                ('validation_key', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('ready', '可报告'), ('insufficient_n', '数据不足'), ('not_applicable', '暂不适用'), ('blocked', '已阻断')], max_length=24)),
                ('train_count', models.PositiveIntegerField(default=0)),
                ('test_count', models.PositiveIntegerField(default=0)),
                ('predicted_count', models.PositiveIntegerField(default=0)),
                ('abstained_count', models.PositiveIntegerField(default=0)),
                ('primary_metric', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('brier_score', models.FloatField(blank=True, null=True)),
                ('calibration_intercept', models.FloatField(blank=True, null=True)),
                ('calibration_slope', models.FloatField(blank=True, null=True)),
                ('coverage', models.FloatField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='learning_analytics.modelcomparisonrun')),
            ],
            options={
                'ordering': ['run_id', 'validation_key', 'model_key'],
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonymous_key', models.CharField(max_length=64)),
                ('model_key', models.CharField(max_length=16)),
                ('validation_key', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('predicted', '已预测'), ('abstained', '拒绝预测'), ('not_applicable', '暂不适用')], max_length=24)),
                ('predicted_value', models.FloatField(blank=True, null=True)),
                ('observed_value', models.FloatField(blank=True, null=True)),
                ('abstain_reason', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_predictions', to='learning_analytics.trainingdatasetrow')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='learning_analytics.modelevaluationresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='learning_analytics.modelcomparisonrun')),
            ],
        ),
        migrations.CreateModel(
            name='NegativeControlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_key', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('passed', '通过'), ('insufficient_n', '数据不足'), ('failed', '需解释'), ('not_applicable', '暂不适用')], max_length=24)),
                ('expected_behavior', models.CharField(max_length=255)),
                ('observed_metric', models.FloatField(blank=True, null=True)),
                ('baseline_metric', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negative_controls', to='learning_analytics.modelcomparisonrun')),
            ],
            options={
                'ordering': ['run_id', 'control_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='longitudinalanalysisrun',
            constraint=models.UniqueConstraint(fields=('dataset', 'analysis_version'), name='uniq_longitudinal_dataset_version'),
        ),
        migrations.AddConstraint(
            model_name='longitudinalfeatureresult',
            constraint=models.UniqueConstraint(fields=('run', 'feature_key'), name='uniq_longitudinal_run_feature'),
        ),
        migrations.AddConstraint(
            model_name='modelcomparisonrun',
            constraint=models.UniqueConstraint(fields=('dataset', 'comparison_version'), name='uniq_model_comparison_dataset_version'),
        ),
        migrations.AddConstraint(
            model_name='modelevaluationresult',
            constraint=models.UniqueConstraint(fields=('run', 'model_key', 'validation_key'), name='uniq_model_eval_run_model_validation'),
        ),
        migrations.AddIndex(
            model_name='modelprediction',
            index=models.Index(fields=['run', 'model_key', 'validation_key'], name='learning_an_run_id_fc80dc_idx'),
        ),
        migrations.AddIndex(
            model_name='modelprediction',
            index=models.Index(fields=['pseudonymous_key', 'run'], name='learning_an_pseudon_12284a_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelprediction',
            constraint=models.UniqueConstraint(fields=('run', 'dataset_row', 'model_key', 'validation_key'), name='uniq_model_prediction_row_model_fold'),
        ),
        migrations.AddConstraint(
            model_name='negativecontrolresult',
            constraint=models.UniqueConstraint(fields=('run', 'control_key'), name='uniq_negative_control_run_key'),
        ),
    ]
