# Generated by Django 5.2.15 on 2026-07-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0024_longitudinalanalysisrun_longitudinalfeatureresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longitudinalanalysisrun',
            name='manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='modelcomparisonrun',
            name='manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='modelcomparisonrun',
            name='model_card',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='modelcomparisonrun',
            name='model_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='modelcomparisonrun',
            name='validation_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
