# Generated by Django 5.2.15 on 2026-07-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0025_alter_longitudinalanalysisrun_manifest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcomparisonrun',
            name='comparison_version',
            field=models.CharField(default='model-01-v2', max_length=32),
        ),
    ]
