# Generated by Django 5.2.15 on 2026-07-20 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_classroomevaluationconfig_legacy_only_and_more'),
        ('learning_analytics', '0026_alter_modelcomparisonrun_comparison_version'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCalibrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('run_key', models.CharField(max_length=96, unique=True)),
                ('calibration_version', models.CharField(default='model-03-v1', max_length=32)),
                ('model_key', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('building', '生成中'), ('candidate', '待教师使用'), ('blocked', '暂不生成建议'), ('failed', '生成失败'), ('archived', '已归档')], default='building', max_length=16)),
                ('global_parameters', models.JSONField(blank=True, default=dict)),
                ('class_parameters', models.JSONField(blank=True, default=dict)),
                ('model_card', models.JSONField(blank=True, default=dict)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('manifest_hash', models.CharField(blank=True, max_length=64)),
                ('artifact_path', models.CharField(blank=True, max_length=500)),
                ('artifact_hash', models.CharField(blank=True, max_length=64)),
                ('suggestion_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('comparison_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_calibration_runs', to='learning_analytics.modelcomparisonrun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_calibration_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_calibration_runs', to='learning_analytics.trainingdatasetversion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_calibration_runs', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_calibration_runs', to='courses.subject')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['school', 'subject', 'status'], name='learning_an_school__5f1c0e_idx'), models.Index(fields=['comparison_run', 'created_at'], name='learning_an_compari_154176_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'calibration_version'), name='uniq_class_calibration_dataset_version')],
            },
        ),
    ]
