# Generated by Django 5.2.15 on 2026-07-20 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_classroomevaluationconfig_legacy_only_and_more'),
        ('learning_analytics', '0027_classcalibrationrun'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('release_key', models.CharField(max_length=96, unique=True)),
                ('release_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', '当前使用'), ('superseded', '已被新版本替代'), ('rolled_back', '已回退')], default='active', max_length=16)),
                ('is_test_data', models.BooleanField(default=False)),
                ('package_path', models.CharField(max_length=500)),
                ('package_hash', models.CharField(max_length=64)),
                ('package_signature', models.TextField()),
                ('signing_key_id', models.CharField(max_length=64)),
                ('manifest', models.JSONField(default=dict)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='learning_analytics.classcalibrationrun')),
                ('previous_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_releases', to='learning_analytics.modelrelease')),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_model_releases', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_releases', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_releases', to='courses.subject')),
            ],
            options={
                'ordering': ['-released_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ModelReleaseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('publish', '发布'), ('rollback', '回滚'), ('verify', '校验')], max_length=16)),
                ('result', models.CharField(choices=[('succeeded', '成功'), ('failed', '失败')], max_length=16)),
                ('message', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_release_actions', to=settings.AUTH_USER_MODEL)),
                ('calibration_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_audits', to='learning_analytics.classcalibrationrun')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='learning_analytics.modelrelease')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_release_audits', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_release_audits', to='courses.subject')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='modelrelease',
            index=models.Index(fields=['school', 'subject', 'is_test_data', 'status'], name='learning_an_school__0e684c_idx'),
        ),
        migrations.AddIndex(
            model_name='modelrelease',
            index=models.Index(fields=['released_at'], name='learning_an_release_9fb765_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelrelease',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'is_test_data', 'release_version'), name='uniq_model_release_scope_version'),
        ),
        migrations.AddConstraint(
            model_name='modelrelease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('school', 'subject', 'is_test_data'), name='uniq_active_model_release_scope'),
        ),
        migrations.AddConstraint(
            model_name='modelrelease',
            constraint=models.UniqueConstraint(fields=('calibration_run',), name='uniq_model_release_calibration_run'),
        ),
        migrations.AddIndex(
            model_name='modelreleaseaudit',
            index=models.Index(fields=['school', 'subject', 'created_at'], name='learning_an_school__bbcffb_idx'),
        ),
        migrations.AddIndex(
            model_name='modelreleaseaudit',
            index=models.Index(fields=['action', 'result', 'created_at'], name='learning_an_action_1aede2_idx'),
        ),
    ]
