# Generated by Django 5.2.15 on 2026-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics', '0028_modelrelease_modelreleaseaudit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcalibrationrun',
            name='decision_purpose',
            field=models.CharField(choices=[('support', '学习支持'), ('content_band', '学习内容层级')], default='support', max_length=16),
        ),
    ]
