# Generated by Django 5.2.15 on 2026-07-20 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_remove_classroomgroup_uniq_classroom_group_no_per_collaboration_and_more'),
        ('learning_analytics', '0029_classcalibrationrun_decision_purpose'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupingDecisionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trigger', models.CharField(choices=[('lesson_step', '课堂环节'), ('project_stage', '项目阶段'), ('teacher_request', '教师发起')], max_length=24)),
                ('task_context', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', '准备中'), ('candidate_ready', '候选已生成'), ('confirmed', '已确认'), ('closed', '已结束')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_decision_points', to='school.classgroup')),
                ('classroom_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_decision_points', to='courses.classroomsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_decision_points', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_grouping_decision_points', to=settings.AUTH_USER_MODEL)),
                ('lesson_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grouping_decision_points', to='courses.lessonstep')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_decision_points', to='school.school')),
            ],
            options={
                'ordering': ['-scheduled_for', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupingCandidateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('algorithm_version', models.CharField(max_length=32)),
                ('seed', models.BigIntegerField()),
                ('status', models.CharField(choices=[('building', '生成中'), ('ready', '可选择'), ('blocked', '无法生成'), ('failed', '生成失败')], max_length=16)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('candidates', models.JSONField(default=list)),
                ('conflict_explanations', models.JSONField(blank=True, default=list)),
                ('candidate_count', models.PositiveSmallIntegerField(default=0)),
                ('selected_candidate_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_grouping_candidate_runs', to=settings.AUTH_USER_MODEL)),
                ('decision_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_runs', to='learning_analytics.groupingdecisionpoint')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupingPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('plan_version', models.PositiveIntegerField()),
                ('candidate_key', models.CharField(max_length=64)),
                ('assignments', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('confirmed', '已确认'), ('archived', '已归档')], max_length=16)),
                ('adjustment_note', models.CharField(blank=True, max_length=500)),
                ('confirmed_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='learning_analytics.groupingcandidaterun')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_versions', to='courses.classroomgroupcollaboration')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_grouping_plans', to=settings.AUTH_USER_MODEL)),
                ('decision_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='learning_analytics.groupingdecisionpoint')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_plans', to='learning_analytics.groupingplanversion')),
            ],
            options={
                'ordering': ['-plan_version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupingOutcomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.PositiveSmallIntegerField()),
                ('group_result', models.JSONField(default=dict)),
                ('individual_results', models.JSONField(default=list)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_snapshots', to='learning_analytics.groupingplanversion')),
            ],
        ),
        migrations.CreateModel(
            name='GroupingOpportunityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.PositiveSmallIntegerField()),
                ('role', models.CharField(blank=True, max_length=24)),
                ('opportunities', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_opportunity_audits', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_audits', to='learning_analytics.groupingplanversion')),
            ],
        ),
        migrations.CreateModel(
            name='GroupingPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('policy_version', models.CharField(max_length=32)),
                ('strategy', models.CharField(choices=[('random_baseline', '随机分组'), ('readiness_aligned', '准备度接近'), ('readiness_bridged', '相邻互助'), ('skill_complementary', '技能互补'), ('stable_project', '项目稳定'), ('manual', '教师设置')], max_length=32)),
                ('group_size', models.PositiveSmallIntegerField(default=4)),
                ('min_group_size', models.PositiveSmallIntegerField(default=3)),
                ('max_group_size', models.PositiveSmallIntegerField(default=5)),
                ('role_scheme', models.JSONField(blank=True, default=list)),
                ('hard_constraints', models.JSONField(blank=True, default=dict)),
                ('objective_weights', models.JSONField(blank=True, default=dict)),
                ('stability_window_days', models.PositiveSmallIntegerField(default=14)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('retired', '停用')], max_length=16)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grouping_policy_versions', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_grouping_policies', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_grouping_policies', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouping_policy_versions', to='school.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grouping_policy_versions', to='courses.subject')),
            ],
            options={
                'ordering': ['school_id', 'name', '-version_no', '-id'],
            },
        ),
        migrations.AddField(
            model_name='groupingdecisionpoint',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_points', to='learning_analytics.groupingpolicyversion'),
        ),
        migrations.AddField(
            model_name='groupingcandidaterun',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_runs', to='learning_analytics.groupingpolicyversion'),
        ),
        migrations.CreateModel(
            name='GroupingTeacherDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accept', '采用'), ('adjust', '调整后采用'), ('regenerate', '重新生成'), ('manual', '教师设置')], max_length=16)),
                ('candidate_key', models.CharField(blank=True, max_length=64)),
                ('adjustments', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_teacher_decisions', to=settings.AUTH_USER_MODEL)),
                ('candidate_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_decisions', to='learning_analytics.groupingcandidaterun')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_decisions', to='learning_analytics.groupingplanversion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupingFairnessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('passed', '通过'), ('review', '需要检查'), ('blocked', '不能使用')], max_length=16)),
                ('metrics', models.JSONField(default=dict)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fairness_audits', to='learning_analytics.groupingcandidaterun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate_run', 'candidate_key'), name='uniq_grouping_candidate_fairness')],
            },
        ),
        migrations.CreateModel(
            name='GroupingPairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_count', models.PositiveIntegerField(default=0)),
                ('last_collaborated_at', models.DateTimeField()),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_pair_history', to='school.classgroup')),
                ('left_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_pairs_as_left', to=settings.AUTH_USER_MODEL)),
                ('right_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_pairs_as_right', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_pair_history', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grouping_pair_history', to='courses.subject')),
            ],
            options={
                'indexes': [models.Index(fields=['class_group', 'subject', 'collaboration_count'], name='learning_an_class_g_8a1208_idx')],
                'constraints': [models.UniqueConstraint(fields=('class_group', 'subject', 'left_student', 'right_student'), name='uniq_grouping_pair_history')],
            },
        ),
        migrations.AddConstraint(
            model_name='groupingplanversion',
            constraint=models.UniqueConstraint(fields=('collaboration', 'plan_version'), name='uniq_grouping_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='groupingplanversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('collaboration',), name='uniq_confirmed_grouping_plan'),
        ),
        migrations.AddConstraint(
            model_name='groupingoutcomesnapshot',
            constraint=models.UniqueConstraint(fields=('plan', 'group_no', 'observed_at'), name='uniq_grouping_outcome_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='groupingopportunityaudit',
            constraint=models.UniqueConstraint(fields=('plan', 'student'), name='uniq_grouping_plan_student_opportunity'),
        ),
        migrations.AddIndex(
            model_name='groupingpolicyversion',
            index=models.Index(fields=['school', 'status', 'strategy'], name='learning_an_school__77de50_idx'),
        ),
        migrations.AddIndex(
            model_name='groupingpolicyversion',
            index=models.Index(fields=['course', 'status', 'version_no'], name='learning_an_course__e389d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupingpolicyversion',
            constraint=models.UniqueConstraint(fields=('school', 'policy_version'), name='uniq_grouping_policy_version'),
        ),
        migrations.AddIndex(
            model_name='groupingdecisionpoint',
            index=models.Index(fields=['classroom_session', 'status', 'scheduled_for'], name='learning_an_classro_be82ab_idx'),
        ),
        migrations.AddIndex(
            model_name='groupingdecisionpoint',
            index=models.Index(fields=['school', 'class_group', 'created_at'], name='learning_an_school__1b69c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupingcandidaterun',
            constraint=models.UniqueConstraint(fields=('decision_point', 'input_hash', 'algorithm_version'), name='uniq_grouping_candidate_input'),
        ),
    ]
