# Generated by Django 5.2.15 on 2026-07-20 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_classroomgroupcollaboration_grouping_strategy_and_more'),
        ('learning_analytics', '0030_groupingdecisionpoint_groupingcandidaterun_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupingpolicyversion',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('retired', '停用')], default='draft', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='groupingpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True), ('status', 'active'), ('subject__isnull', True)), fields=('school',), name='uniq_active_global_grouping_policy'),
        ),
        migrations.AddConstraint(
            model_name='groupingpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True), ('status', 'active'), ('subject__isnull', False)), fields=('school', 'subject'), name='uniq_active_subject_grouping_policy'),
        ),
        migrations.AddConstraint(
            model_name='groupingpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('status', 'active')), fields=('school', 'course'), name='uniq_active_course_grouping_policy'),
        ),
    ]
