# Generated by Django 5.2.15 on 2026-07-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_analytics", "0031_alter_groupingpolicyversion_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestDataBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_code", models.CharField(max_length=72, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("development_testing", "开发测试"),
                            ("acceptance_testing", "验收测试"),
                            ("migration_verification", "迁移验证"),
                            ("research_sandbox", "研究沙盒"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("historical_manual", "历史或手工测试数据"),
                            ("scripted_fixture", "脚本生成测试数据"),
                            ("migration_result", "迁移验证结果"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField()),
                ("target_count", models.PositiveIntegerField()),
                ("manifest_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_test_data_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["purpose", "created_at"],
                        name="la_tdb_purpose_created",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TestDataObjectMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=64)),
                ("model_name", models.CharField(max_length=64)),
                ("object_pk", models.CharField(max_length=64)),
                ("object_label", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="object_markers",
                        to="learning_analytics.testdatabatch",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_data_object_markers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_test_data_object_markers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["batch_id", "app_label", "model_name", "object_pk"],
                "indexes": [
                    models.Index(
                        fields=["batch", "created_at"],
                        name="la_tdmark_batch_created",
                    ),
                    models.Index(
                        fields=["app_label", "model_name", "object_pk"],
                        name="la_tdmark_object_lookup",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("app_label", "model_name", "object_pk"),
                        name="uniq_test_data_object_marker",
                    )
                ],
            },
        ),
    ]
