# Generated by Django 5.2.15 on 2026-07-22

import hashlib
import json
import re
import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


TARGET_CODE_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,31}$")
REQUIRED_NODE_TYPES = {
    "core_competency",
    "course_objective",
    "course_content",
    "academic_quality",
}


def _canonical_hash(payload):
    encoded = json.dumps(
        payload,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def backfill_learning_target_versions(apps, schema_editor):
    EvaluationPlanVersion = apps.get_model(
        "learning_analytics", "EvaluationPlanVersion"
    )
    EvaluationStandardVersion = apps.get_model(
        "learning_analytics", "EvaluationStandardVersion"
    )
    EvaluationPlanVersionCurriculumReference = apps.get_model(
        "curriculum_standards", "EvaluationPlanVersionCurriculumReference"
    )
    LearningTarget = apps.get_model("learning_analytics", "LearningTarget")
    LearningTargetVersion = apps.get_model(
        "learning_analytics", "LearningTargetVersion"
    )
    LearningTargetCurriculumAlignment = apps.get_model(
        "learning_analytics", "LearningTargetCurriculumAlignment"
    )
    EvaluationBasisLearningTarget = apps.get_model(
        "learning_analytics", "EvaluationBasisLearningTarget"
    )
    LearningActivityLearningTarget = apps.get_model(
        "learning_analytics", "LearningActivityLearningTarget"
    )
    EvaluationTaskLearningTarget = apps.get_model(
        "learning_analytics", "EvaluationTaskLearningTarget"
    )
    EvaluationCriterionLearningTarget = apps.get_model(
        "learning_analytics", "EvaluationCriterionLearningTarget"
    )
    LearningTargetBackfillIssue = apps.get_model(
        "learning_analytics", "LearningTargetBackfillIssue"
    )
    alias = schema_editor.connection.alias

    def issue(
        *,
        plan_version_id=None,
        standard_version_id=None,
        item_kind,
        source_code="",
        reason,
        detail=None,
    ):
        LearningTargetBackfillIssue.objects.using(alias).create(
            plan_version_id=plan_version_id,
            standard_version_id=standard_version_id,
            item_kind=item_kind,
            source_code=str(source_code or "")[:80],
            reason=reason,
            detail=detail or {},
        )

    plan_versions = EvaluationPlanVersion.objects.using(alias).order_by(
        "published_at", "id"
    )
    for plan_version in plan_versions.iterator():
        if not plan_version.course_id:
            issue(
                plan_version_id=plan_version.id,
                item_kind="evaluation_plan_version",
                reason="course_scope_missing",
                detail={
                    "message": "历史方案版本未绑定具体课程，未生成正式学习目标身份。"
                },
            )
            continue

        raw_goals = plan_version.learning_goals
        if not isinstance(raw_goals, list):
            issue(
                plan_version_id=plan_version.id,
                item_kind="learning_target",
                reason="goals_not_list",
                detail={"message": "历史学习目标快照不是列表，已跳过。"},
            )
            continue

        code_counts = {}
        for row in raw_goals:
            if isinstance(row, dict):
                code = str(row.get("code") or "").strip()
                code_counts[code] = code_counts.get(code, 0) + 1

        references = list(
            EvaluationPlanVersionCurriculumReference.objects.using(alias)
            .filter(plan_version_id=plan_version.id)
            .order_by("node_type", "node_code", "node_id", "id")
        )
        references_by_node = {reference.node_id: reference for reference in references}
        target_versions_by_code = {}

        for goal_index, raw_goal in enumerate(raw_goals):
            if not isinstance(raw_goal, dict):
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="learning_target",
                    reason="goal_not_object",
                    detail={"goal_index": goal_index},
                )
                continue
            code = str(raw_goal.get("code") or "").strip()
            if not TARGET_CODE_PATTERN.fullmatch(code):
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="learning_target",
                    source_code=code,
                    reason="invalid_goal_code",
                    detail={"goal_index": goal_index},
                )
                continue
            if code_counts.get(code) != 1:
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="learning_target",
                    source_code=code,
                    reason="duplicate_goal_code",
                    detail={"goal_index": goal_index, "count": code_counts.get(code)},
                )
                continue
            title = str(raw_goal.get("title") or "").strip()
            description = str(raw_goal.get("description") or "").strip()
            if not title or len(description) < 8:
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="learning_target",
                    source_code=code,
                    reason="invalid_goal_content",
                    detail={"goal_index": goal_index},
                )
                continue

            reference_problem = False
            raw_node_ids = raw_goal.get("curriculum_node_ids")
            if not isinstance(raw_node_ids, list):
                node_ids = []
                reference_problem = True
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="learning_target",
                    source_code=code,
                    reason="curriculum_ids_not_list",
                    detail={"goal_index": goal_index},
                )
            else:
                try:
                    node_ids = [int(node_id) for node_id in raw_node_ids]
                except (TypeError, ValueError):
                    node_ids = []
                    reference_problem = True
                    issue(
                        plan_version_id=plan_version.id,
                        item_kind="learning_target",
                        source_code=code,
                        reason="invalid_curriculum_ids",
                        detail={"goal_index": goal_index},
                    )
            if len(node_ids) != len(set(node_ids)):
                reference_problem = True
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="learning_target",
                    source_code=code,
                    reason="duplicate_curriculum_ids",
                    detail={"goal_index": goal_index},
                )
            node_ids = list(dict.fromkeys(node_ids))
            missing_node_ids = sorted(set(node_ids) - set(references_by_node))
            if missing_node_ids:
                reference_problem = True
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="learning_target",
                    source_code=code,
                    reason="curriculum_reference_missing",
                    detail={"node_ids": missing_node_ids},
                )
            goal_references = sorted(
                (
                    references_by_node[node_id]
                    for node_id in node_ids
                    if node_id in references_by_node
                ),
                key=lambda row: (row.node_type, row.node_code, row.node_id, row.id),
            )
            covered_types = {reference.node_type for reference in goal_references}
            missing_types = sorted(REQUIRED_NODE_TYPES - covered_types)
            if missing_types:
                reference_problem = True
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="learning_target",
                    source_code=code,
                    reason="curriculum_chain_incomplete",
                    detail={"missing_node_types": missing_types},
                )

            target, _created = LearningTarget.objects.using(alias).get_or_create(
                school_id=plan_version.school_id,
                subject_id=plan_version.subject_id,
                course_id=plan_version.course_id,
                code=code,
                defaults={
                    "logical_key": uuid.uuid4(),
                    "created_by_id": plan_version.published_by_id,
                },
            )
            if _created:
                LearningTarget.objects.using(alias).filter(pk=target.pk).update(
                    created_at=plan_version.published_at
                )
            target_hash = _canonical_hash(
                {
                    "plan_version_hash": plan_version.content_hash,
                    "code": code,
                    "title": title,
                    "description": description,
                    "curriculum_references": [
                        {
                            "node_type": reference.node_type,
                            "node_code": reference.node_code,
                            "node_content_hash": reference.node_content_hash,
                            "curriculum_version_hash": reference.curriculum_version_hash,
                        }
                        for reference in goal_references
                    ],
                }
            )
            latest_version = (
                LearningTargetVersion.objects.using(alias)
                .filter(target_id=target.id)
                .order_by("-version_no")
                .first()
            )
            target_version = LearningTargetVersion.objects.using(alias).create(
                target_id=target.id,
                plan_version_id=plan_version.id,
                version_no=(latest_version.version_no + 1) if latest_version else 1,
                code=code,
                title=title,
                description=description,
                content_hash=target_hash,
                alignment_status=(
                    "legacy_incomplete" if reference_problem else "complete"
                ),
                published_by_id=plan_version.published_by_id,
            )
            LearningTargetVersion.objects.using(alias).filter(
                pk=target_version.pk
            ).update(published_at=plan_version.published_at)
            for sort_order, reference in enumerate(goal_references):
                LearningTargetCurriculumAlignment.objects.using(alias).create(
                    target_version_id=target_version.id,
                    plan_reference_id=reference.id,
                    sort_order=sort_order,
                )
            target_versions_by_code[code] = target_version

        def backfill_relation_rows(
            *, raw_rows, item_kind, relation_model, code_field
        ):
            if not isinstance(raw_rows, list):
                issue(
                    plan_version_id=plan_version.id,
                    item_kind=item_kind,
                    reason="relations_not_list",
                )
                return
            if not raw_rows:
                issue(
                    plan_version_id=plan_version.id,
                    item_kind=item_kind,
                    reason="relations_empty",
                )
                return
            relation_code_counts = {}
            for relation_row in raw_rows:
                if isinstance(relation_row, dict):
                    relation_code = str(relation_row.get("code") or "").strip()
                    relation_code_counts[relation_code] = (
                        relation_code_counts.get(relation_code, 0) + 1
                    )
            for relation_index, relation_row in enumerate(raw_rows):
                if not isinstance(relation_row, dict):
                    issue(
                        plan_version_id=plan_version.id,
                        item_kind=item_kind,
                        reason="relation_not_object",
                        detail={"relation_index": relation_index},
                    )
                    continue
                relation_code = str(relation_row.get("code") or "").strip()
                if (
                    not TARGET_CODE_PATTERN.fullmatch(relation_code)
                    or relation_code_counts.get(relation_code) != 1
                ):
                    issue(
                        plan_version_id=plan_version.id,
                        item_kind=item_kind,
                        source_code=relation_code,
                        reason=(
                            "duplicate_relation_code"
                            if relation_code_counts.get(relation_code, 0) > 1
                            else "invalid_relation_code"
                        ),
                        detail={"relation_index": relation_index},
                    )
                    continue
                goal_codes = relation_row.get("goal_codes")
                if not isinstance(goal_codes, list) or not goal_codes or any(
                    not isinstance(goal_code, str) or not goal_code.strip()
                    for goal_code in goal_codes
                ):
                    issue(
                        plan_version_id=plan_version.id,
                        item_kind=item_kind,
                        source_code=relation_code,
                        reason="invalid_relation_goal_codes",
                    )
                    continue
                normalized_goal_codes = [goal_code.strip() for goal_code in goal_codes]
                if len(normalized_goal_codes) != len(set(normalized_goal_codes)):
                    issue(
                        plan_version_id=plan_version.id,
                        item_kind=item_kind,
                        source_code=relation_code,
                        reason="duplicate_relation_goal_code",
                    )
                    continue
                for sort_order, goal_code in enumerate(normalized_goal_codes):
                    target_version = target_versions_by_code.get(goal_code)
                    if target_version is None:
                        issue(
                            plan_version_id=plan_version.id,
                            item_kind=item_kind,
                            source_code=relation_code,
                            reason="relation_target_not_resolved",
                            detail={"learning_target_code": goal_code},
                        )
                        continue
                    create_values = {
                        "plan_version_id": plan_version.id,
                        "target_version_id": target_version.id,
                        "sort_order": sort_order,
                        code_field: relation_code,
                    }
                    relation_model.objects.using(alias).create(**create_values)

        backfill_relation_rows(
            raw_rows=plan_version.evaluation_basis,
            item_kind="evaluation_basis",
            relation_model=EvaluationBasisLearningTarget,
            code_field="basis_code",
        )
        backfill_relation_rows(
            raw_rows=plan_version.learning_activities,
            item_kind="learning_activity",
            relation_model=LearningActivityLearningTarget,
            code_field="activity_code",
        )

        raw_tasks = plan_version.evaluation_tasks
        if not isinstance(raw_tasks, list):
            issue(
                plan_version_id=plan_version.id,
                item_kind="evaluation_task",
                reason="tasks_not_list",
            )
            continue
        if not raw_tasks:
            issue(
                plan_version_id=plan_version.id,
                item_kind="evaluation_task",
                reason="tasks_empty",
            )
            continue
        task_code_counts = {}
        for task in raw_tasks:
            if isinstance(task, dict):
                task_code = str(task.get("code") or "").strip()
                task_code_counts[task_code] = task_code_counts.get(task_code, 0) + 1
        for task_index, task in enumerate(raw_tasks):
            if not isinstance(task, dict):
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="evaluation_task",
                    reason="task_not_object",
                    detail={"task_index": task_index},
                )
                continue
            task_code = str(task.get("code") or "").strip()
            if (
                not TARGET_CODE_PATTERN.fullmatch(task_code)
                or task_code_counts.get(task_code) != 1
            ):
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="evaluation_task",
                    source_code=task_code,
                    reason=(
                        "duplicate_task_code"
                        if task_code_counts.get(task_code, 0) > 1
                        else "invalid_task_code"
                    ),
                    detail={"task_index": task_index},
                )
                continue
            goal_codes = task.get("goal_codes")
            if not isinstance(goal_codes, list) or not goal_codes or any(
                not isinstance(goal_code, str) or not goal_code.strip()
                for goal_code in goal_codes
            ):
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="evaluation_task",
                    source_code=task_code,
                    reason="invalid_task_goal_codes",
                )
                continue
            normalized_goal_codes = [goal_code.strip() for goal_code in goal_codes]
            if len(normalized_goal_codes) != len(set(normalized_goal_codes)):
                issue(
                    plan_version_id=plan_version.id,
                    item_kind="evaluation_task",
                    source_code=task_code,
                    reason="duplicate_task_goal_code",
                )
                continue
            for sort_order, goal_code in enumerate(normalized_goal_codes):
                target_version = target_versions_by_code.get(goal_code)
                if target_version is None:
                    issue(
                        plan_version_id=plan_version.id,
                        item_kind="evaluation_task",
                        source_code=task_code,
                        reason="task_target_not_resolved",
                        detail={"learning_target_code": goal_code},
                    )
                    continue
                EvaluationTaskLearningTarget.objects.using(alias).get_or_create(
                    plan_version_id=plan_version.id,
                    task_code=task_code,
                    target_version_id=target_version.id,
                    defaults={"sort_order": sort_order},
                )

    standard_versions = EvaluationStandardVersion.objects.using(alias).order_by("id")
    for standard_version in standard_versions.iterator():
        plan_targets = {
            target_version.code: target_version
            for target_version in LearningTargetVersion.objects.using(alias).filter(
                plan_version_id=standard_version.plan_version_id
            )
        }
        for criterion in standard_version.criteria.all().order_by("sort_order", "id"):
            goal_codes = criterion.learning_goal_codes
            if not isinstance(goal_codes, list) or any(
                not isinstance(goal_code, str) or not goal_code.strip()
                for goal_code in goal_codes
            ):
                issue(
                    plan_version_id=standard_version.plan_version_id,
                    standard_version_id=standard_version.id,
                    item_kind="evaluation_criterion",
                    source_code=criterion.code,
                    reason="invalid_criterion_goal_codes",
                )
                continue
            seen_codes = set()
            for sort_order, raw_code in enumerate(goal_codes):
                goal_code = raw_code.strip()
                if goal_code in seen_codes:
                    issue(
                        plan_version_id=standard_version.plan_version_id,
                        standard_version_id=standard_version.id,
                        item_kind="evaluation_criterion",
                        source_code=criterion.code,
                        reason="duplicate_criterion_goal_code",
                        detail={"learning_target_code": goal_code},
                    )
                    continue
                seen_codes.add(goal_code)
                target_version = plan_targets.get(goal_code)
                if target_version is None:
                    issue(
                        plan_version_id=standard_version.plan_version_id,
                        standard_version_id=standard_version.id,
                        item_kind="evaluation_criterion",
                        source_code=criterion.code,
                        reason="criterion_target_not_resolved",
                        detail={"learning_target_code": goal_code},
                    )
                    continue
                EvaluationCriterionLearningTarget.objects.using(alias).create(
                    criterion_id=criterion.id,
                    target_version_id=target_version.id,
                    sort_order=sort_order,
                )


def reverse_learning_target_backfill(apps, schema_editor):
    alias = schema_editor.connection.alias
    for model_name in (
        "EvaluationCriterionLearningTarget",
        "EvaluationTaskLearningTarget",
        "LearningActivityLearningTarget",
        "EvaluationBasisLearningTarget",
        "LearningTargetCurriculumAlignment",
        "LearningTargetBackfillIssue",
        "LearningTargetVersion",
        "LearningTarget",
    ):
        apps.get_model("learning_analytics", model_name).objects.using(alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0029_alter_classroomgroupcollaboration_storage_quota_mb"),
        (
            "curriculum_standards",
            "0004_curriculumretrievalindex_curriculumretrievalchunk_and_more",
        ),
        (
            "learning_analytics",
            "0033_evaluationcriterionversion_evaluation_task_codes_and_more",
        ),
        ("school", "0009_school_is_synthetic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logical_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="学习目标代码必须以字母开头，只能包含字母、数字、下划线或连字符。",
                                regex=TARGET_CODE_PATTERN,
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_targets",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_learning_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_targets",
                        to="school.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_targets",
                        to="courses.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["school_id", "subject_id", "course_id", "code"],
            },
        ),
        migrations.CreateModel(
            name="LearningTargetBackfillIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_kind", models.CharField(max_length=40)),
                ("source_code", models.CharField(blank=True, max_length=80)),
                ("reason", models.CharField(max_length=80)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_target_backfill_issues",
                        to="learning_analytics.evaluationplanversion",
                    ),
                ),
                (
                    "standard_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_target_backfill_issues",
                        to="learning_analytics.evaluationstandardversion",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="LearningTargetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_no", models.PositiveIntegerField()),
                (
                    "code",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="学习目标代码必须以字母开头，只能包含字母、数字、下划线或连字符。",
                                regex=TARGET_CODE_PATTERN,
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                (
                    "alignment_status",
                    models.CharField(
                        choices=[
                            ("complete", "课标依据完整"),
                            ("legacy_incomplete", "历史课标依据不完整"),
                        ],
                        default="complete",
                        max_length=24,
                    ),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_target_versions",
                        to="learning_analytics.evaluationplanversion",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_learning_target_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="learning_analytics.learningtarget",
                    ),
                ),
            ],
            options={"ordering": ["target_id", "version_no", "id"]},
        ),
        migrations.CreateModel(
            name="LearningTargetCurriculumAlignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_target_alignments",
                        to="curriculum_standards.evaluationplanversioncurriculumreference",
                    ),
                ),
                (
                    "target_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_alignments",
                        to="learning_analytics.learningtargetversion",
                    ),
                ),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="EvaluationBasisLearningTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basis_code",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="代码必须以字母开头，只能包含字母、数字、下划线或连字符。",
                                regex=TARGET_CODE_PATTERN,
                            )
                        ],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basis_learning_target_links",
                        to="learning_analytics.evaluationplanversion",
                    ),
                ),
                (
                    "target_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_basis_links",
                        to="learning_analytics.learningtargetversion",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "plan_version_id",
                    "basis_code",
                    "sort_order",
                    "id",
                ]
            },
        ),
        migrations.CreateModel(
            name="LearningActivityLearningTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_code",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="代码必须以字母开头，只能包含字母、数字、下划线或连字符。",
                                regex=TARGET_CODE_PATTERN,
                            )
                        ],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_learning_target_links",
                        to="learning_analytics.evaluationplanversion",
                    ),
                ),
                (
                    "target_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_activity_links",
                        to="learning_analytics.learningtargetversion",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "plan_version_id",
                    "activity_code",
                    "sort_order",
                    "id",
                ]
            },
        ),
        migrations.CreateModel(
            name="EvaluationTaskLearningTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_code",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="代码必须以字母开头，只能包含字母、数字、下划线或连字符。",
                                regex=TARGET_CODE_PATTERN,
                            )
                        ],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_learning_target_links",
                        to="learning_analytics.evaluationplanversion",
                    ),
                ),
                (
                    "target_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_task_links",
                        to="learning_analytics.learningtargetversion",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "plan_version_id",
                    "task_code",
                    "sort_order",
                    "id",
                ]
            },
        ),
        migrations.CreateModel(
            name="EvaluationCriterionLearningTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_target_links",
                        to="learning_analytics.evaluationcriterionversion",
                    ),
                ),
                (
                    "target_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_criterion_links",
                        to="learning_analytics.learningtargetversion",
                    ),
                ),
            ],
            options={"ordering": ["criterion_id", "sort_order", "id"]},
        ),
        migrations.AddIndex(
            model_name="learningtarget",
            index=models.Index(
                fields=["school", "subject", "course", "code"],
                name="la_target_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningtarget",
            constraint=models.UniqueConstraint(
                fields=("school", "subject", "course", "code"),
                name="uniq_learning_target_scope_code",
            ),
        ),
        migrations.AddIndex(
            model_name="learningtargetbackfillissue",
            index=models.Index(
                fields=["item_kind", "reason", "created_at"],
                name="la_target_issue_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningtargetversion",
            index=models.Index(
                fields=["plan_version", "alignment_status"],
                name="la_target_plan_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningtargetversion",
            index=models.Index(
                fields=["target", "published_at"],
                name="la_target_version_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningtargetversion",
            constraint=models.UniqueConstraint(
                fields=("target", "version_no"),
                name="uniq_learning_target_version_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningtargetversion",
            constraint=models.UniqueConstraint(
                fields=("target", "plan_version"),
                name="uniq_target_plan_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningtargetversion",
            constraint=models.UniqueConstraint(
                fields=("plan_version", "code"),
                name="uniq_plan_version_target_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningtargetcurriculumalignment",
            constraint=models.UniqueConstraint(
                fields=("target_version", "plan_reference"),
                name="uniq_target_curriculum_alignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningtargetcurriculumalignment",
            constraint=models.UniqueConstraint(
                fields=("target_version", "sort_order"),
                name="uniq_target_curriculum_order",
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationbasislearningtarget",
            index=models.Index(
                fields=["plan_version", "basis_code"], name="la_basis_target_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationbasislearningtarget",
            constraint=models.UniqueConstraint(
                fields=("plan_version", "basis_code", "target_version"),
                name="uniq_basis_learning_target",
            ),
        ),
        migrations.AddIndex(
            model_name="learningactivitylearningtarget",
            index=models.Index(
                fields=["plan_version", "activity_code"],
                name="la_activity_target_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningactivitylearningtarget",
            constraint=models.UniqueConstraint(
                fields=("plan_version", "activity_code", "target_version"),
                name="uniq_activity_learning_target",
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationtasklearningtarget",
            index=models.Index(
                fields=["plan_version", "task_code"], name="la_task_target_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationtasklearningtarget",
            constraint=models.UniqueConstraint(
                fields=("plan_version", "task_code", "target_version"),
                name="uniq_task_learning_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationcriterionlearningtarget",
            constraint=models.UniqueConstraint(
                fields=("criterion", "target_version"),
                name="uniq_criterion_learning_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationcriterionlearningtarget",
            constraint=models.UniqueConstraint(
                fields=("criterion", "sort_order"),
                name="uniq_criterion_target_order",
            ),
        ),
        migrations.RunPython(
            backfill_learning_target_versions,
            reverse_learning_target_backfill,
        ),
    ]
