# Generated by Django 5.2.15 on 2026-07-22 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_alter_classroomgroupcollaboration_storage_quota_mb"),
        (
            "curriculum_standards",
            "0004_curriculumretrievalindex_curriculumretrievalchunk_and_more",
        ),
        ("learning_analytics", "0035_p2_teacher_review_contract"),
        ("school", "0009_school_is_synthetic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIEvaluationDraftSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("curriculum_version_content_hash", models.CharField(max_length=64)),
                ("curriculum_pdf_sha256", models.CharField(max_length=64)),
                ("school_stage", models.CharField(max_length=16)),
                ("grade_or_stage", models.CharField(max_length=64)),
                ("unit_title", models.CharField(max_length=160)),
                ("course_content", models.TextField()),
                ("evaluation_purpose", models.TextField()),
                ("teacher_mode_note", models.CharField(blank=True, max_length=500)),
                ("retrieval_query", models.TextField()),
                ("retrieval_snapshot", models.JSONField(blank=True, default=list)),
                ("retrieval_snapshot_hash", models.CharField(blank=True, max_length=64)),
                ("suggested_modes", models.JSONField(blank=True, default=list)),
                ("confirmed_modes", models.JSONField(blank=True, default=list)),
                ("plan_draft", models.JSONField(blank=True, default=dict)),
                ("standard_draft", models.JSONField(blank=True, default=dict)),
                ("automatic_check_result", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "待检索课程标准"),
                            ("retrieved", "已检索课程标准"),
                            ("mode_suggestion_queued", "评价方式建议排队中"),
                            ("mode_suggestion_running", "正在形成评价方式建议"),
                            ("modes_suggested", "评价方式待教师确认"),
                            ("modes_confirmed", "教师已确认评价方式"),
                            ("draft_queued", "评价初稿排队中"),
                            ("draft_running", "正在形成评价初稿"),
                            ("draft_generated", "评价初稿待教师审阅"),
                            ("saved", "已保存为评价方案草稿"),
                            ("failed", "后台任务失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="created",
                        max_length=32,
                    ),
                ),
                (
                    "active_task_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "无"),
                            ("suggest_modes", "建议评价方式"),
                            ("generate_draft", "生成评价初稿"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("dispatch_count", models.PositiveIntegerField(default=0)),
                ("dispatch_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("last_error_message", models.CharField(blank=True, max_length=1000)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("save_request_hash", models.CharField(blank=True, max_length=64)),
                ("saved_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_evaluation_draft_sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "curriculum_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_evaluation_draft_sessions",
                        to="curriculum_standards.curriculumstandardversion",
                    ),
                ),
                (
                    "linked_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_draft_sessions",
                        to="learning_analytics.evaluationplan",
                    ),
                ),
                (
                    "linked_standard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_draft_sessions",
                        to="learning_analytics.evaluationstandard",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_evaluation_draft_sessions",
                        to="school.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_evaluation_draft_sessions",
                        to="courses.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_evaluation_draft_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.CreateModel(
            name="AIEvaluationGenerationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("mode_suggestion", "评价方式建议"),
                            ("evaluation_draft", "评价内容初稿"),
                        ],
                        max_length=24,
                    ),
                ),
                ("attempt_no", models.PositiveIntegerField()),
                ("provider", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=128)),
                ("system_prompt", models.TextField()),
                ("user_prompt", models.TextField()),
                ("prompt_hash", models.CharField(max_length=64)),
                ("generation_config", models.JSONField(default=dict)),
                ("retrieval_snapshot", models.JSONField(default=list)),
                ("raw_response_text", models.TextField(blank=True)),
                ("raw_result", models.JSONField(blank=True, default=dict)),
                ("parsed_result", models.JSONField(blank=True, default=dict)),
                ("validation_result", models.JSONField(blank=True, default=dict)),
                ("result_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "成功"), ("failed", "失败")],
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=1000)),
                ("celery_task_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_records",
                        to="learning_analytics.aievaluationdraftsession",
                    ),
                ),
            ],
            options={"ordering": ["session_id", "stage", "attempt_no", "id"]},
        ),
        migrations.CreateModel(
            name="AIEvaluationTeacherDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=32)),
                ("item_type", models.CharField(max_length=48)),
                ("item_key", models.CharField(max_length=128)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("accepted", "采纳"),
                            ("edited", "修改后采纳"),
                            ("rejected", "不采纳"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ai_value", models.JSONField(blank=True, null=True)),
                ("teacher_value", models.JSONField(blank=True, null=True)),
                ("diff", models.JSONField(blank=True, default=dict)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher_decisions",
                        to="learning_analytics.aievaluationgenerationrecord",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher_decisions",
                        to="learning_analytics.aievaluationdraftsession",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_evaluation_teacher_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "session_id",
                    "stage",
                    "item_type",
                    "item_key",
                    "sequence",
                    "id",
                ]
            },
        ),
        migrations.AddIndex(
            model_name="aievaluationdraftsession",
            index=models.Index(
                fields=["teacher", "status", "updated_at"],
                name="learning_an_teacher_65adf2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aievaluationdraftsession",
            index=models.Index(
                fields=["school", "course", "updated_at"],
                name="learning_an_school__754206_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aievaluationdraftsession",
            constraint=models.UniqueConstraint(
                fields=("teacher", "idempotency_key"),
                name="uniq_ai_eval_teacher_idempotency",
            ),
        ),
        migrations.AddIndex(
            model_name="aievaluationgenerationrecord",
            index=models.Index(
                fields=["session", "stage", "created_at"],
                name="learning_an_session_c88b75_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aievaluationgenerationrecord",
            constraint=models.UniqueConstraint(
                fields=("session", "stage", "attempt_no"),
                name="uniq_ai_eval_generation_attempt",
            ),
        ),
        migrations.AddIndex(
            model_name="aievaluationteacherdecision",
            index=models.Index(
                fields=["session", "stage", "created_at"],
                name="learning_an_session_82f04b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aievaluationteacherdecision",
            constraint=models.UniqueConstraint(
                fields=("session", "stage", "item_type", "item_key", "sequence"),
                name="uniq_ai_eval_teacher_decision",
            ),
        ),
    ]
