# Generated by Django 5.2.15 on 2026-07-01 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('candidate', '候选'), ('champion', '生产'), ('archived', '归档'), ('failed', '失败')], default='candidate', max_length=16)),
                ('algorithm', models.CharField(default='rules', max_length=64)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('feature_schema', models.JSONField(blank=True, default=dict)),
                ('artifact_uri', models.CharField(blank=True, max_length=512)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_versions', to='school.classgroup')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败')], default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='school.classgroup')),
                ('output_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiops.modelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['class_group', 'status'], name='aiops_model_class_g_7866fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(fields=('class_group', 'name', 'version'), name='uniq_class_model_version'),
        ),
    ]
