# Generated by Django 5.2.15 on 2026-07-04 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek')], default='deepseek', max_length=32)),
                ('base_url', models.URLField(default='https://api.deepseek.com', max_length=255)),
                ('model', models.CharField(default='deepseek-v4-flash', max_length=64)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('api_key_hint', models.CharField(blank=True, max_length=16)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacher_id', 'provider'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'provider'), name='uniq_teacher_ai_provider')],
            },
        ),
    ]
