# Generated by Django 5.2.15 on 2026-07-01 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('school', '0002_school_address_school_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='school.school'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('school_admin', '学校管理员'), ('admin', '管理员'), ('teacher', '教师'), ('student', '学生')], default='student', max_length=20),
        ),
    ]
