# Generated by Django 5.2.15 on 2026-07-02 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_subject_course_subject_and_more'),
        ('school', '0008_simplify_teaching_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('draft', '未开始'), ('running', '进行中'), ('finished', '已结束')], default='draft', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_sessions', to='school.classgroup')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_sessions', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_sessions', to='courses.lesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_sessions', to='school.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('sign_in', '签到'), ('quick_answer', '抢答'), ('question', '即时题'), ('discussion', '讨论'), ('task', '课堂任务'), ('confusion', '未懂反馈'), ('broadcast', '课堂广播')], max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', '未开启'), ('open', '进行中'), ('closed', '已关闭')], default='draft', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.classroomsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_classes', to='school.classgroup')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classes', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_id', 'class_group__grade', 'class_group__name'],
            },
        ),
        migrations.AddIndex(
            model_name='classroomsession',
            index=models.Index(fields=['school', 'teacher', 'status', 'created_at'], name='courses_cla_school__3eca3c_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomsession',
            index=models.Index(fields=['class_group', 'status', 'created_at'], name='courses_cla_class_g_6f2715_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomactivity',
            index=models.Index(fields=['session', 'status', 'created_at'], name='courses_cla_session_626d56_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomactivity',
            index=models.Index(fields=['activity_type', 'status'], name='courses_cla_activit_64f9f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(fields=('course', 'class_group'), name='uniq_course_class_group'),
        ),
    ]
