# Generated by Django 5.2.15 on 2026-07-04 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_classroomsession_classroomactivity_courseclass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('step_type', models.CharField(choices=[('intro', '导入'), ('resource', '资源学习'), ('question', '课堂题'), ('task', '任务实践'), ('upload', '作品上传'), ('discussion', '讨论反馈'), ('evaluation', '展示评价'), ('reflection', '小结反思'), ('ai_worksheet', 'AI 学习单'), ('document', '协作文档')], default='resource', max_length=32)),
                ('student_instruction', models.TextField(blank=True)),
                ('teacher_note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('target_layer', models.CharField(choices=[('all', '全体'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('A/B', 'A/B'), ('B/C', 'B/C'), ('A/B/C', 'A/B/C')], default='all', max_length=16)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '已配置')], default='draft', max_length=16)),
                ('resource_items', models.JSONField(blank=True, default=list)),
                ('activity_items', models.JSONField(blank=True, default=list)),
                ('ai_prompt', models.TextField(blank=True)),
                ('collect_student_log', models.BooleanField(default=True)),
                ('collect_class_log', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_steps', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.lesson')),
            ],
            options={
                'ordering': ['lesson_id', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['lesson', 'sort_order', 'id'], name='courses_les_lesson__fe7e77_idx'), models.Index(fields=['step_type', 'status'], name='courses_les_step_ty_b801f3_idx')],
            },
        ),
    ]
