# Generated by Django 5.2.15 on 2026-07-10 06:51

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_classroomactivity_metadata'),
        ('school', '0008_simplify_teaching_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomGroupCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('group_size', models.PositiveSmallIntegerField(default=4)),
                ('grouping_strategy', models.CharField(choices=[('balanced_layer', '按层级优先分组'), ('same_layer', '同层级分组'), ('random', '随机分组'), ('manual', '手动分组'), ('ai_layer', 'AI 分层分组')], default='balanced_layer', max_length=32)),
                ('document_type', models.CharField(choices=[('docx', 'Word'), ('pptx', 'PPT'), ('xlsx', 'Excel')], default='docx', max_length=8)),
                ('storage_quota_mb', models.PositiveIntegerField(default=100)),
                ('allow_student_upload', models.BooleanField(default=True)),
                ('allow_onlyoffice_edit', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', '未开启'), ('open', '进行中'), ('closed', '已关闭')], default='draft', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_collaborations', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_collaboration', to='courses.classroomsession')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('layer_hint', models.CharField(blank=True, max_length=32)),
                ('collaboration_document', models.FileField(blank=True, upload_to=courses.models.classroom_group_document_upload_path)),
                ('document_original_name', models.CharField(blank=True, max_length=128)),
                ('document_file_ext', models.CharField(blank=True, max_length=8)),
                ('document_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_classroom_groups', to=settings.AUTH_USER_MODEL)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.classroomgroupcollaboration')),
            ],
            options={
                'ordering': ['collaboration_id', 'group_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomGroupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=courses.models.classroom_group_file_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_ext', models.CharField(blank=True, max_length=16)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.classroomgroup')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_classroom_group_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '组长'), ('member', '成员')], default='member', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='courses.classroomgroupcollaboration')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='courses.classroomgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_group_memberships', to='school.studentprofile')),
            ],
            options={
                'ordering': ['group__group_no', 'role', 'student__display_name', 'student__username'],
            },
        ),
        migrations.AddIndex(
            model_name='classroomgroupcollaboration',
            index=models.Index(fields=['status', 'updated_at'], name='courses_cla_status_cb531d_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomgroupcollaboration',
            index=models.Index(fields=['grouping_strategy', 'updated_at'], name='courses_cla_groupin_9175e4_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomgroup',
            index=models.Index(fields=['collaboration', 'group_no'], name='courses_cla_collabo_5e0e0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomgroup',
            constraint=models.UniqueConstraint(fields=('collaboration', 'group_no'), name='uniq_classroom_group_no_per_collaboration'),
        ),
        migrations.AddIndex(
            model_name='classroomgroupfile',
            index=models.Index(fields=['group', 'created_at'], name='courses_cla_group_i_174056_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomgroupfile',
            index=models.Index(fields=['uploader', 'created_at'], name='courses_cla_uploade_43698a_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomgroupmember',
            index=models.Index(fields=['collaboration', 'student'], name='courses_cla_collabo_2b8cad_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomgroupmember',
            index=models.Index(fields=['group', 'role'], name='courses_cla_group_i_45b431_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomgroupmember',
            constraint=models.UniqueConstraint(fields=('collaboration', 'student'), name='uniq_student_per_group_collaboration'),
        ),
        migrations.AddConstraint(
            model_name='classroomgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'student'), name='uniq_student_per_classroom_group'),
        ),
    ]
