# Generated by Django 5.2.15 on 2026-07-10 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_classroomgroupcollaboration_classroomgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomEvaluationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_self', models.BooleanField(default=False)),
                ('enable_peer', models.BooleanField(default=False)),
                ('enable_teacher', models.BooleanField(default=False)),
                ('self_criteria', models.JSONField(blank=True, default=list)),
                ('peer_criteria', models.JSONField(blank=True, default=list)),
                ('teacher_criteria', models.JSONField(blank=True, default=list)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classroom_evaluation_configs', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_config', to='courses.classroomsession')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['enable_self', 'enable_peer', 'enable_teacher'], name='courses_cla_enable__0c071b_idx'), models.Index(fields=['updated_at'], name='courses_cla_updated_26b0d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassroomEvaluationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('self', '自评'), ('peer', '互评'), ('teacher', '师评')], max_length=16)),
                ('ratings', models.JSONField(default=dict)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_submissions', to='courses.classroomgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_submissions', to='courses.classroomsession')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_evaluations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['session', 'evaluation_type', 'updated_at'], name='courses_cla_session_18ddc8_idx'), models.Index(fields=['target', 'updated_at'], name='courses_cla_target__5b51e7_idx'), models.Index(fields=['group', 'evaluation_type'], name='courses_cla_group_i_63f88f_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'evaluation_type', 'evaluator', 'target'), name='uniq_classroom_evaluation_submission')],
            },
        ),
    ]
