# Generated by Django 5.2.15 on 2026-07-11 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_classroomsession_evaluation_runtime'),
        ('school', '0008_simplify_teaching_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningWebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('schema', models.JSONField(default=dict)),
                ('generation_prompt', models.TextField(blank=True)),
                ('revision_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '可使用')], default='ready', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_web_pages', to='courses.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_web_pages', to='courses.lesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_web_pages', to='school.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='learning_web_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LearningWebPageResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_version', models.PositiveIntegerField(default=1)),
                ('form_id', models.CharField(max_length=64)),
                ('answers', models.JSONField(default=dict)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_web_page_responses', to='school.classgroup')),
                ('classroom_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_web_page_responses', to='courses.classroomsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_web_page_responses', to='courses.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_web_page_responses', to='courses.lesson')),
                ('lesson_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_web_page_responses', to='courses.lessonstep')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='courses.learningwebpage')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_web_page_responses', to='school.school')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='learning_web_page_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LearningWebPageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('prompt', models.TextField(blank=True)),
                ('schema', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learning_web_page_versions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='courses.learningwebpage')),
            ],
            options={
                'ordering': ['-version_no', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='learningwebpage',
            index=models.Index(fields=['lesson', 'is_active', 'updated_at'], name='courses_lea_lesson__8e0cba_idx'),
        ),
        migrations.AddIndex(
            model_name='learningwebpage',
            index=models.Index(fields=['teacher', 'updated_at'], name='courses_lea_teacher_27be6d_idx'),
        ),
        migrations.AddIndex(
            model_name='learningwebpageresponse',
            index=models.Index(fields=['page', 'form_id', 'submitted_at'], name='courses_lea_page_id_3fef9c_idx'),
        ),
        migrations.AddIndex(
            model_name='learningwebpageresponse',
            index=models.Index(fields=['class_group', 'submitted_at'], name='courses_lea_class_g_eeebc5_idx'),
        ),
        migrations.AddIndex(
            model_name='learningwebpageresponse',
            index=models.Index(fields=['student', 'submitted_at'], name='courses_lea_student_7ed93d_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningwebpageresponse',
            constraint=models.UniqueConstraint(fields=('page', 'student', 'form_id', 'attempt_no'), name='uniq_learning_web_page_form_attempt'),
        ),
        migrations.AddConstraint(
            model_name='learningwebpageversion',
            constraint=models.UniqueConstraint(fields=('page', 'version_no'), name='uniq_learning_web_page_version'),
        ),
    ]
