# Generated by Django 5.2.15 on 2026-07-17 13:19

import courses.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def assign_resource_public_ids(apps, schema_editor):
    Resource = apps.get_model('courses', 'Resource')
    for resource in Resource.objects.all().only('id', 'public_id').iterator():
        resource.public_id = uuid.uuid4()
        resource.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_learningwebpage_learningwebpageresponse_and_more'),
        ('school', '0008_simplify_teaching_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=courses.models.resource_extra_file_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_ext', models.CharField(blank=True, max_length=16)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('role', models.CharField(choices=[('supplement', '补充附件'), ('process', '项目过程材料')], default='supplement', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='award_level',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('courseware', '课件素材'), ('extracurricular', '课外拓展'), ('competition', '竞赛资源'), ('project', '学生项目'), ('reference', '参考资料'), ('toolkit', '工具素材'), ('other', '其他')], default='courseware', max_length=24),
        ),
        migrations.AddField(
            model_name='resource',
            name='competition_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='resource',
            name='competition_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='cover',
            field=models.ImageField(blank=True, upload_to='resource_covers/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='external_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='resource',
            name='grade_scope',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='resource',
            name='project_course',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='resource',
            name='project_members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resource',
            name='project_type',
            field=models.CharField(blank=True, choices=[('individual', '个人项目'), ('group', '小组项目')], max_length=16),
        ),
        migrations.AddField(
            model_name='resource',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(assign_resource_public_ids, migrations.RunPython.noop),
        migrations.AddField(
            model_name='resource',
            name='publish_status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已退回'), ('archived', '已归档')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='resource',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('file', '文件资源'), ('article', '图文内容'), ('link', '外部链接'), ('student_project', '学生项目')], default='file', max_length=24),
        ),
        migrations.AddField(
            model_name='resource',
            name='review_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resource',
            name='target_classes',
            field=models.ManyToManyField(blank=True, related_name='shared_resources', to='school.classgroup'),
        ),
        migrations.AddField(
            model_name='resource',
            name='visibility',
            field=models.CharField(choices=[('private', '仅自己'), ('classes', '指定班级'), ('school', '本校共享'), ('external', '跨校共享')], default='private', max_length=16),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['visibility', 'publish_status', 'updated_at'], name='courses_res_visibil_848d97_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type', 'category', 'updated_at'], name='courses_res_resourc_a216a8_idx'),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_files', to='courses.resource'),
        ),
        migrations.AddIndex(
            model_name='resourcefile',
            index=models.Index(fields=['resource', 'role', 'sort_order'], name='courses_res_resourc_2e7dca_idx'),
        ),
    ]
