# Generated by Django 5.2.15 on 2026-07-17 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_resourcefile_resource_award_level_resource_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
