# Generated by Django 5.2.15 on 2026-07-18 17:09

import hashlib
import uuid

import courses.models
from django.core.files.base import ContentFile
from django.db import migrations, models
import django.db.models.deletion


def backfill_group_file_identifiers(apps, schema_editor):
    GroupFile = apps.get_model("courses", "ClassroomGroupFile")
    for file in GroupFile.objects.filter(public_id__isnull=True).iterator():
        GroupFile.objects.filter(pk=file.pk).update(
            public_id=uuid.uuid4(),
            analytics_attempt_id=uuid.uuid4(),
        )


def backfill_group_document_versions(apps, schema_editor):
    Group = apps.get_model("courses", "ClassroomGroup")
    Version = apps.get_model("courses", "ClassroomGroupDocumentVersion")
    for group in Group.objects.exclude(collaboration_document="").iterator():
        try:
            with group.collaboration_document.storage.open(
                group.collaboration_document.name, "rb"
            ) as source:
                data = source.read()
        except (FileNotFoundError, OSError):
            continue
        if not data:
            continue
        version = Version(
            group_id=group.id,
            version_no=max(int(group.document_version or 1), 1),
            file_sha256=hashlib.sha256(data).hexdigest(),
            file_size=len(data),
            source="initial",
        )
        file_ext = group.document_file_ext or group.collaboration.document_type
        version.file.save(
            f"version_{version.version_no}.{file_ext}",
            ContentFile(data),
            save=False,
        )
        version.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0022_bind_historical_evaluation_sessions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomGroupDocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_no", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        upload_to=courses.models.classroom_group_document_version_upload_path
                    ),
                ),
                ("file_sha256", models.CharField(max_length=64)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("initial", "初始文档"),
                            ("onlyoffice_callback", "ONLYOFFICE 回调"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "callback_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("callback_key", models.CharField(blank=True, max_length=255)),
                ("verified_editor_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions",
                        to="courses.classroomgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["group_id", "version_no"],
                "indexes": [
                    models.Index(
                        fields=["group", "created_at"],
                        name="courses_cla_group_i_2cbbd0_idx",
                    ),
                    models.Index(
                        fields=["file_sha256"],
                        name="courses_cla_file_sh_634ad2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "version_no"),
                        name="uniq_classroom_group_document_version",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_group_document_versions, noop_reverse),
        migrations.AddField(
            model_name="classroomgroupfile",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="classroomgroupfile",
            name="analytics_attempt_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="classroomgroupfile",
            name="version_no",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_group_file_identifiers, noop_reverse),
        migrations.AlterField(
            model_name="classroomgroupfile",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="classroomgroupfile",
            name="analytics_attempt_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
