# Generated by Django 5.2.15 on 2026-07-19 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_add_evaluation_not_assessed'),
        ('learning_analytics', '0020_repair_evaluation_schema_hash'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomevaluationconfig',
            name='legacy_only',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='classroomevaluationconfigversion',
            name='legacy_only',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='classroomevaluationsubmission',
            name='legacy_compatible',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='classroomevaluationsubmission',
            name='standard_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning_analytics.classroomevaluationstandarduse'),
        ),
        migrations.AlterField(
            model_name='classroomevaluationsubmission',
            name='evaluation_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='courses.classroomevaluationconfigversion'),
        ),
        migrations.AddIndex(
            model_name='classroomevaluationsubmission',
            index=models.Index(fields=['standard_use', 'evaluation_type', 'updated_at'], name='courses_cla_standar_482d88_idx'),
        ),
    ]
