# Generated by Django 5.2.15 on 2026-07-20 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_classroomevaluationconfig_legacy_only_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classroomgroup',
            name='uniq_classroom_group_no_per_collaboration',
        ),
        migrations.RemoveConstraint(
            model_name='classroomgroupmember',
            name='uniq_student_per_group_collaboration',
        ),
        migrations.RemoveIndex(
            model_name='classroomgroup',
            name='courses_cla_collabo_5e0e0b_idx',
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroomgroup',
            name='plan_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classroomgroupcollaboration',
            name='active_plan_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classroomgroupcollaboration',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classroomgroupcollaboration',
            name='strategy_version',
            field=models.CharField(default='group-policy-v2', max_length=32),
        ),
        migrations.AddField(
            model_name='classroomgroupmember',
            name='plan_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='classroomgroupcollaboration',
            name='grouping_strategy',
            field=models.CharField(choices=[('balanced_layer', '按层级优先分组'), ('same_layer', '同层级分组'), ('random', '随机分组'), ('manual', '手动分组'), ('ai_layer', 'AI 分层分组')], default='random', max_length=32),
        ),
        migrations.AddIndex(
            model_name='classroomgroup',
            index=models.Index(fields=['collaboration', 'is_active', 'group_no'], name='courses_cla_collabo_70a5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomgroup',
            index=models.Index(fields=['collaboration', 'plan_version', 'group_no'], name='courses_cla_collabo_2b8098_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomgroup',
            constraint=models.UniqueConstraint(fields=('collaboration', 'plan_version', 'group_no'), name='uniq_classroom_group_no_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='classroomgroupmember',
            constraint=models.UniqueConstraint(fields=('collaboration', 'student', 'plan_version'), name='uniq_student_per_group_plan'),
        ),
    ]
