# Generated by Django 5.2.15 on 2026-07-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_remove_classroomgroup_uniq_classroom_group_no_per_collaboration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomgroupcollaboration',
            name='grouping_strategy',
            field=models.CharField(choices=[('balanced_layer', '按层级优先分组'), ('same_layer', '同层级分组'), ('random', '随机分组'), ('manual', '手动分组'), ('ai_layer', 'AI 分层分组'), ('stable_project', '项目稳定分组')], default='random', max_length=32),
        ),
        migrations.AlterField(
            model_name='classroomgroupmember',
            name='role',
            field=models.CharField(choices=[('leader', '组长'), ('member', '成员'), ('coordinator', '协调'), ('recorder', '记录'), ('resource', '资源'), ('presenter', '展示'), ('verifier', '核验')], default='member', max_length=16),
        ),
    ]
