# Generated by Django 5.2.15 on 2026-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_classroomgroupcollaboration_grouping_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomgroupcollaboration',
            name='storage_quota_mb',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
