# Generated by Django 5.2.15 on 2026-07-24

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_alter_classroomgroupcollaboration_storage_quota_mb"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceDocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_no", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        upload_to=courses.models.resource_document_version_upload_path
                    ),
                ),
                ("file_sha256", models.CharField(max_length=64)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("initial", "初始文件"),
                            ("onlyoffice_callback", "OnlyOffice 保存"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "callback_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("callback_key", models.CharField(blank=True, max_length=255)),
                ("verified_editor_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions",
                        to="courses.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["resource_id", "version_no"],
                "indexes": [
                    models.Index(
                        fields=["resource", "created_at"],
                        name="courses_res_resourc_692883_idx",
                    ),
                    models.Index(
                        fields=["file_sha256"],
                        name="courses_res_file_sh_ef04db_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "version_no"),
                        name="uniq_resource_document_version",
                    ),
                ],
            },
        ),
    ]
