# Generated by Django 5.2.15 on 2026-07-01 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_school_address_school_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=64, unique=True)),
                ('system_version', models.CharField(blank=True, max_length=32)),
                ('file', models.FileField(blank=True, upload_to='exports/')),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '处理中'), ('succeeded', '成功'), ('failed', '失败')], default='pending', max_length=16)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_export_batches', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_batches', to='school.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=64, unique=True)),
                ('source_school_code', models.CharField(blank=True, max_length=32)),
                ('source_system_version', models.CharField(blank=True, max_length=32)),
                ('package_file', models.FileField(upload_to='imports/')),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('validated', '已校验'), ('imported', '已导入'), ('failed', '失败')], default='uploaded', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True)),
                ('source_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='school.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='ops_auditlo_action_f4d18a_idx'), models.Index(fields=['school', 'created_at'], name='ops_auditlo_school__4c0034_idx')],
            },
        ),
    ]
