# Generated by Django 5.2.15 on 2026-07-01 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aiops', '0001_initial'),
        ('courses', '0001_initial'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', '登录'), ('page_view', '页面访问'), ('resource_view', '资源查看'), ('lesson_enter', '进入课时'), ('answer_submit', '提交答案'), ('task_submit', '提交任务'), ('project_submit', '提交项目'), ('chat_message', '聊天消息'), ('question_ask', '提问'), ('question_answer', '回答'), ('teacher_intervention', '教师干预')], max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.classgroup')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['class_group', 'occurred_at'], name='learning_le_class_g_7dac04_idx'), models.Index(fields=['actor', 'occurred_at'], name='learning_le_actor_i_5b4341_idx'), models.Index(fields=['event_type', 'occurred_at'], name='learning_le_event_t_381f97_idx')],
            },
        ),
        migrations.CreateModel(
            name='StratificationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_layer', models.CharField(max_length=1)),
                ('suggested_layer', models.CharField(max_length=1)),
                ('confidence', models.FloatField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '待教师确认'), ('accepted', '已采纳'), ('rejected', '已拒绝')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.classgroup')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiops.modelversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_layer_decisions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['class_group', 'status', 'created_at'], name='learning_st_class_g_c00e85_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.classgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['class_group', 'window_end'], name='learning_st_class_g_9aed44_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'window_start', 'window_end'), name='uniq_feature_snapshot_window')],
            },
        ),
    ]
