# Generated by Django 5.2.15 on 2026-07-02 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_subject_course_subject_and_more'),
        ('learning', '0001_initial'),
        ('school', '0008_simplify_teaching_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PretestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('literacy', '素养测试'), ('attitude', '学习态度问卷')], max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('introduction', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pretest_papers', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretest_papers', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pretest_papers', to='courses.subject')),
            ],
            options={
                'ordering': ['subject__name', 'kind', '-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PretestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField()),
                ('question_type', models.CharField(choices=[('single', '单选'), ('multiple', '多选'), ('scale', '量表'), ('text', '简答')], default='single', max_length=16)),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(default=0)),
                ('dimension', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.pretestpaper')),
            ],
            options={
                'ordering': ['paper_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PretestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('score', models.FloatField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning.pretestpaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretest_submissions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pretest_submissions', to='courses.subject')),
            ],
        ),
        migrations.AddIndex(
            model_name='pretestpaper',
            index=models.Index(fields=['school', 'subject', 'kind', 'status'], name='learning_pr_school__3cf112_idx'),
        ),
        migrations.AddConstraint(
            model_name='pretestpaper',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'kind', 'version'), name='uniq_pretest_paper_version_per_subject_kind'),
        ),
        migrations.AddIndex(
            model_name='pretestquestion',
            index=models.Index(fields=['paper', 'sort_order'], name='learning_pr_paper_i_4c0b58_idx'),
        ),
        migrations.AddIndex(
            model_name='pretestsubmission',
            index=models.Index(fields=['subject', 'submitted_at'], name='learning_pr_subject_e65789_idx'),
        ),
        migrations.AddIndex(
            model_name='pretestsubmission',
            index=models.Index(fields=['student', 'subject'], name='learning_pr_student_9bebe8_idx'),
        ),
        migrations.AddConstraint(
            model_name='pretestsubmission',
            constraint=models.UniqueConstraint(fields=('student', 'paper'), name='uniq_pretest_submission_per_paper'),
        ),
    ]
