# Generated by Django 5.2.15 on 2026-07-02 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_pretestpaper_pretestquestion_pretestsubmission_and_more'),
        ('school', '0008_simplify_teaching_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('study', '学习问题'), ('account', '账号问题'), ('resource', '资源问题'), ('suggestion', '建议反馈'), ('other', '其他')], default='study', max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待回复'), ('replied', '已回复'), ('closed', '已关闭')], default='pending', max_length=16)),
                ('reply_content', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_items', to='school.classgroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_feedback_items', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_feedback_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'teacher', 'status', 'created_at'], name='learning_fe_school__9a7cdf_idx'), models.Index(fields=['class_group', 'status', 'created_at'], name='learning_fe_class_g_bb9eb1_idx'), models.Index(fields=['student', 'created_at'], name='learning_fe_student_53af31_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=16)),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='school.school')),
                ('target_classes', models.ManyToManyField(blank=True, related_name='notices', to='school.classgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['school', 'teacher', 'status', 'created_at'], name='learning_no_school__1dffb3_idx'), models.Index(fields=['school', 'status', 'is_pinned'], name='learning_no_school__2cc06b_idx')],
            },
        ),
    ]
