# Generated by Django 5.2.15 on 2026-07-09 13:53

import django.db.models.deletion
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_classroomactivity_metadata'),
        ('learning', '0003_feedback_notice'),
        ('school', '0008_simplify_teaching_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWorkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=64)),
                ('question_stem', models.TextField(blank=True)),
                ('attachment', models.FileField(upload_to=learning.models.student_work_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_ext', models.CharField(blank=True, max_length=16)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_work_attachments', to='school.classgroup')),
                ('classroom_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_work_attachments', to='courses.classroomsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_work_attachments', to='courses.course')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_student_work_attachments', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_work_attachments', to='courses.lesson')),
                ('lesson_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_work_attachments', to='courses.lessonstep')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_work_attachments', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_work_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['class_group', 'lesson_step', 'question_id'], name='learning_st_class_g_8c21fe_idx'), models.Index(fields=['student', 'created_at'], name='learning_st_student_97cf05_idx'), models.Index(fields=['classroom_session', 'created_at'], name='learning_st_classro_b8eee4_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson_step', 'question_id'), name='uniq_student_work_per_step_question')],
            },
        ),
    ]
