# Generated by Django 5.2.15 on 2026-07-11 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_learningwebpage_learningwebpageresponse_and_more'),
        ('learning', '0004_studentworkattachment'),
        ('school', '0008_simplify_teaching_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField()),
                ('question_type', models.CharField(choices=[('single', '单选'), ('multiple', '多选'), ('judge', '判断'), ('blank', '填空'), ('text', '简答')], max_length=16)),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer', models.JSONField(blank=True, default=list)),
                ('analysis', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', '基础'), ('normal', '适中'), ('hard', '挑战')], default='normal', max_length=16)),
                ('knowledge_point', models.CharField(blank=True, max_length=128)),
                ('default_score', models.FloatField(default=2)),
                ('status', models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=16)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_question_bank_items', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_items', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_items', to='courses.subject')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('instruction', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '待开启'), ('open', '进行中'), ('closed', '已结束')], default='draft', max_length=16)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('show_score_after_submit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_assessments', to='courses.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_assessments', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_assessments', to='courses.subject')),
                ('target_classes', models.ManyToManyField(related_name='test_assessments', to='school.classgroup')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='test_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单选'), ('multiple', '多选'), ('judge', '判断'), ('blank', '填空'), ('text', '简答')], max_length=16)),
                ('stem', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer', models.JSONField(blank=True, default=list)),
                ('analysis', models.TextField(blank=True)),
                ('knowledge_point', models.CharField(blank=True, max_length=128)),
                ('score', models.FloatField(default=2)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.testassessment')),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='learning.questionbankitem')),
            ],
            options={
                'ordering': ['assessment_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '答题中'), ('submitted', '已提交'), ('graded', '已评分')], default='in_progress', max_length=16)),
                ('objective_score', models.FloatField(default=0)),
                ('subjective_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='learning.testassessment')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_attempts', to='school.classgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, default=list)),
                ('auto_score', models.FloatField(default=0)),
                ('manual_score', models.FloatField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_rows', to='learning.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='learning.testassessmentquestion')),
            ],
            options={
                'ordering': ['question__sort_order', 'question_id'],
            },
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['school', 'subject', 'status', 'updated_at'], name='learning_qu_school__db80cc_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['school', 'creator', 'status'], name='learning_qu_school__a8d3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['question_type', 'difficulty'], name='learning_qu_questio_c84c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='testassessment',
            index=models.Index(fields=['school', 'teacher', 'status', 'updated_at'], name='learning_te_school__831120_idx'),
        ),
        migrations.AddIndex(
            model_name='testassessment',
            index=models.Index(fields=['school', 'status', 'start_at', 'end_at'], name='learning_te_school__ce2bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='testassessmentquestion',
            index=models.Index(fields=['assessment', 'sort_order', 'id'], name='learning_te_assessm_c3be88_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['assessment', 'class_group', 'status'], name='learning_te_assessm_80faec_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student', 'status', 'started_at'], name='learning_te_student_29ce91_idx'),
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='uniq_test_attempt_per_student'),
        ),
        migrations.AddIndex(
            model_name='testattemptanswer',
            index=models.Index(fields=['attempt', 'question'], name='learning_te_attempt_5ff72d_idx'),
        ),
        migrations.AddConstraint(
            model_name='testattemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_test_answer_per_attempt_question'),
        ),
    ]
