# Generated by Django 5.2.15 on 2026-07-19 13:14

import hashlib
import json

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_question_versions(apps, schema_editor):
    QuestionBankItem = apps.get_model("learning", "QuestionBankItem")
    QuestionBankItemVersion = apps.get_model("learning", "QuestionBankItemVersion")
    QuestionBankItemLifecycleRecord = apps.get_model(
        "learning", "QuestionBankItemLifecycleRecord"
    )
    TestAssessmentQuestion = apps.get_model("learning", "TestAssessmentQuestion")

    versions = []
    lifecycle_records = []
    for question in QuestionBankItem.objects.all().iterator(chunk_size=500):
        payload = {
            "subject_id": question.subject_id,
            "stem": question.stem,
            "question_type": question.question_type,
            "options": question.options,
            "answer": question.answer,
            "analysis": question.analysis,
            "difficulty": question.difficulty,
            "knowledge_point": question.knowledge_point,
            "default_score": float(question.default_score),
        }
        encoded = json.dumps(
            payload,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
        content_hash = hashlib.sha256(encoded).hexdigest()
        QuestionBankItem.objects.filter(pk=question.pk).update(
            source="existing",
            version_no=1,
            content_hash=content_hash,
        )
        versions.append(
            QuestionBankItemVersion(
                question_id=question.pk,
                original_question_id=question.pk,
                school_id=question.school_id,
                subject_id=question.subject_id,
                creator_id=question.creator_id,
                created_by_id=question.creator_id,
                version_no=1,
                content_hash=content_hash,
                source="existing",
                status_snapshot=question.status,
                stem=question.stem,
                question_type=question.question_type,
                options=question.options,
                answer=question.answer,
                analysis=question.analysis,
                difficulty=question.difficulty,
                knowledge_point=question.knowledge_point,
                default_score=question.default_score,
            )
        )
        lifecycle_records.append(
            QuestionBankItemLifecycleRecord(
                question_id=question.pk,
                original_question_id=question.pk,
                school_id=question.school_id,
                actor_id=question.creator_id,
                from_status="",
                to_status=question.status,
                action="existing",
                note="升级前已有题目",
            )
        )
        if len(versions) >= 500:
            QuestionBankItemVersion.objects.bulk_create(versions)
            QuestionBankItemLifecycleRecord.objects.bulk_create(lifecycle_records)
            versions = []
            lifecycle_records = []
    if versions:
        QuestionBankItemVersion.objects.bulk_create(versions)
        QuestionBankItemLifecycleRecord.objects.bulk_create(lifecycle_records)

    version_ids = dict(
        QuestionBankItemVersion.objects.values_list("original_question_id", "id")
    )
    statuses = dict(QuestionBankItem.objects.values_list("id", "status"))
    for snapshot in TestAssessmentQuestion.objects.exclude(
        source_question_id=None
    ).iterator(chunk_size=500):
        TestAssessmentQuestion.objects.filter(pk=snapshot.pk).update(
            source_version_id=version_ids.get(snapshot.source_question_id),
            source_status=statuses.get(snapshot.source_question_id, "active"),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_add_evaluation_not_assessed'),
        ('learning', '0008_lesson_step_attempts_and_attachment_versions'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankItemLifecycleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_question_id', models.PositiveBigIntegerField()),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('trial', '可试用'), ('active', '启用'), ('disabled', '停用')], max_length=24)),
                ('action', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_question_id', models.PositiveBigIntegerField()),
                ('version_no', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('manual', '手工创建'), ('xlsx', 'XLSX 导入'), ('ai', 'AI 生成'), ('copy', '复制题目'), ('existing', '既有题目')], max_length=16)),
                ('status_snapshot', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('trial', '可试用'), ('active', '启用'), ('disabled', '停用')], max_length=24)),
                ('stem', models.TextField()),
                ('question_type', models.CharField(choices=[('single', '单选'), ('multiple', '多选'), ('judge', '判断'), ('blank', '填空'), ('text', '简答')], max_length=16)),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer', models.JSONField(blank=True, default=list)),
                ('analysis', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', '基础'), ('normal', '适中'), ('hard', '挑战')], max_length=16)),
                ('knowledge_point', models.CharField(blank=True, max_length=128)),
                ('default_score', models.FloatField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['original_question_id', 'version_no'],
            },
        ),
        migrations.RemoveField(
            model_name='questionbankitem',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='disabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disabled_question_bank_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='disabled_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_question_bank_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='source',
            field=models.CharField(choices=[('manual', '手工创建'), ('xlsx', 'XLSX 导入'), ('ai', 'AI 生成'), ('copy', '复制题目'), ('existing', '既有题目')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='version_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testassessmentquestion',
            name='source_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('trial', '可试用'), ('active', '启用'), ('disabled', '停用')], default='active', max_length=24),
        ),
        migrations.AlterField(
            model_name='questionbankitem',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('trial', '可试用'), ('active', '启用'), ('disabled', '停用')], default='draft', max_length=24),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['school', 'status', 'submitted_for_review_at'], name='learning_qu_school__4ab2e0_idx'),
        ),
        migrations.AddField(
            model_name='questionbankitemlifecyclerecord',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_lifecycle_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionbankitemlifecyclerecord',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_records', to='learning.questionbankitem'),
        ),
        migrations.AddField(
            model_name='questionbankitemlifecyclerecord',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_lifecycle_records', to='school.school'),
        ),
        migrations.AddField(
            model_name='questionbankitemversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_question_bank_item_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionbankitemversion',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_question_bank_item_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionbankitemversion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='learning.questionbankitem'),
        ),
        migrations.AddField(
            model_name='questionbankitemversion',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_item_versions', to='school.school'),
        ),
        migrations.AddField(
            model_name='questionbankitemversion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_item_versions', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='testassessmentquestion',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_questions', to='learning.questionbankitemversion'),
        ),
        migrations.RunPython(backfill_question_versions, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='questionbankitemlifecyclerecord',
            index=models.Index(fields=['school', 'to_status', 'created_at'], name='learning_qu_school__a28551_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankitemlifecyclerecord',
            index=models.Index(fields=['question', 'created_at'], name='learning_qu_questio_fbd66c_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankitemversion',
            index=models.Index(fields=['school', 'subject', 'created_at'], name='learning_qu_school__c0bc40_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankitemversion',
            index=models.Index(fields=['question', 'version_no'], name='learning_qu_questio_1cd794_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankitemversion',
            index=models.Index(fields=['content_hash'], name='learning_qu_content_1bc21e_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbankitemversion',
            constraint=models.UniqueConstraint(fields=('school', 'original_question_id', 'version_no'), name='uniq_question_bank_item_version'),
        ),
        migrations.AddConstraint(
            model_name='questionbankitemversion',
            constraint=models.UniqueConstraint(fields=('school', 'original_question_id', 'content_hash'), name='uniq_question_bank_item_content_hash'),
        ),
    ]
