# Generated by Django 5.2.15 on 2026-07-19 14:13

from django.conf import settings
from django.db import migrations, models


def mark_existing_shared_questions(apps, schema_editor):
    QuestionBankItem = apps.get_model('learning', 'QuestionBankItem')
    QuestionBankItem.objects.filter(
        status__in=['pending_review', 'trial', 'active'],
    ).update(library_scope='school')
    QuestionBankItem.objects.filter(reviewed_by__isnull=False).update(
        library_scope='school',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_add_evaluation_not_assessed'),
        ('learning', '0009_questionbankitemlifecyclerecord_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbankitem',
            name='library_scope',
            field=models.CharField(choices=[('personal', '个人题目'), ('school', '校内共享')], default='personal', max_length=16),
        ),
        migrations.RunPython(
            mark_existing_shared_questions,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['school', 'library_scope', 'status'], name='learning_qu_school__583af6_idx'),
        ),
    ]
