# Generated by Django 5.2.15 on 2026-07-19 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_classroomevaluationconfig_legacy_only_and_more'),
        ('learning', '0010_question_library_scope'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentComparabilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('comparable', '可以比较'), ('not_comparable', '不可比较'), ('insufficient', '数据不足')], max_length=24)),
                ('common_question_count', models.PositiveIntegerField(default=0)),
                ('exact_version_match_count', models.PositiveIntegerField(default=0)),
                ('left_sample_size', models.PositiveIntegerField(default=0)),
                ('right_sample_size', models.PositiveIntegerField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('compared_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-compared_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommonQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('grade_scope', models.CharField(blank=True, max_length=32)),
                ('term', models.CharField(blank=True, max_length=32)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject_id', 'grade_scope', 'term', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='CommonQuestionSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_code', models.CharField(max_length=64)),
                ('required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='comparison_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='item_role',
            field=models.CharField(choices=[('regular', '普通题'), ('common', '共同题'), ('layered', '分层题')], default='regular', max_length=16),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='layer_scope',
            field=models.CharField(choices=[('all', '全体'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('ab', 'A/B'), ('bc', 'B/C')], default='all', max_length=8),
        ),
        migrations.AddField(
            model_name='questionbankitemversion',
            name='comparison_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='questionbankitemversion',
            name='item_role',
            field=models.CharField(choices=[('regular', '普通题'), ('common', '共同题'), ('layered', '分层题')], default='regular', max_length=16),
        ),
        migrations.AddField(
            model_name='questionbankitemversion',
            name='layer_scope',
            field=models.CharField(choices=[('all', '全体'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('ab', 'A/B'), ('bc', 'B/C')], default='all', max_length=8),
        ),
        migrations.AddField(
            model_name='testassessment',
            name='common_set_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='testassessment',
            name='common_set_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testassessmentquestion',
            name='comparison_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='testassessmentquestion',
            name='item_role',
            field=models.CharField(choices=[('regular', '普通题'), ('common', '共同题'), ('layered', '分层题')], default='regular', max_length=16),
        ),
        migrations.AddField(
            model_name='testassessmentquestion',
            name='layer_scope',
            field=models.CharField(choices=[('all', '全体'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('ab', 'A/B'), ('bc', 'B/C')], default='all', max_length=8),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['school', 'subject', 'item_role', 'comparison_code'], name='learning_qu_school__1238b3_idx'),
        ),
        migrations.AddField(
            model_name='assessmentcomparabilityrecord',
            name='left_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_left', to='learning.testassessment'),
        ),
        migrations.AddField(
            model_name='assessmentcomparabilityrecord',
            name='right_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_right', to='learning.testassessment'),
        ),
        migrations.AddField(
            model_name='assessmentcomparabilityrecord',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_comparability_records', to='school.school'),
        ),
        migrations.AddField(
            model_name='commonquestionset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_common_question_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonquestionset',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_common_question_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonquestionset',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_question_sets', to='school.school'),
        ),
        migrations.AddField(
            model_name='commonquestionset',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_question_sets', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='testassessment',
            name='common_question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='learning.commonquestionset'),
        ),
        migrations.AddField(
            model_name='commonquestionsetitem',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.commonquestionset'),
        ),
        migrations.AddField(
            model_name='commonquestionsetitem',
            name='question_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_set_items', to='learning.questionbankitemversion'),
        ),
        migrations.AddIndex(
            model_name='assessmentcomparabilityrecord',
            index=models.Index(fields=['school', 'status', 'compared_at'], name='learning_as_school__e800d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcomparabilityrecord',
            constraint=models.UniqueConstraint(fields=('left_assessment', 'right_assessment'), name='uniq_assessment_comparison_pair'),
        ),
        migrations.AddIndex(
            model_name='commonquestionset',
            index=models.Index(fields=['school', 'subject', 'status', 'updated_at'], name='learning_co_school__19a61f_idx'),
        ),
        migrations.AddConstraint(
            model_name='commonquestionset',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'grade_scope', 'term', 'version_no'), name='uniq_common_question_set_version'),
        ),
        migrations.AddConstraint(
            model_name='commonquestionsetitem',
            constraint=models.UniqueConstraint(fields=('question_set', 'question_version'), name='uniq_common_set_question_version'),
        ),
        migrations.AddConstraint(
            model_name='commonquestionsetitem',
            constraint=models.UniqueConstraint(fields=('question_set', 'comparison_code'), name='uniq_common_set_comparison_code'),
        ),
    ]
