# Generated by Django 5.2.15 on 2026-07-19 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0002_teacheraiprovider'),
        ('courses', '0026_classroomevaluationconfig_legacy_only_and_more'),
        ('learning', '0011_assessmentcomparabilityrecord_commonquestionset_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stratificationdecision',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='learning_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='missing_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='rule_version',
            field=models.CharField(default='transparent-rules-v1', max_length=32),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='support_suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='teacher_selected_layer',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stratificationdecision',
            name='status',
            field=models.CharField(choices=[('pending', '待教师确认'), ('accepted', '已采纳'), ('kept', '保持当前安排'), ('adjusted', '教师已调整'), ('deferred', '暂缓处理'), ('rejected', '已拒绝')], default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='stratificationdecision',
            index=models.Index(fields=['subject', 'status', 'created_at'], name='learning_st_subject_81ab95_idx'),
        ),
    ]
