# Generated by Django 5.2.15 on 2026-07-19 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0002_teacheraiprovider'),
        ('courses', '0026_classroomevaluationconfig_legacy_only_and_more'),
        ('learning', '0012_stratificationdecision_course_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stratificationdecision',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'window_end', 'rule_version'), name='uniq_stratification_suggestion_window'),
        ),
    ]
