# Generated by Django 5.2.15 on 2026-07-20 05:09

import django.db.models.deletion
from django.db import migrations, models


def link_existing_model_candidates(apps, schema_editor):
    StratificationDecision = apps.get_model('learning', 'StratificationDecision')
    ClassCalibrationRun = apps.get_model('learning_analytics', 'ClassCalibrationRun')
    available_ids = set(ClassCalibrationRun.objects.values_list('id', flat=True))
    for decision in StratificationDecision.objects.filter(
        rule_version__startswith='m03-',
        calibration_run__isnull=True,
    ).iterator():
        payload = decision.learning_summary if isinstance(decision.learning_summary, dict) else {}
        run_id = payload.get('calibration_run_id')
        if isinstance(run_id, int) and run_id in available_ids:
            StratificationDecision.objects.filter(pk=decision.pk).update(
                calibration_run_id=run_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_stratificationdecision_uniq_stratification_suggestion_window'),
        ('learning_analytics', '0027_classcalibrationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratificationdecision',
            name='calibration_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stratification_decisions', to='learning_analytics.classcalibrationrun'),
        ),
        migrations.RunPython(link_existing_model_candidates, migrations.RunPython.noop),
    ]
