# Generated by Django 5.2.15 on 2026-07-20 05:23

import hashlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_common_test_version_groundwork(apps, schema_editor):
    CommonQuestionSet = apps.get_model('learning', 'CommonQuestionSet')
    KnowledgeComponent = apps.get_model('learning', 'KnowledgeComponent')
    Mapping = apps.get_model('learning', 'QuestionVersionKnowledgeComponent')
    groups = {}
    for question_set in CommonQuestionSet.objects.select_related('school', 'subject').order_by(
        'school_id', 'subject_id', 'grade_scope', 'term', 'version_no', 'id'
    ):
        group_key = (
            question_set.school_id,
            question_set.subject_id,
            question_set.grade_scope,
            question_set.term,
        )
        groups.setdefault(group_key, []).append(question_set)

    for sets in groups.values():
        previous = None
        for question_set in sets:
            raw = (
                f'{question_set.school.code}|{question_set.subject.code}|'
                f'{question_set.grade_scope or "ALL"}|{question_set.term or "ALL"}'
            )
            series = f'CS-{hashlib.sha256(raw.encode("utf-8")).hexdigest()[:24].upper()}'
            previous_items = {
                item.comparison_code: item
                for item in previous.items.select_related('question_version').all()
            } if previous else {}
            item_count = 0
            anchor_count = 0
            mapped_count = 0
            for item in question_set.items.select_related('question_version').all():
                item_count += 1
                source = previous_items.get(item.comparison_code)
                if source and source.question_version.content_hash == item.question_version.content_hash:
                    item.anchor_source_id = source.id
                    item.save(update_fields=['anchor_source'])
                    anchor_count += 1
                name = ' '.join((item.question_version.knowledge_point or '').split())[:128]
                if not name:
                    continue
                code_raw = f'{question_set.subject_id}|{name}'
                code = f'KC-{hashlib.sha256(code_raw.encode("utf-8")).hexdigest()[:12].upper()}'
                component, _ = KnowledgeComponent.objects.get_or_create(
                    school_id=question_set.school_id,
                    subject_id=question_set.subject_id,
                    name=name,
                    defaults={'code': code},
                )
                Mapping.objects.get_or_create(
                    question_version_id=item.question_version_id,
                    component_id=component.id,
                    defaults={
                        'created_by_id': item.question_version.created_by_id,
                        'weight': 1.0,
                        'is_primary': True,
                    },
                )
                mapped_count += 1
            anchor_ratio = round(anchor_count / item_count, 4) if item_count else 0
            blockers = []
            if previous:
                if anchor_count < 5:
                    blockers.append('与上一版本完全一致的共同题少于 5 道。')
                if anchor_ratio < 0.3:
                    blockers.append('锚题比例低于 30%。')
            else:
                blockers.append('这是首个版本，需要后续版本后才能比较版本变化。')
            if mapped_count < item_count:
                blockers.append(f'还有 {item_count - mapped_count} 道题未填写知识点。')
            if item_count < 10:
                blockers.append('题目少于 10 道，暂不准备 IRT 参数估计。')
            readiness = {
                'schema_version': '1.0',
                'item_count': item_count,
                'anchor_count': anchor_count,
                'anchor_ratio': anchor_ratio,
                'knowledge_mapped_count': mapped_count,
                've_collection_ready': bool(previous and anchor_count >= 5 and anchor_ratio >= 0.3),
                'irt_collection_ready': bool(item_count >= 10 and mapped_count == item_count),
                'bkt_collection_ready': bool(item_count > 0 and mapped_count == item_count),
                'requires_real_responses': True,
                'blockers': blockers,
            }
            CommonQuestionSet.objects.filter(pk=question_set.pk).update(
                measurement_series=series,
                version_purpose='follow_up' if previous else 'baseline',
                previous_version_id=previous.id if previous else None,
                readiness=readiness,
            )
            previous = question_set


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_classroomevaluationconfig_legacy_only_and_more'),
        ('learning', '0014_stratificationdecision_calibration_run'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='QuestionVersionKnowledgeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['question_version_id', '-is_primary', 'component_id'],
            },
        ),
        migrations.AddField(
            model_name='commonquestionset',
            name='measurement_series',
            field=models.CharField(blank=True, db_index=True, max_length=96),
        ),
        migrations.AddField(
            model_name='commonquestionset',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='learning.commonquestionset'),
        ),
        migrations.AddField(
            model_name='commonquestionset',
            name='readiness',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='commonquestionset',
            name='version_purpose',
            field=models.CharField(choices=[('baseline', '首个版本'), ('follow_up', '后续版本'), ('parallel', '平行版本')], default='baseline', max_length=16),
        ),
        migrations.AddField(
            model_name='commonquestionsetitem',
            name='anchor_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anchor_successors', to='learning.commonquestionsetitem'),
        ),
        migrations.AddIndex(
            model_name='commonquestionset',
            index=models.Index(fields=['school', 'subject', 'measurement_series', 'version_no'], name='learning_co_school__3e2582_idx'),
        ),
        migrations.AddField(
            model_name='knowledgecomponent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_components', to='school.school'),
        ),
        migrations.AddField(
            model_name='knowledgecomponent',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_components', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='questionversionknowledgecomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_mappings', to='learning.knowledgecomponent'),
        ),
        migrations.AddField(
            model_name='questionversionknowledgecomponent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_question_knowledge_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionversionknowledgecomponent',
            name='question_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_mappings', to='learning.questionbankitemversion'),
        ),
        migrations.AddIndex(
            model_name='knowledgecomponent',
            index=models.Index(fields=['school', 'subject', 'is_active'], name='learning_kn_school__4715f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecomponent',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'code'), name='uniq_knowledge_component_code'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecomponent',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'name'), name='uniq_knowledge_component_name'),
        ),
        migrations.AddIndex(
            model_name='questionversionknowledgecomponent',
            index=models.Index(fields=['component', 'question_version'], name='learning_qu_compone_ccf61e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionversionknowledgecomponent',
            index=models.Index(fields=['question_version', 'is_primary'], name='learning_qu_questio_65fc84_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionversionknowledgecomponent',
            constraint=models.UniqueConstraint(fields=('question_version', 'component'), name='uniq_question_version_knowledge_component'),
        ),
        migrations.RunPython(
            backfill_common_test_version_groundwork,
            migrations.RunPython.noop,
        ),
    ]
