# Generated by Django 5.2.15 on 2026-07-20 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def retire_legacy_layer_suggestions(apps, schema_editor):
    StratificationDecision = apps.get_model('learning', 'StratificationDecision')
    StratificationDecision.objects.all().update(
        decision_kind='legacy',
        support_priority='',
        boundary_band='',
        policy_version='legacy-compat-v1',
    )
    StratificationDecision.objects.filter(status='pending').update(
        status='deferred',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0002_teacheraiprovider'),
        ('courses', '0027_remove_classroomgroup_uniq_classroom_group_no_per_collaboration_and_more'),
        ('learning', '0015_common_test_version_groundwork'),
        ('learning_analytics', '0029_classcalibrationrun_decision_purpose'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('A', '拓展挑战层'), ('B', '核心发展层'), ('C', '基础提升层')], max_length=1)),
                ('boundary_band', models.CharField(blank=True, choices=[('A/B', 'A/B 边界'), ('B/C', 'B/C 边界')], max_length=3)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(max_length=32)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-valid_from', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='boundary_band',
            field=models.CharField(blank=True, choices=[('A/B', 'A/B 边界'), ('B/C', 'B/C 边界')], max_length=3),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='decision_kind',
            field=models.CharField(choices=[('support', '学习支持'), ('content_band', '学习内容层级'), ('legacy', '兼容记录')], default='support', max_length=16),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='policy_version',
            field=models.CharField(default='support-policy-v2', max_length=32),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='support_priority',
            field=models.CharField(blank=True, choices=[('routine', '常规关注'), ('watch', '持续关注'), ('high', '优先支持')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='stratificationdecision',
            index=models.Index(fields=['decision_kind', 'status', 'created_at'], name='learning_st_decisio_3c4bc6_idx'),
        ),
        migrations.AddField(
            model_name='studentsubjectband',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_subject_bands', to='school.classgroup'),
        ),
        migrations.AddField(
            model_name='studentsubjectband',
            name='confirmed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_student_subject_bands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsubjectband',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_bands', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentsubjectband',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_subject_bands', to='school.school'),
        ),
        migrations.AddField(
            model_name='studentsubjectband',
            name='source_decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_bands', to='learning.stratificationdecision'),
        ),
        migrations.AddField(
            model_name='studentsubjectband',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_bands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsubjectband',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_bands', to='courses.subject'),
        ),
        migrations.AddIndex(
            model_name='studentsubjectband',
            index=models.Index(fields=['student', 'subject', 'valid_from'], name='learning_st_student_67fa5c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubjectband',
            index=models.Index(fields=['class_group', 'subject', 'valid_until'], name='learning_st_class_g_6e067e_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentsubjectband',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True), ('valid_until__isnull', True)), fields=('student', 'subject'), name='uniq_active_student_subject_band'),
        ),
        migrations.AddConstraint(
            model_name='studentsubjectband',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('valid_until__isnull', True)), fields=('student', 'subject', 'course'), name='uniq_active_student_course_band'),
        ),
        migrations.RunPython(
            retire_legacy_layer_suggestions,
            migrations.RunPython.noop,
        ),
    ]
