# Generated by Django 5.2.15 on 2026-07-20 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_remove_classroomgroup_uniq_classroom_group_no_per_collaboration_and_more'),
        ('learning', '0016_studentsubjectband_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stratificationdecision',
            name='abstain_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='transition_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ContentBandPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('policy_version', models.CharField(max_length=32)),
                ('a_min', models.FloatField(default=0.8)),
                ('b_min', models.FloatField(default=0.6)),
                ('boundary_margin', models.FloatField(default=0.03)),
                ('hysteresis_margin', models.FloatField(default=0.03)),
                ('max_measurement_error', models.FloatField(default=0.18)),
                ('min_common_items', models.PositiveSmallIntegerField(default=5)),
                ('min_answered_ratio', models.FloatField(default=0.8)),
                ('required_consecutive_windows', models.PositiveSmallIntegerField(default=2)),
                ('cooldown_days', models.PositiveSmallIntegerField(default=14)),
                ('max_step_change', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('retired', '停用')], default='draft', max_length=16)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_band_policies', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_band_policies', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_content_band_policies', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_band_policies', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_band_policies', to='courses.subject')),
            ],
            options={
                'ordering': ['subject_id', 'course_id', '-version_no', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='learning.contentbandpolicyversion'),
        ),
        migrations.CreateModel(
            name='StudentMasterySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_series', models.CharField(db_index=True, max_length=96)),
                ('assessment_version', models.CharField(max_length=32)),
                ('data_status', models.CharField(choices=[('available', '可用'), ('insufficient', '数据不足'), ('not_comparable', '不可比较'), ('pending_grading', '等待评分')], max_length=24)),
                ('score_obtained', models.FloatField(default=0)),
                ('score_max', models.FloatField(default=0)),
                ('mastery_score', models.FloatField(blank=True, null=True)),
                ('measurement_error', models.FloatField(blank=True, null=True)),
                ('common_item_count', models.PositiveIntegerField(default=0)),
                ('answered_item_count', models.PositiveIntegerField(default=0)),
                ('answered_ratio', models.FloatField(default=0)),
                ('knowledge_results', models.JSONField(blank=True, default=list)),
                ('comparability_evidence', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('is_test_data', models.BooleanField(default=False)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mastery_snapshots', to='learning.testassessment')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mastery_snapshot', to='learning.testattempt')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_mastery_snapshots', to='school.classgroup')),
                ('common_question_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mastery_snapshots', to='learning.commonquestionset')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_mastery_snapshots', to='courses.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_mastery_snapshots', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mastery_snapshots', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_mastery_snapshots', to='courses.subject')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stratificationdecision',
            name='mastery_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='learning.studentmasterysnapshot'),
        ),
        migrations.AddField(
            model_name='studentsubjectband',
            name='mastery_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_bands', to='learning.studentmasterysnapshot'),
        ),
        migrations.CreateModel(
            name='BandTransitionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_band', models.CharField(blank=True, max_length=1)),
                ('raw_candidate_band', models.CharField(blank=True, max_length=1)),
                ('guarded_candidate_band', models.CharField(blank=True, max_length=1)),
                ('checks', models.JSONField(default=dict)),
                ('action', models.CharField(max_length=24)),
                ('final_band', models.CharField(blank=True, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_band_transition_audits', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='band_transition_audits', to='courses.course')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_audits', to='learning.stratificationdecision')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='band_transition_audits', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='band_transition_audits', to='courses.subject')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['student', 'subject', 'created_at'], name='learning_ba_student_2a912f_idx'), models.Index(fields=['decision', 'action'], name='learning_ba_decisio_cc8444_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contentbandpolicyversion',
            index=models.Index(fields=['school', 'subject', 'status'], name='learning_co_school__71346c_idx'),
        ),
        migrations.AddIndex(
            model_name='contentbandpolicyversion',
            index=models.Index(fields=['course', 'status', 'version_no'], name='learning_co_course__bb32c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentbandpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True)), fields=('school', 'subject', 'version_no'), name='uniq_subject_band_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='contentbandpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('school', 'subject', 'course', 'version_no'), name='uniq_course_band_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='contentbandpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True), ('status', 'active')), fields=('school', 'subject'), name='uniq_active_subject_band_policy'),
        ),
        migrations.AddConstraint(
            model_name='contentbandpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('status', 'active')), fields=('school', 'subject', 'course'), name='uniq_active_course_band_policy'),
        ),
        migrations.AddIndex(
            model_name='studentmasterysnapshot',
            index=models.Index(fields=['student', 'subject', 'observed_at'], name='learning_st_student_0e497d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmasterysnapshot',
            index=models.Index(fields=['school', 'subject', 'data_status'], name='learning_st_school__c64af9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmasterysnapshot',
            index=models.Index(fields=['measurement_series', 'assessment_version'], name='learning_st_measure_5b19bb_idx'),
        ),
    ]
