# Generated by Django 5.2.15 on 2026-07-22 04:58

import django.db.models.deletion
import hashlib
import json
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_published_diagnostic_versions(apps, schema_editor):
    PretestPaper = apps.get_model("learning", "PretestPaper")
    PretestQuestion = apps.get_model("learning", "PretestQuestion")
    PretestPaperVersion = apps.get_model("learning", "PretestPaperVersion")
    PretestSubmission = apps.get_model("learning", "PretestSubmission")
    User = apps.get_model("accounts", "User")

    # Only immutable historical papers receive synthetic target identifiers and
    # a published snapshot. Drafts remain editable and must be reviewed before
    # their first publication.
    immutable_statuses = ("published", "archived")
    for question in PretestQuestion.objects.filter(
        paper__status__in=immutable_statuses,
        learning_target_code="",
    ):
        question.learning_target_code = f"ENTRY-{question.id}"
        question.learning_target_name = question.dimension or question.stem[:80]
        question.save(update_fields=["learning_target_code", "learning_target_name"])

    for paper in PretestPaper.objects.filter(
        status__in=immutable_statuses
    ).order_by("id"):
        actor_id = paper.created_by_id
        if not actor_id:
            actor_id = (
                User.objects.filter(school_id=paper.school_id)
                .order_by("id")
                .values_list("id", flat=True)
                .first()
            )
        if not actor_id:
            continue
        snapshot = []
        for question in PretestQuestion.objects.filter(paper_id=paper.id).order_by(
            "sort_order", "id"
        ):
            snapshot.append(
                {
                    "id": question.id,
                    "stem": question.stem,
                    "question_type": question.question_type,
                    "options": question.options,
                    "answer": question.answer,
                    "score": question.score,
                    "dimension": question.dimension,
                    "learning_target_code": question.learning_target_code,
                    "learning_target_name": question.learning_target_name,
                    "material_requirements": question.material_requirements,
                    "is_required": question.is_required,
                    "sort_order": question.sort_order,
                }
            )
        payload = {
            "source_id": paper.id,
            "version_no": paper.version,
            "title": paper.title,
            "kind": paper.kind,
            "introduction": paper.introduction,
            "question_snapshot": snapshot,
        }
        content_hash = hashlib.sha256(
            json.dumps(
                payload,
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
        ).hexdigest()
        version, _ = PretestPaperVersion.objects.get_or_create(
            source_id=paper.id,
            version_no=paper.version,
            defaults={
                "content_hash": content_hash,
                "title": paper.title,
                "kind": paper.kind,
                "introduction": paper.introduction,
                "question_snapshot": snapshot,
                "published_by_id": actor_id,
            },
        )
        PretestSubmission._base_manager.filter(
            paper_id=paper.id,
            paper_version__isnull=True,
        ).update(paper_version_id=version.id)

def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_classroomgroupcollaboration_storage_quota_mb'),
        ('learning', '0020_rebuild_active_legacy_support'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestquestion',
            name='learning_target_code',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='pretestquestion',
            name='learning_target_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pretestquestion',
            name='material_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pretestsubmission',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pretestsubmission',
            name='opportunity_status',
            field=models.CharField(choices=[('observed', '已获得评价机会'), ('missing', '材料缺失'), ('device_issue', '设备问题'), ('not_offered', '未获得评价机会')], default='observed', max_length=24),
        ),
        migrations.AddField(
            model_name='pretestsubmission',
            name='target_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pretestsubmission',
            name='task_statuses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveConstraint(
            model_name='pretestsubmission',
            name='uniq_pretest_submission_per_paper',
        ),
        migrations.AddField(
            model_name='pretestsubmission',
            name='attempt_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='pretestsubmission',
            constraint=models.UniqueConstraint(fields=('student', 'paper', 'attempt_no'), name='uniq_pretest_submission_attempt'),
        ),
        migrations.AlterField(
            model_name='pretestpaper',
            name='kind',
            field=models.CharField(choices=[('literacy', '学科学习诊断'), ('attitude', '学习支持问卷')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pretestquestion',
            name='question_type',
            field=models.CharField(choices=[('single', '单选'), ('multiple', '多选'), ('scale', '量表'), ('text', '简答'), ('performance', '表现任务'), ('operation', '操作任务'), ('short_project', '短项目')], default='single', max_length=16),
        ),
        migrations.AlterField(
            model_name='pretestsubmission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PretestPaperVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('content_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('title', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('literacy', '学科学习诊断'), ('attitude', '学习支持问卷')], max_length=16)),
                ('introduction', models.TextField(blank=True)),
                ('question_snapshot', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_pretest_versions', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_versions', to='learning.pretestpaper')),
            ],
            options={
                'ordering': ['source_id', '-version_no'],
            },
        ),
        migrations.AddField(
            model_name='pretestsubmission',
            name='paper_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning.pretestpaperversion'),
        ),
        migrations.RunPython(
            backfill_published_diagnostic_versions,
            noop_reverse,
        ),
        migrations.CreateModel(
            name='StudentLearningTargetStateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_target_code', models.CharField(max_length=96)),
                ('learning_target_name', models.CharField(max_length=300)),
                ('source_type', models.CharField(max_length=48)),
                ('source_id', models.CharField(max_length=96)),
                ('source_version', models.CharField(max_length=96)),
                ('evidence_status', models.CharField(choices=[('available', '材料可用'), ('partial', '材料部分可用'), ('insufficient', '材料不足'), ('pending_review', '等待评价'), ('not_observed', '未形成观察')], max_length=24)),
                ('evidence_coverage', models.FloatField(default=0)),
                ('estimate', models.FloatField(blank=True, null=True)),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('material_references', models.JSONField(blank=True, default=list)),
                ('observation_notes', models.JSONField(blank=True, default=list)),
                ('is_initial_diagnostic', models.BooleanField(default=False)),
                ('observed_at', models.DateTimeField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_target_state_versions', to='school.classgroup')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_target_state_versions', to='courses.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_target_state_versions', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_target_state_versions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_target_state_versions', to='courses.subject')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LearningSupportRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('routine', '常规支持'), ('watch', '持续关注'), ('priority', '优先支持')], max_length=16)),
                ('suggestion', models.TextField()),
                ('rationale', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '待教师确认'), ('confirmed', '已确认'), ('adjusted', '教师已调整'), ('deferred', '暂缓安排')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_learning_support_recommendations', to=settings.AUTH_USER_MODEL)),
                ('target_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_recommendations', to='learning.studentlearningtargetstateversion')),
            ],
        ),
        migrations.CreateModel(
            name='LearningContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_band', models.CharField(blank=True, max_length=1)),
                ('status', models.CharField(choices=[('not_recommended', '暂不建议'), ('pending', '待教师确认'), ('confirmed', '已确认'), ('kept', '保持当前安排'), ('adjusted', '教师已调整')], max_length=24)),
                ('rationale', models.JSONField(blank=True, default=list)),
                ('evidence_coverage', models.FloatField(default=0)),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('teacher_selected_band', models.CharField(blank=True, max_length=1)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_learning_content_recommendations', to=settings.AUTH_USER_MODEL)),
                ('source_decision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_recommendation', to='learning.stratificationdecision')),
                ('target_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_recommendations', to='learning.studentlearningtargetstateversion')),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedAssessmentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ownership', models.CharField(choices=[('individual', '个人评价材料'), ('group', '小组评价材料')], max_length=16)),
                ('group_reference', models.CharField(blank=True, max_length=96)),
                ('material_type', models.CharField(choices=[('answer', '作答记录'), ('artifact', '作品材料'), ('operation', '操作记录'), ('oral_defense', '答辩记录'), ('observation', '观察记录'), ('score', '评分记录')], max_length=24)),
                ('material_status', models.CharField(choices=[('available', '材料可用'), ('missing', '材料缺失'), ('device_issue', '设备问题'), ('not_offered', '未获得机会'), ('pending_review', '等待评价')], max_length=24)),
                ('learning_target_code', models.CharField(blank=True, max_length=96)),
                ('source_type', models.CharField(max_length=48)),
                ('source_id', models.CharField(max_length=96)),
                ('source_version', models.CharField(max_length=96)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('score_max', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_materials', to='school.classgroup')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_materials', to='courses.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_materials', to='school.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_materials', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_materials', to='courses.subject')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pretestpaperversion',
            constraint=models.UniqueConstraint(fields=('source', 'version_no'), name='uniq_pretest_source_version'),
        ),
        migrations.AddConstraint(
            model_name='pretestpaperversion',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='uniq_pretest_source_content_hash'),
        ),
        migrations.AddIndex(
            model_name='studentlearningtargetstateversion',
            index=models.Index(fields=['student', 'subject', 'observed_at'], name='learning_st_student_4fcef8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlearningtargetstateversion',
            index=models.Index(fields=['class_group', 'subject', 'evidence_status'], name='learning_st_class_g_b934ab_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlearningtargetstateversion',
            index=models.Index(fields=['learning_target_code', 'observed_at'], name='learning_st_learnin_95c325_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentlearningtargetstateversion',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'course', 'learning_target_code', 'source_type', 'source_id', 'source_version'), name='uniq_student_target_state_source_version'),
        ),
        migrations.AddIndex(
            model_name='unifiedassessmentmaterial',
            index=models.Index(fields=['student', 'subject', 'recorded_at'], name='learning_un_student_d9be2c_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedassessmentmaterial',
            index=models.Index(fields=['source_type', 'source_id', 'source_version'], name='learning_un_source__0d7ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedassessmentmaterial',
            index=models.Index(fields=['learning_target_code', 'material_status'], name='learning_un_learnin_d31610_idx'),
        ),
    ]
