# Generated by Django 5.2.15 on 2026-07-22 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_classroomgroupcollaboration_storage_quota_mb'),
        ('learning', '0021_pretestquestion_learning_target_code_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentlearningtargetstateversion',
            name='uniq_student_target_state_source_version',
        ),
        migrations.AddField(
            model_name='learningsupportrecommendation',
            name='source_decision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_recommendation', to='learning.stratificationdecision'),
        ),
        migrations.AddConstraint(
            model_name='learningsupportrecommendation',
            constraint=models.UniqueConstraint(fields=('target_state',), name='uniq_support_recommendation_target_state'),
        ),
        migrations.AddConstraint(
            model_name='studentlearningtargetstateversion',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True)), fields=('student', 'subject', 'learning_target_code', 'source_type', 'source_id', 'source_version'), name='uniq_subject_target_state_source_version'),
        ),
        migrations.AddConstraint(
            model_name='studentlearningtargetstateversion',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('student', 'subject', 'course', 'learning_target_code', 'source_type', 'source_id', 'source_version'), name='uniq_course_target_state_source_version'),
        ),
    ]
