# Generated by Django 5.2.15 on 2026-07-22

import hashlib
import json

import django.db.models.deletion
import learning.models
import uuid
from django.conf import settings
from django.db import migrations, models


def mark_legacy_materials(apps, schema_editor):
    Material = apps.get_model("learning", "UnifiedAssessmentMaterial")
    seen_reviews = set()
    for material in Material.objects.order_by("id").iterator():
        content = material.content if isinstance(material.content, dict) else {}
        source_id = material.source_id
        legacy_unmapped = material.recorded_by_id is None
        if material.source_type == "learning_entry_diagnostic_review":
            review_key = (material.source_type, source_id)
            if review_key in seen_reviews:
                content = {
                    **content,
                    "legacy_duplicate_source_id": source_id,
                    "legacy_duplicate_preserved": True,
                }
                source_id = f"{source_id[:64]}:legacy:{material.id}"
                legacy_unmapped = True
            else:
                seen_reviews.add(review_key)
        semantic = {
            "material_id": str(material.material_id),
            "school_id": material.school_id,
            "subject_id": material.subject_id,
            "course_id": material.course_id,
            "class_group_id": material.class_group_id,
            "student_id": material.student_id,
            "recorded_by_id": material.recorded_by_id,
            "legacy_unmapped": legacy_unmapped,
            "ownership": material.ownership,
            "group_reference": material.group_reference,
            "material_type": material.material_type,
            "material_status": material.material_status,
            "learning_target_code": material.learning_target_code,
            "source_type": material.source_type,
            "source_id": source_id,
            "source_version": material.source_version,
            "content": content,
            "score": material.score,
            "score_max": material.score_max,
            "recorded_at": material.recorded_at,
        }
        content_hash = hashlib.sha256(
            json.dumps(
                semantic,
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
                default=str,
            ).encode("utf-8")
        ).hexdigest()
        Material.objects.filter(pk=material.pk).update(
            content=content,
            source_id=source_id,
            legacy_unmapped=legacy_unmapped,
            content_hash=content_hash,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_alter_classroomgroupcollaboration_storage_quota_mb"),
        (
            "learning",
            "0022_remove_studentlearningtargetstateversion_uniq_student_target_state_source_version_and_more",
        ),
        ("school", "0009_school_is_synthetic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PretestMaterialAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("question_id", models.CharField(max_length=64)),
                (
                    "attachment",
                    models.FileField(
                        max_length=500,
                        upload_to=learning.models.pretest_material_upload_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file_ext", models.CharField(max_length=16)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("file_size", models.PositiveIntegerField()),
                (
                    "file_sha256",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["material_id", "id"]},
        ),
        migrations.AddField(
            model_name="unifiedassessmentmaterial",
            name="content_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="unifiedassessmentmaterial",
            name="legacy_unmapped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unifiedassessmentmaterial",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_assessment_materials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(mark_legacy_materials, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="unifiedassessmentmaterial",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source_type", "learning_entry_diagnostic_review")
                ),
                fields=("source_type", "source_id"),
                name="uniq_pretest_material_review_source",
            ),
        ),
        migrations.AddField(
            model_name="pretestmaterialattachment",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="learning.unifiedassessmentmaterial",
            ),
        ),
        migrations.AddField(
            model_name="pretestmaterialattachment",
            name="paper_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="material_attachments",
                to="learning.pretestpaperversion",
            ),
        ),
        migrations.AddField(
            model_name="pretestmaterialattachment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pretest_material_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pretestmaterialattachment",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="material_attachments",
                to="learning.pretestsubmission",
            ),
        ),
        migrations.AddIndex(
            model_name="pretestmaterialattachment",
            index=models.Index(
                fields=["submission", "question_id"],
                name="learning_pr_submiss_c14d1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pretestmaterialattachment",
            index=models.Index(
                fields=["student", "created_at"],
                name="learning_pr_student_0dddb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pretestmaterialattachment",
            index=models.Index(
                fields=["paper_version", "question_id"],
                name="learning_pr_paper_v_d0573c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pretestmaterialattachment",
            constraint=models.UniqueConstraint(
                fields=("material", "file_sha256"),
                name="uniq_pretest_material_attachment_hash",
            ),
        ),
    ]
