# Generated by Django 5.2.15 on 2026-07-22 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_unmapped_p3_records(apps, schema_editor):
    PretestQuestion = apps.get_model('learning', 'PretestQuestion')
    StudentLearningTargetStateVersion = apps.get_model(
        'learning', 'StudentLearningTargetStateVersion'
    )
    UnifiedAssessmentMaterial = apps.get_model('learning', 'UnifiedAssessmentMaterial')

    # Never infer a formal learning-target identity from legacy free text.
    PretestQuestion._base_manager.filter(learning_target_version__isnull=True).update(
        legacy_unmapped=True
    )
    StudentLearningTargetStateVersion._base_manager.filter(
        learning_target_version__isnull=True
    ).update(legacy_unmapped=True)
    UnifiedAssessmentMaterial._base_manager.filter(
        learning_target_version__isnull=True
    ).update(legacy_unmapped=True)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_classroomgroupcollaboration_storage_quota_mb'),
        ('learning', '0023_pretestmaterialattachment_and_more'),
        ('learning_analytics', '0034_learningtarget_learningtargetbackfillissue_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('entry_diagnostic', '学习起点诊断'), ('research_pretest', '教育实验前测'), ('research_posttest', '教育实验后测'), ('pilot', '诊断工具试测')], max_length=32)),
                ('batch_code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('open_at', models.DateTimeField(blank=True, null=True)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('closed', '已关闭')], db_index=True, default='draft', max_length=16)),
                ('content_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_diagnostic_administrations', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_administrations', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_diagnostic_administrations', to=settings.AUTH_USER_MODEL)),
                ('paper_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_administrations', to='learning.pretestpaperversion')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_diagnostic_administrations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_administrations', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_administrations', to='courses.subject')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAdministrationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_role', models.CharField(choices=[('experiment', '实验班'), ('control', '对照班'), ('unassigned', '未设置实验角色')], default='unassigned', max_length=16)),
                ('opportunity_status', models.CharField(choices=[('offered', '已提供评价机会'), ('not_offered', '未提供评价机会')], default='offered', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning.diagnosticadministration')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_administration_assignments', to='school.classgroup')),
            ],
            options={
                'ordering': ['administration_id', 'class_group_id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSubmissionBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(editable=False, max_length=64)),
                ('content_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_bindings', to='learning.diagnosticadministration')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_bindings', to='learning.diagnosticadministrationassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_submission_bindings', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_binding', to='learning.pretestsubmission')),
            ],
            options={
                'ordering': ['administration_id', 'student_id', 'attempt_no'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='pretestsubmission',
            name='uniq_pretest_submission_attempt',
        ),
        migrations.AddField(
            model_name='pretestquestion',
            name='learning_target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pretest_questions', to='learning_analytics.learningtargetversion'),
        ),
        migrations.AddField(
            model_name='pretestquestion',
            name='legacy_unmapped',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pretestsubmission',
            name='administration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning.diagnosticadministration'),
        ),
        migrations.AddField(
            model_name='pretestsubmission',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='pretestsubmission',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentlearningtargetstateversion',
            name='learning_target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_learning_states', to='learning_analytics.learningtargetversion'),
        ),
        migrations.AddField(
            model_name='studentlearningtargetstateversion',
            name='legacy_unmapped',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unifiedassessmentmaterial',
            name='learning_target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_materials', to='learning_analytics.learningtargetversion'),
        ),
        migrations.AlterField(
            model_name='unifiedassessmentmaterial',
            name='legacy_unmapped',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unifiedassessmentmaterial',
            name='material_status',
            field=models.CharField(choices=[('available', '材料可用'), ('missing', '材料缺失'), ('device_issue', '设备问题'), ('technical_issue', '技术问题'), ('not_offered', '未获得机会'), ('not_observed', '未观察到'), ('not_applicable', '不适用'), ('pending_review', '等待评价')], max_length=24),
        ),
        migrations.RunPython(mark_unmapped_p3_records, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='diagnosticadministration',
            index=models.Index(fields=['school', 'subject', 'status'], name='learning_di_school__f9b4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticadministration',
            index=models.Index(fields=['course', 'status'], name='learning_di_course__24592c_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticadministration',
            index=models.Index(fields=['purpose', 'status', 'open_at', 'close_at'], name='learning_di_purpose_27274c_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticadministration',
            constraint=models.UniqueConstraint(fields=('school', 'batch_code'), name='uniq_diagnostic_batch_per_school'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticadministration',
            constraint=models.CheckConstraint(condition=models.Q(('close_at__isnull', True), ('open_at__isnull', True), ('close_at__gt', models.F('open_at')), _connector='OR'), name='diagnostic_close_after_open'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticadministration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('closed_by__isnull', True), ('content_hash', ''), ('published_at__isnull', True), ('published_by__isnull', True), ('status', 'draft')), models.Q(('closed_at__isnull', True), ('closed_by__isnull', True), ('content_hash__gt', ''), ('published_at__isnull', False), ('published_by__isnull', False), ('status', 'published')), models.Q(('closed_at__isnull', False), ('closed_by__isnull', False), ('content_hash__gt', ''), ('published_at__isnull', False), ('published_by__isnull', False), ('status', 'closed')), _connector='OR'), name='diagnostic_lifecycle_fields_consistent'),
        ),
        migrations.AddIndex(
            model_name='diagnosticadministrationassignment',
            index=models.Index(fields=['class_group', 'opportunity_status'], name='learning_di_class_g_87325b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticadministrationassignment',
            index=models.Index(fields=['administration', 'cohort_role'], name='learning_di_adminis_e97d08_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticadministrationassignment',
            constraint=models.UniqueConstraint(fields=('administration', 'class_group'), name='uniq_diagnostic_assignment_class'),
        ),
        migrations.AddIndex(
            model_name='diagnosticsubmissionbinding',
            index=models.Index(fields=['administration', 'student'], name='learning_di_adminis_b1b543_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticsubmissionbinding',
            index=models.Index(fields=['assignment', 'created_at'], name='learning_di_assignm_abf1c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticsubmissionbinding',
            constraint=models.UniqueConstraint(fields=('administration', 'student', 'attempt_no'), name='uniq_diagnostic_student_attempt'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticsubmissionbinding',
            constraint=models.UniqueConstraint(fields=('administration', 'student', 'idempotency_key'), name='uniq_diagnostic_student_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticsubmissionbinding',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_no__gt', 0)), name='diagnostic_attempt_positive'),
        ),
        migrations.AddIndex(
            model_name='pretestsubmission',
            index=models.Index(fields=['administration', 'student'], name='learning_pr_adminis_5e8b2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='pretestsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('administration__isnull', True)), fields=('student', 'paper', 'attempt_no'), name='uniq_pretest_legacy_attempt'),
        ),
        migrations.AddConstraint(
            model_name='pretestsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('administration__isnull', False)), fields=('administration', 'student', 'attempt_no'), name='uniq_pretest_admin_attempt'),
        ),
        migrations.AddConstraint(
            model_name='pretestsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('administration__isnull', False), ('idempotency_key__gt', '')), fields=('administration', 'student', 'idempotency_key'), name='uniq_pretest_admin_idempotency'),
        ),
    ]
