# Generated by Django 5.2.15 on 2026-07-22 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_historical_rows_and_link_primary_targets(apps, schema_editor):
    LearningContentRecommendation = apps.get_model(
        'learning', 'LearningContentRecommendation'
    )
    LearningContentRecommendationTargetState = apps.get_model(
        'learning', 'LearningContentRecommendationTargetState'
    )

    # Preserve the old single-target evidence as the first member of the new
    # immutable multi-target relation.  New recommendations are populated by
    # the service from all target-level mastery results.
    links = [
        LearningContentRecommendationTargetState(
            recommendation_id=recommendation_id,
            target_state_id=target_state_id,
            sort_order=0,
        )
        for recommendation_id, target_state_id in (
            LearningContentRecommendation.objects.exclude(
                target_state__isnull=True
            ).values_list('id', 'target_state_id')
        )
    ]
    LearningContentRecommendationTargetState.objects.bulk_create(
        links, ignore_conflicts=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_classroomgroupcollaboration_storage_quota_mb'),
        ('learning', '0024_diagnosticadministration_and_more'),
        ('learning_analytics', '0034_learningtarget_learningtargetbackfillissue_and_more'),
        ('school', '0009_school_is_synthetic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContentRecommendationTargetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['recommendation_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentMasteryTargetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_status', models.CharField(choices=[('available', '可用'), ('insufficient', '数据不足'), ('not_comparable', '不可比较'), ('pending_grading', '等待评分')], max_length=24)),
                ('score_obtained', models.FloatField(default=0)),
                ('score_max', models.FloatField(default=0)),
                ('mastery_score', models.FloatField(blank=True, null=True)),
                ('measurement_error', models.FloatField(blank=True, null=True)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('answered_item_count', models.PositiveIntegerField(default=0)),
                ('evidence_coverage', models.FloatField(default=0)),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['snapshot_id', 'learning_target_version_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='learningsupportrecommendation',
            name='uniq_support_recommendation_target_state',
        ),
        migrations.AddField(
            model_name='learningsupportrecommendation',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learningsupportrecommendation',
            name='source_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='learningsupportrecommendation',
            name='source_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_recommendations', to='learning_analytics.studentlearningsummary'),
        ),
        migrations.AddField(
            model_name='learningsupportrecommendation',
            name='source_summary_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='learning_target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_items', to='learning_analytics.learningtargetversion'),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='legacy_unmapped',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionbankitemversion',
            name='learning_target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_item_versions', to='learning_analytics.learningtargetversion'),
        ),
        migrations.AddField(
            model_name='questionbankitemversion',
            name='legacy_unmapped',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentmasterysnapshot',
            name='legacy_unmapped',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testassessmentquestion',
            name='learning_target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_question_snapshots', to='learning_analytics.learningtargetversion'),
        ),
        migrations.AddField(
            model_name='testassessmentquestion',
            name='legacy_unmapped',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='learningcontentrecommendation',
            name='target_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_recommendations', to='learning.studentlearningtargetstateversion'),
        ),
        migrations.AlterField(
            model_name='learningsupportrecommendation',
            name='target_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_recommendations', to='learning.studentlearningtargetstateversion'),
        ),
        migrations.AlterField(
            model_name='stratificationdecision',
            name='rule_version',
            field=models.CharField(default='transparent-rules-v1', max_length=96),
        ),
        migrations.AlterField(
            model_name='studentmasterysnapshot',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mastery_snapshots', to='learning.testattempt'),
        ),
        migrations.AddConstraint(
            model_name='learningsupportrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('target_state__isnull', False)), fields=('target_state',), name='uniq_support_recommendation_target_state'),
        ),
        migrations.AddConstraint(
            model_name='studentmasterysnapshot',
            constraint=models.UniqueConstraint(fields=('attempt', 'source_hash'), name='uniq_mastery_attempt_source_hash'),
        ),
        migrations.AddField(
            model_name='learningcontentrecommendationtargetstate',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_state_links', to='learning.learningcontentrecommendation'),
        ),
        migrations.AddField(
            model_name='learningcontentrecommendationtargetstate',
            name='target_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_recommendation_links', to='learning.studentlearningtargetstateversion'),
        ),
        migrations.AddField(
            model_name='learningcontentrecommendation',
            name='target_states',
            field=models.ManyToManyField(related_name='content_recommendation_evidence', through='learning.LearningContentRecommendationTargetState', to='learning.studentlearningtargetstateversion'),
        ),
        migrations.RunPython(
            mark_historical_rows_and_link_primary_targets,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='studentmasterytargetresult',
            name='learning_target_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_mastery_results', to='learning_analytics.learningtargetversion'),
        ),
        migrations.AddField(
            model_name='studentmasterytargetresult',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_results', to='learning.studentmasterysnapshot'),
        ),
        migrations.AddConstraint(
            model_name='learningcontentrecommendationtargetstate',
            constraint=models.UniqueConstraint(fields=('recommendation', 'target_state'), name='uniq_content_recommendation_target_state'),
        ),
        migrations.AddConstraint(
            model_name='learningcontentrecommendationtargetstate',
            constraint=models.UniqueConstraint(fields=('recommendation', 'sort_order'), name='uniq_content_recommendation_target_order'),
        ),
        migrations.AddIndex(
            model_name='studentmasterytargetresult',
            index=models.Index(fields=['learning_target_version', 'data_status'], name='learning_st_learnin_94c182_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmasterytargetresult',
            index=models.Index(fields=['snapshot', 'data_status'], name='learning_st_snapsho_d38648_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentmasterytargetresult',
            constraint=models.UniqueConstraint(fields=('snapshot', 'learning_target_version'), name='uniq_mastery_snapshot_target_version'),
        ),
    ]
