from django.urls import path

from . import views

urlpatterns = [
    path("auth/csrf/", views.csrf_token_view, name="api_csrf"),
    path("auth/login/", views.login_view, name="api_login"),
    path("auth/logout/", views.logout_view, name="api_logout"),
    path("auth/me/", views.me_view, name="api_me"),
    path("super-admin/dashboard/", views.super_admin_dashboard, name="api_super_admin_dashboard"),
    path("super-admin/schools/", views.super_admin_schools, name="api_super_admin_schools"),
    path("super-admin/schools/bulk-disable/", views.super_admin_schools_bulk_disable, name="api_super_admin_schools_bulk_disable"),
    path("super-admin/schools/bulk-delete/", views.super_admin_schools_bulk_delete, name="api_super_admin_schools_bulk_delete"),
    path("super-admin/schools/<int:pk>/", views.super_admin_school_detail, name="api_super_admin_school_detail"),
    path("super-admin/school-admins/", views.super_admin_school_admins, name="api_super_admin_school_admins"),
    path(
        "super-admin/school-admins/bulk-disable/",
        views.super_admin_school_admins_bulk_disable,
        name="api_super_admin_school_admins_bulk_disable",
    ),
    path(
        "super-admin/school-admins/bulk-delete/",
        views.super_admin_school_admins_bulk_delete,
        name="api_super_admin_school_admins_bulk_delete",
    ),
    path(
        "super-admin/school-admins/<int:pk>/",
        views.super_admin_school_admin_detail,
        name="api_super_admin_school_admin_detail",
    ),
    path(
        "super-admin/school-admins/<int:pk>/active/",
        views.super_admin_school_admin_set_active,
        name="api_super_admin_school_admin_active",
    ),
    path(
        "super-admin/school-admins/<int:pk>/reset-password/",
        views.super_admin_school_admin_reset_password,
        name="api_super_admin_school_admin_reset_password",
    ),
    path("school-admin/dashboard/", views.school_admin_dashboard, name="api_school_admin_dashboard"),
    path("school-admin/teachers/", views.school_admin_teachers, name="api_school_admin_teachers"),
    path("school-admin/teachers/export/", views.school_admin_teachers_export, name="api_school_admin_teachers_export"),
    path("school-admin/teachers/template/", views.school_admin_teachers_template, name="api_school_admin_teachers_template"),
    path("school-admin/teachers/import/", views.school_admin_teachers_import, name="api_school_admin_teachers_import"),
    path("school-admin/teachers/bulk-disable/", views.school_admin_teachers_bulk_disable, name="api_school_admin_teachers_bulk_disable"),
    path("school-admin/teachers/bulk-delete/", views.school_admin_teachers_bulk_delete, name="api_school_admin_teachers_bulk_delete"),
    path("school-admin/teachers/<int:pk>/", views.school_admin_teacher_detail, name="api_school_admin_teacher_detail"),
    path("school-admin/teachers/<int:pk>/active/", views.school_admin_teacher_set_active, name="api_school_admin_teacher_active"),
    path(
        "school-admin/teachers/<int:pk>/reset-password/",
        views.school_admin_teacher_reset_password,
        name="api_school_admin_teacher_reset_password",
    ),
    path("school-admin/students/", views.school_admin_students, name="api_school_admin_students"),
    path("school-admin/students/export/", views.school_admin_students_export, name="api_school_admin_students_export"),
    path("school-admin/students/template/", views.school_admin_students_template, name="api_school_admin_students_template"),
    path("school-admin/students/import/", views.school_admin_students_import, name="api_school_admin_students_import"),
    path("school-admin/students/bulk-disable/", views.school_admin_students_bulk_disable, name="api_school_admin_students_bulk_disable"),
    path("school-admin/students/bulk-delete/", views.school_admin_students_bulk_delete, name="api_school_admin_students_bulk_delete"),
    path("school-admin/students/<int:pk>/", views.school_admin_student_detail, name="api_school_admin_student_detail"),
    path("school-admin/students/<int:pk>/active/", views.school_admin_student_set_active, name="api_school_admin_student_active"),
    path(
        "school-admin/students/<int:pk>/reset-password/",
        views.school_admin_student_reset_password,
        name="api_school_admin_student_reset_password",
    ),
    path("school-admin/classes/", views.school_admin_classes, name="api_school_admin_classes"),
    path("school-admin/classes/bulk-create/", views.school_admin_classes_bulk_create, name="api_school_admin_classes_bulk_create"),
    path("school-admin/classes/bulk-disable/", views.school_admin_classes_bulk_disable, name="api_school_admin_classes_bulk_disable"),
    path("school-admin/classes/bulk-delete/", views.school_admin_classes_bulk_delete, name="api_school_admin_classes_bulk_delete"),
    path("school-admin/classes/graduate/", views.school_admin_classes_graduate, name="api_school_admin_classes_graduate"),
    path("school-admin/classes/promote/", views.school_admin_classes_promote, name="api_school_admin_classes_promote"),
    path("school-admin/classes/<int:pk>/", views.school_admin_class_detail, name="api_school_admin_class_detail"),
    path("school-admin/subjects/", views.school_admin_subjects, name="api_school_admin_subjects"),
    path("school-admin/subjects/<int:pk>/", views.school_admin_subject_detail, name="api_school_admin_subject_detail"),
    path("school-admin/pretests/", views.school_admin_pretest_papers, name="api_school_admin_pretests"),
    path("school-admin/pretests/<int:pk>/", views.school_admin_pretest_paper_detail, name="api_school_admin_pretest_detail"),
    path(
        "school-admin/pretests/<int:pk>/publish/",
        views.school_admin_pretest_paper_publish,
        name="api_school_admin_pretest_publish",
    ),
    path(
        "school-admin/pretests/<int:pk>/archive/",
        views.school_admin_pretest_paper_archive,
        name="api_school_admin_pretest_archive",
    ),
    path(
        "school-admin/pretests/<int:paper_id>/questions/",
        views.school_admin_pretest_questions,
        name="api_school_admin_pretest_questions",
    ),
    path(
        "school-admin/pretests/<int:paper_id>/questions/<int:pk>/",
        views.school_admin_pretest_question_detail,
        name="api_school_admin_pretest_question_detail",
    ),
    path("school-admin/teaching/options/", views.school_admin_teaching_options, name="api_school_admin_teaching_options"),
    path("school-admin/teaching/export/", views.school_admin_teaching_export, name="api_school_admin_teaching_export"),
    path("school-admin/teaching/bulk-save/", views.school_admin_teaching_bulk_save, name="api_school_admin_teaching_bulk_save"),
    path("school-admin/teaching/", views.school_admin_teaching_assignments, name="api_school_admin_teaching"),
    path("school-admin/teaching/<int:pk>/", views.school_admin_teaching_assignment_detail, name="api_school_admin_teaching_detail"),
    path("teacher/dashboard/", views.teacher_dashboard, name="api_teacher_dashboard"),
    path("teacher/classes/", views.teacher_classes, name="api_teacher_classes"),
    path("teacher/ai-provider/", views.teacher_ai_provider, name="api_teacher_ai_provider"),
    path("teacher/ai-provider/test/", views.teacher_ai_provider_test, name="api_teacher_ai_provider_test"),
    path("teacher/students/", views.teacher_students, name="api_teacher_students"),
    path(
        "teacher/students/bulk-reset-password/",
        views.teacher_students_bulk_reset_password,
        name="api_teacher_students_bulk_reset_password",
    ),
    path(
        "teacher/students/<int:pk>/reset-password/",
        views.teacher_student_reset_password,
        name="api_teacher_student_reset_password",
    ),
    path("teacher/course-options/", views.teacher_course_options, name="api_teacher_course_options"),
    path("teacher/classroom/options/", views.teacher_course_options, name="api_teacher_classroom_options"),
    path("resources/<int:pk>/office-config/", views.resource_office_config, name="api_resource_office_config"),
    path("resources/<int:pk>/office-callback/", views.resource_office_callback, name="api_resource_office_callback"),
    path("teacher/resources/", views.teacher_resources, name="api_teacher_resources"),
    path("teacher/resources/<int:pk>/", views.teacher_resource_detail, name="api_teacher_resource_detail"),
    path("teacher/courses/", views.teacher_courses, name="api_teacher_courses"),
    path("teacher/courses/<int:pk>/", views.teacher_course_detail, name="api_teacher_course_detail"),
    path("teacher/courses/<int:pk>/cover/", views.teacher_course_cover, name="api_teacher_course_cover"),
    path("teacher/courses/<int:pk>/publish/", views.teacher_course_publish, name="api_teacher_course_publish"),
    path("teacher/courses/<int:pk>/archive/", views.teacher_course_archive, name="api_teacher_course_archive"),
    path("teacher/courses/<int:pk>/classes/", views.teacher_course_classes, name="api_teacher_course_classes"),
    path("teacher/courses/<int:course_id>/lessons/", views.teacher_course_lessons, name="api_teacher_course_lessons"),
    path("teacher/lessons/<int:pk>/", views.teacher_lesson_detail, name="api_teacher_lesson_detail"),
    path("teacher/lessons/<int:pk>/publish/", views.teacher_lesson_publish, name="api_teacher_lesson_publish"),
    path("teacher/lessons/<int:pk>/archive/", views.teacher_lesson_archive, name="api_teacher_lesson_archive"),
    path("teacher/lessons/<int:lesson_id>/steps/", views.teacher_lesson_steps, name="api_teacher_lesson_steps"),
    path(
        "teacher/lessons/<int:lesson_id>/steps/reorder/",
        views.teacher_lesson_steps_reorder,
        name="api_teacher_lesson_steps_reorder",
    ),
    path("teacher/lesson-steps/<int:pk>/", views.teacher_lesson_step_detail, name="api_teacher_lesson_step_detail"),
    path(
        "teacher/lesson-steps/ai-generate-questions/",
        views.teacher_lesson_step_ai_generate_questions,
        name="api_teacher_lesson_step_ai_generate_questions",
    ),
    path("teacher/classroom/sessions/", views.teacher_classroom_sessions, name="api_teacher_classroom_sessions"),
    path("teacher/classroom/sessions/<int:pk>/", views.teacher_classroom_session_detail, name="api_teacher_classroom_session_detail"),
    path("teacher/classroom/sessions/<int:pk>/start/", views.teacher_classroom_session_start, name="api_teacher_classroom_start"),
    path("teacher/classroom/sessions/<int:pk>/restart/", views.teacher_classroom_session_restart, name="api_teacher_classroom_restart"),
    path("teacher/classroom/sessions/<int:pk>/finish/", views.teacher_classroom_session_finish, name="api_teacher_classroom_finish"),
    path("teacher/classroom/sessions/<int:pk>/step/open/", views.teacher_classroom_step_open, name="api_teacher_classroom_step_open"),
    path("teacher/classroom/sessions/<int:pk>/step/lock/", views.teacher_classroom_step_lock, name="api_teacher_classroom_step_lock"),
    path("teacher/classroom/sessions/<int:pk>/step/close/", views.teacher_classroom_step_close, name="api_teacher_classroom_step_close"),
    path(
        "teacher/classroom/sessions/<int:session_id>/activities/",
        views.teacher_classroom_activities,
        name="api_teacher_classroom_activities",
    ),
    path("teacher/classroom/activities/<int:pk>/", views.teacher_classroom_activity_detail, name="api_teacher_classroom_activity_detail"),
    path("teacher/classroom/activities/<int:pk>/open/", views.teacher_classroom_activity_open, name="api_teacher_classroom_activity_open"),
    path("teacher/classroom/activities/<int:pk>/close/", views.teacher_classroom_activity_close, name="api_teacher_classroom_activity_close"),
    path("teacher/notices/", views.teacher_notices, name="api_teacher_notices"),
    path("teacher/notices/<int:pk>/", views.teacher_notice_detail, name="api_teacher_notice_detail"),
    path("teacher/notices/<int:pk>/publish/", views.teacher_notice_publish, name="api_teacher_notice_publish"),
    path("teacher/notices/<int:pk>/archive/", views.teacher_notice_archive, name="api_teacher_notice_archive"),
    path("teacher/feedback/", views.teacher_feedback_items, name="api_teacher_feedback"),
    path("teacher/feedback/<int:pk>/", views.teacher_feedback_detail, name="api_teacher_feedback_detail"),
    path("teacher/feedback/<int:pk>/reply/", views.teacher_feedback_reply, name="api_teacher_feedback_reply"),
    path("teacher/feedback/<int:pk>/close/", views.teacher_feedback_close, name="api_teacher_feedback_close"),
    path("student/me/", views.student_me, name="api_student_me"),
    path("student/dashboard/", views.student_dashboard, name="api_student_dashboard"),
    path("student/onboarding/", views.student_onboarding, name="api_student_onboarding"),
    path("student/onboarding/classes/", views.student_onboarding_classes, name="api_student_onboarding_classes"),
    path("student/onboarding/password/", views.student_onboarding_password, name="api_student_onboarding_password"),
    path("student/onboarding/class/", views.student_onboarding_class, name="api_student_onboarding_class"),
    path("student/pretests/required/", views.student_pretests_required, name="api_student_pretests_required"),
    path("student/pretests/<int:subject_id>/", views.student_pretests_for_subject, name="api_student_pretests_subject"),
    path("student/pretests/papers/<int:paper_id>/", views.student_pretest_paper, name="api_student_pretest_paper"),
    path("student/courses/", views.student_courses, name="api_student_courses"),
    path("student/courses/<int:pk>/", views.student_course_detail, name="api_student_course_detail"),
    path("student/courses/<int:course_id>/lessons/", views.student_course_lessons, name="api_student_course_lessons"),
    path("student/lessons/<int:lesson_id>/workspace/", views.student_lesson_workspace, name="api_student_lesson_workspace"),
    path("student/lessons/<int:lesson_id>/enter/", views.student_lesson_enter, name="api_student_lesson_enter"),
    path("student/lesson-steps/<int:step_id>/enter/", views.student_lesson_step_enter, name="api_student_lesson_step_enter"),
    path("student/lesson-steps/<int:step_id>/complete/", views.student_lesson_step_complete, name="api_student_lesson_step_complete"),
    path("student/lesson-steps/<int:step_id>/answer/", views.student_lesson_step_answer, name="api_student_lesson_step_answer"),
    path("student/classroom/current/", views.student_current_classroom, name="api_student_current_classroom"),
    path("student/classroom/<int:pk>/", views.student_classroom_detail, name="api_student_classroom_detail"),
    path("student/notices/", views.student_notices, name="api_student_notices"),
    path("student/feedback/", views.student_feedback, name="api_student_feedback"),
    path("student/feedback/<int:pk>/", views.student_feedback_detail, name="api_student_feedback_detail"),
]
