from django.urls import include, path

from . import assessment_views, chat_views, protected_files, views

urlpatterns = [
    path("", include("api.analytics.urls")),
    path(
        "files/courses/<int:pk>/cover/",
        protected_files.course_cover,
        name="api_protected_course_cover",
    ),
    path(
        "files/resources/<int:pk>/attachment/",
        protected_files.resource_attachment,
        name="api_protected_resource_attachment",
    ),
    path(
        "files/resources/<int:pk>/cover/",
        protected_files.resource_cover,
        name="api_protected_resource_cover",
    ),
    path(
        "files/resource-files/<int:pk>/",
        protected_files.resource_extra_file,
        name="api_protected_resource_extra_file",
    ),
    path(
        "files/student-work/<int:pk>/",
        protected_files.student_work_file,
        name="api_protected_student_work",
    ),
    path(
        "files/classroom-group-files/<int:pk>/",
        protected_files.classroom_group_file,
        name="api_protected_classroom_group_file",
    ),
    path(
        "files/classroom-groups/<int:pk>/document/",
        protected_files.classroom_group_document,
        name="api_protected_classroom_group_document",
    ),
    path("auth/csrf/", views.csrf_token_view, name="api_csrf"),
    path("auth/login/", views.login_view, name="api_login"),
    path("auth/logout/", views.logout_view, name="api_logout"),
    path("auth/me/", views.me_view, name="api_me"),
    path(
        "super-admin/dashboard/",
        views.super_admin_dashboard,
        name="api_super_admin_dashboard",
    ),
    path(
        "super-admin/schools/",
        views.super_admin_schools,
        name="api_super_admin_schools",
    ),
    path(
        "super-admin/schools/bulk-disable/",
        views.super_admin_schools_bulk_disable,
        name="api_super_admin_schools_bulk_disable",
    ),
    path(
        "super-admin/schools/bulk-delete/",
        views.super_admin_schools_bulk_delete,
        name="api_super_admin_schools_bulk_delete",
    ),
    path(
        "super-admin/schools/<int:pk>/",
        views.super_admin_school_detail,
        name="api_super_admin_school_detail",
    ),
    path(
        "super-admin/school-admins/",
        views.super_admin_school_admins,
        name="api_super_admin_school_admins",
    ),
    path(
        "super-admin/school-admins/bulk-disable/",
        views.super_admin_school_admins_bulk_disable,
        name="api_super_admin_school_admins_bulk_disable",
    ),
    path(
        "super-admin/school-admins/bulk-delete/",
        views.super_admin_school_admins_bulk_delete,
        name="api_super_admin_school_admins_bulk_delete",
    ),
    path(
        "super-admin/school-admins/<int:pk>/",
        views.super_admin_school_admin_detail,
        name="api_super_admin_school_admin_detail",
    ),
    path(
        "super-admin/school-admins/<int:pk>/active/",
        views.super_admin_school_admin_set_active,
        name="api_super_admin_school_admin_active",
    ),
    path(
        "super-admin/school-admins/<int:pk>/reset-password/",
        views.super_admin_school_admin_reset_password,
        name="api_super_admin_school_admin_reset_password",
    ),
    path(
        "school-admin/dashboard/",
        views.school_admin_dashboard,
        name="api_school_admin_dashboard",
    ),
    path(
        "school-admin/teachers/",
        views.school_admin_teachers,
        name="api_school_admin_teachers",
    ),
    path(
        "school-admin/teachers/export/",
        views.school_admin_teachers_export,
        name="api_school_admin_teachers_export",
    ),
    path(
        "school-admin/teachers/template/",
        views.school_admin_teachers_template,
        name="api_school_admin_teachers_template",
    ),
    path(
        "school-admin/teachers/import/",
        views.school_admin_teachers_import,
        name="api_school_admin_teachers_import",
    ),
    path(
        "school-admin/teachers/bulk-disable/",
        views.school_admin_teachers_bulk_disable,
        name="api_school_admin_teachers_bulk_disable",
    ),
    path(
        "school-admin/teachers/bulk-delete/",
        views.school_admin_teachers_bulk_delete,
        name="api_school_admin_teachers_bulk_delete",
    ),
    path(
        "school-admin/teachers/<int:pk>/",
        views.school_admin_teacher_detail,
        name="api_school_admin_teacher_detail",
    ),
    path(
        "school-admin/teachers/<int:pk>/active/",
        views.school_admin_teacher_set_active,
        name="api_school_admin_teacher_active",
    ),
    path(
        "school-admin/teachers/<int:pk>/reset-password/",
        views.school_admin_teacher_reset_password,
        name="api_school_admin_teacher_reset_password",
    ),
    path(
        "school-admin/students/",
        views.school_admin_students,
        name="api_school_admin_students",
    ),
    path(
        "school-admin/students/export/",
        views.school_admin_students_export,
        name="api_school_admin_students_export",
    ),
    path(
        "school-admin/students/template/",
        views.school_admin_students_template,
        name="api_school_admin_students_template",
    ),
    path(
        "school-admin/students/import/",
        views.school_admin_students_import,
        name="api_school_admin_students_import",
    ),
    path(
        "school-admin/students/bulk-disable/",
        views.school_admin_students_bulk_disable,
        name="api_school_admin_students_bulk_disable",
    ),
    path(
        "school-admin/students/bulk-delete/",
        views.school_admin_students_bulk_delete,
        name="api_school_admin_students_bulk_delete",
    ),
    path(
        "school-admin/students/<int:pk>/",
        views.school_admin_student_detail,
        name="api_school_admin_student_detail",
    ),
    path(
        "school-admin/students/<int:pk>/active/",
        views.school_admin_student_set_active,
        name="api_school_admin_student_active",
    ),
    path(
        "school-admin/students/<int:pk>/reset-password/",
        views.school_admin_student_reset_password,
        name="api_school_admin_student_reset_password",
    ),
    path(
        "school-admin/classes/",
        views.school_admin_classes,
        name="api_school_admin_classes",
    ),
    path(
        "school-admin/classes/bulk-create/",
        views.school_admin_classes_bulk_create,
        name="api_school_admin_classes_bulk_create",
    ),
    path(
        "school-admin/classes/bulk-disable/",
        views.school_admin_classes_bulk_disable,
        name="api_school_admin_classes_bulk_disable",
    ),
    path(
        "school-admin/classes/bulk-delete/",
        views.school_admin_classes_bulk_delete,
        name="api_school_admin_classes_bulk_delete",
    ),
    path(
        "school-admin/classes/graduate/",
        views.school_admin_classes_graduate,
        name="api_school_admin_classes_graduate",
    ),
    path(
        "school-admin/classes/promote/",
        views.school_admin_classes_promote,
        name="api_school_admin_classes_promote",
    ),
    path(
        "school-admin/classes/<int:pk>/",
        views.school_admin_class_detail,
        name="api_school_admin_class_detail",
    ),
    path(
        "school-admin/subjects/",
        views.school_admin_subjects,
        name="api_school_admin_subjects",
    ),
    path(
        "school-admin/subjects/<int:pk>/",
        views.school_admin_subject_detail,
        name="api_school_admin_subject_detail",
    ),
    path(
        "school-admin/pretests/",
        views.school_admin_pretest_papers,
        name="api_school_admin_pretests",
    ),
    path(
        "school-admin/pretests/<int:pk>/",
        views.school_admin_pretest_paper_detail,
        name="api_school_admin_pretest_detail",
    ),
    path(
        "school-admin/pretests/<int:pk>/publish/",
        views.school_admin_pretest_paper_publish,
        name="api_school_admin_pretest_publish",
    ),
    path(
        "school-admin/pretests/<int:pk>/archive/",
        views.school_admin_pretest_paper_archive,
        name="api_school_admin_pretest_archive",
    ),
    path(
        "school-admin/pretests/<int:paper_id>/questions/",
        views.school_admin_pretest_questions,
        name="api_school_admin_pretest_questions",
    ),
    path(
        "school-admin/pretests/<int:paper_id>/questions/<int:pk>/",
        views.school_admin_pretest_question_detail,
        name="api_school_admin_pretest_question_detail",
    ),
    path(
        "school-admin/teaching/options/",
        views.school_admin_teaching_options,
        name="api_school_admin_teaching_options",
    ),
    path(
        "school-admin/teaching/export/",
        views.school_admin_teaching_export,
        name="api_school_admin_teaching_export",
    ),
    path(
        "school-admin/teaching/bulk-save/",
        views.school_admin_teaching_bulk_save,
        name="api_school_admin_teaching_bulk_save",
    ),
    path(
        "school-admin/teaching/",
        views.school_admin_teaching_assignments,
        name="api_school_admin_teaching",
    ),
    path(
        "school-admin/teaching/<int:pk>/",
        views.school_admin_teaching_assignment_detail,
        name="api_school_admin_teaching_detail",
    ),
    path(
        "school-admin/resource-reviews/",
        views.school_admin_resource_reviews,
        name="api_school_admin_resource_reviews",
    ),
    path(
        "school-admin/resource-reviews/<int:pk>/",
        views.school_admin_resource_reviews,
        name="api_school_admin_resource_review_detail",
    ),
    path(
        "school-admin/question-reviews/",
        assessment_views.school_admin_question_reviews,
        name="api_school_admin_question_reviews",
    ),
    path(
        "school-admin/question-reviews/export/",
        assessment_views.school_admin_question_reviews_export,
        name="api_school_admin_question_reviews_export",
    ),
    path(
        "school-admin/question-reviews/<int:pk>/",
        assessment_views.school_admin_question_review_detail,
        name="api_school_admin_question_review_detail",
    ),
    path(
        "school-admin/question-reviews/<int:pk>/action/",
        assessment_views.school_admin_question_review_action,
        name="api_school_admin_question_review_action",
    ),
    path(
        "school-admin/common-question-sets/",
        assessment_views.school_admin_common_question_sets,
        name="api_school_admin_common_question_sets",
    ),
    path(
        "school-admin/common-question-sets/export/",
        assessment_views.school_admin_common_question_sets_export,
        name="api_school_admin_common_question_sets_export",
    ),
    path(
        "school-admin/common-question-sets/<int:pk>/archive/",
        assessment_views.school_admin_common_question_set_archive,
        name="api_school_admin_common_question_set_archive",
    ),
    path("teacher/dashboard/", views.teacher_dashboard, name="api_teacher_dashboard"),
    path("teacher/classes/", views.teacher_classes, name="api_teacher_classes"),
    path(
        "teacher/ai-provider/",
        views.teacher_ai_provider,
        name="api_teacher_ai_provider",
    ),
    path(
        "teacher/ai-provider/test/",
        views.teacher_ai_provider_test,
        name="api_teacher_ai_provider_test",
    ),
    path("teacher/students/", views.teacher_students, name="api_teacher_students"),
    path(
        "teacher/students/bulk-reset-password/",
        views.teacher_students_bulk_reset_password,
        name="api_teacher_students_bulk_reset_password",
    ),
    path(
        "teacher/students/<int:pk>/reset-password/",
        views.teacher_student_reset_password,
        name="api_teacher_student_reset_password",
    ),
    path(
        "teacher/course-options/",
        views.teacher_course_options,
        name="api_teacher_course_options",
    ),
    path(
        "teacher/classroom/options/",
        views.teacher_course_options,
        name="api_teacher_classroom_options",
    ),
    path(
        "resources/<int:pk>/office-config/",
        views.resource_office_config,
        name="api_resource_office_config",
    ),
    path(
        "resources/<int:pk>/office-callback/",
        views.resource_office_callback,
        name="api_resource_office_callback",
    ),
    path("teacher/resources/", views.teacher_resources, name="api_teacher_resources"),
    path(
        "teacher/resources/<int:pk>/",
        views.teacher_resource_detail,
        name="api_teacher_resource_detail",
    ),
    path(
        "teacher/resources/<int:pk>/files/<int:file_id>/",
        views.teacher_resource_extra_file,
        name="api_teacher_resource_extra_file",
    ),
    path(
        "teacher/assessment-options/",
        assessment_views.teacher_assessment_options,
        name="api_teacher_assessment_options",
    ),
    path(
        "teacher/question-bank/",
        assessment_views.teacher_question_bank,
        name="api_teacher_question_bank",
    ),
    path(
        "teacher/question-bank/template/",
        assessment_views.teacher_question_bank_template,
        name="api_teacher_question_bank_template",
    ),
    path(
        "teacher/question-bank/export/",
        assessment_views.teacher_question_bank_export,
        name="api_teacher_question_bank_export",
    ),
    path(
        "teacher/question-bank/import/",
        assessment_views.teacher_question_bank_import,
        name="api_teacher_question_bank_import",
    ),
    path(
        "teacher/question-bank/ai-generate/",
        assessment_views.teacher_question_bank_ai_generate,
        name="api_teacher_question_bank_ai_generate",
    ),
    path(
        "teacher/question-bank/ai-confirm/",
        assessment_views.teacher_question_bank_ai_confirm,
        name="api_teacher_question_bank_ai_confirm",
    ),
    path(
        "teacher/question-bank/<int:pk>/",
        assessment_views.teacher_question_bank_detail,
        name="api_teacher_question_bank_detail",
    ),
    path(
        "teacher/question-bank/<int:pk>/action/",
        assessment_views.teacher_question_bank_action,
        name="api_teacher_question_bank_action",
    ),
    path(
        "teacher/assessments/",
        assessment_views.teacher_assessments,
        name="api_teacher_assessments",
    ),
    path(
        "teacher/assessments/<int:pk>/",
        assessment_views.teacher_assessment_detail,
        name="api_teacher_assessment_detail",
    ),
    path(
        "teacher/assessments/<int:pk>/questions/",
        assessment_views.teacher_assessment_questions,
        name="api_teacher_assessment_questions",
    ),
    path(
        "teacher/assessments/<int:pk>/publish/",
        assessment_views.teacher_assessment_publish,
        name="api_teacher_assessment_publish",
    ),
    path(
        "teacher/assessments/<int:pk>/open/",
        assessment_views.teacher_assessment_open,
        name="api_teacher_assessment_open",
    ),
    path(
        "teacher/assessments/<int:pk>/close/",
        assessment_views.teacher_assessment_close,
        name="api_teacher_assessment_close",
    ),
    path(
        "teacher/assessments/<int:pk>/results/",
        assessment_views.teacher_assessment_results,
        name="api_teacher_assessment_results",
    ),
    path(
        "teacher/assessments/<int:pk>/results/export/",
        assessment_views.teacher_assessment_results_export,
        name="api_teacher_assessment_results_export",
    ),
    path(
        "teacher/test-attempts/<int:attempt_id>/grade/",
        assessment_views.teacher_attempt_grade,
        name="api_teacher_attempt_grade",
    ),
    path("teacher/courses/", views.teacher_courses, name="api_teacher_courses"),
    path(
        "teacher/courses/<int:pk>/",
        views.teacher_course_detail,
        name="api_teacher_course_detail",
    ),
    path(
        "teacher/courses/<int:pk>/cover/",
        views.teacher_course_cover,
        name="api_teacher_course_cover",
    ),
    path(
        "teacher/courses/<int:pk>/publish/",
        views.teacher_course_publish,
        name="api_teacher_course_publish",
    ),
    path(
        "teacher/courses/<int:pk>/archive/",
        views.teacher_course_archive,
        name="api_teacher_course_archive",
    ),
    path(
        "teacher/courses/<int:pk>/classes/",
        views.teacher_course_classes,
        name="api_teacher_course_classes",
    ),
    path(
        "teacher/courses/<int:pk>/evaluation/",
        views.teacher_course_evaluation,
        name="api_teacher_course_evaluation",
    ),
    path(
        "teacher/courses/<int:pk>/evaluation/ai-generate/",
        views.teacher_course_evaluation_ai_generate,
        name="api_teacher_course_evaluation_ai_generate",
    ),
    path(
        "teacher/courses/<int:pk>/evaluation/teacher-submit/",
        views.teacher_course_evaluation_submit,
        name="api_teacher_course_evaluation_submit",
    ),
    path(
        "teacher/courses/<int:course_id>/lessons/",
        views.teacher_course_lessons,
        name="api_teacher_course_lessons",
    ),
    path(
        "teacher/lessons/<int:pk>/",
        views.teacher_lesson_detail,
        name="api_teacher_lesson_detail",
    ),
    path(
        "teacher/lessons/<int:pk>/publish/",
        views.teacher_lesson_publish,
        name="api_teacher_lesson_publish",
    ),
    path(
        "teacher/lessons/<int:pk>/archive/",
        views.teacher_lesson_archive,
        name="api_teacher_lesson_archive",
    ),
    path(
        "teacher/lessons/<int:lesson_id>/steps/",
        views.teacher_lesson_steps,
        name="api_teacher_lesson_steps",
    ),
    path(
        "teacher/lessons/<int:lesson_id>/steps/reorder/",
        views.teacher_lesson_steps_reorder,
        name="api_teacher_lesson_steps_reorder",
    ),
    path(
        "teacher/lesson-steps/<int:pk>/",
        views.teacher_lesson_step_detail,
        name="api_teacher_lesson_step_detail",
    ),
    path(
        "teacher/lesson-steps/ai-generate-questions/",
        views.teacher_lesson_step_ai_generate_questions,
        name="api_teacher_lesson_step_ai_generate_questions",
    ),
    path(
        "teacher/lessons/<int:lesson_id>/learning-pages/",
        views.teacher_lesson_learning_web_pages,
        name="api_teacher_lesson_learning_web_pages",
    ),
    path(
        "teacher/learning-pages/<int:pk>/",
        views.teacher_learning_web_page_detail,
        name="api_teacher_learning_web_page_detail",
    ),
    path(
        "teacher/learning-pages/<int:pk>/revise/",
        views.teacher_learning_web_page_revise,
        name="api_teacher_learning_web_page_revise",
    ),
    path(
        "teacher/learning-pages/<int:pk>/responses/",
        views.teacher_learning_web_page_responses,
        name="api_teacher_learning_web_page_responses",
    ),
    path(
        "teacher/classroom/sessions/",
        views.teacher_classroom_sessions,
        name="api_teacher_classroom_sessions",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/",
        views.teacher_classroom_session_detail,
        name="api_teacher_classroom_session_detail",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/start/",
        views.teacher_classroom_session_start,
        name="api_teacher_classroom_start",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/restart/",
        views.teacher_classroom_session_restart,
        name="api_teacher_classroom_restart",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/finish/",
        views.teacher_classroom_session_finish,
        name="api_teacher_classroom_finish",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/chat/",
        chat_views.teacher_chat_context,
        name="api_teacher_chat_context",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/chat/settings/",
        chat_views.teacher_chat_settings,
        name="api_teacher_chat_settings",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/chat/messages/",
        chat_views.teacher_chat_messages,
        name="api_teacher_chat_messages",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/chat/read/",
        chat_views.teacher_chat_read,
        name="api_teacher_chat_read",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/chat/moderation/",
        chat_views.teacher_chat_moderation,
        name="api_teacher_chat_moderation",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/chat/messages/<int:message_id>/moderate/",
        chat_views.teacher_chat_moderate,
        name="api_teacher_chat_moderate",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/step/open/",
        views.teacher_classroom_step_open,
        name="api_teacher_classroom_step_open",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/step/lock/",
        views.teacher_classroom_step_lock,
        name="api_teacher_classroom_step_lock",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/step/close/",
        views.teacher_classroom_step_close,
        name="api_teacher_classroom_step_close",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/step-progress/",
        views.teacher_classroom_step_progress,
        name="api_teacher_classroom_step_progress",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/group-collaboration/",
        views.teacher_classroom_group_collaboration,
        name="api_teacher_classroom_group_collaboration",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/group-collaboration/setup/",
        views.teacher_classroom_group_collaboration_setup,
        name="api_teacher_classroom_group_collaboration_setup",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/group-collaboration/close/",
        views.teacher_classroom_group_collaboration_close,
        name="api_teacher_classroom_group_collaboration_close",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/groups/<int:group_id>/files/",
        views.teacher_classroom_group_files,
        name="api_teacher_classroom_group_files",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/evaluation/",
        views.teacher_classroom_evaluation,
        name="api_teacher_classroom_evaluation",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/evaluation/ai-generate/",
        views.teacher_classroom_evaluation_ai_generate,
        name="api_teacher_classroom_evaluation_ai_generate",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/evaluation/teacher-submit/",
        views.teacher_classroom_evaluation_submit,
        name="api_teacher_classroom_evaluation_submit",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/attachments/<int:attachment_id>/score/",
        views.teacher_classroom_attachment_score,
        name="api_teacher_classroom_attachment_score",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/command/",
        views.teacher_classroom_command,
        name="api_teacher_classroom_command",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/attendance/<int:activity_id>/",
        views.teacher_classroom_attendance,
        name="api_teacher_classroom_attendance",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/attendance/<int:activity_id>/mark/",
        views.teacher_classroom_attendance_mark,
        name="api_teacher_classroom_attendance_mark",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/quick-answer/<int:activity_id>/",
        views.teacher_classroom_quick_answer,
        name="api_teacher_classroom_quick_answer",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/quick-answer/<int:activity_id>/score/",
        views.teacher_classroom_quick_answer_score,
        name="api_teacher_classroom_quick_answer_score",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/random-pick/preview/",
        views.teacher_classroom_random_pick_preview,
        name="api_teacher_classroom_random_pick_preview",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/random-pick/<int:activity_id>/",
        views.teacher_classroom_random_pick,
        name="api_teacher_classroom_random_pick",
    ),
    path(
        "teacher/classroom/sessions/<int:pk>/random-pick/<int:activity_id>/score/",
        views.teacher_classroom_random_pick_score,
        name="api_teacher_classroom_random_pick_score",
    ),
    path(
        "teacher/classroom/sessions/<int:session_id>/activities/",
        views.teacher_classroom_activities,
        name="api_teacher_classroom_activities",
    ),
    path(
        "teacher/classroom/activities/<int:pk>/",
        views.teacher_classroom_activity_detail,
        name="api_teacher_classroom_activity_detail",
    ),
    path(
        "teacher/classroom/activities/<int:pk>/open/",
        views.teacher_classroom_activity_open,
        name="api_teacher_classroom_activity_open",
    ),
    path(
        "teacher/classroom/activities/<int:pk>/close/",
        views.teacher_classroom_activity_close,
        name="api_teacher_classroom_activity_close",
    ),
    path("teacher/notices/", views.teacher_notices, name="api_teacher_notices"),
    path(
        "teacher/notices/<int:pk>/",
        views.teacher_notice_detail,
        name="api_teacher_notice_detail",
    ),
    path(
        "teacher/notices/<int:pk>/publish/",
        views.teacher_notice_publish,
        name="api_teacher_notice_publish",
    ),
    path(
        "teacher/notices/<int:pk>/archive/",
        views.teacher_notice_archive,
        name="api_teacher_notice_archive",
    ),
    path(
        "teacher/feedback/", views.teacher_feedback_items, name="api_teacher_feedback"
    ),
    path(
        "teacher/feedback/<int:pk>/",
        views.teacher_feedback_detail,
        name="api_teacher_feedback_detail",
    ),
    path(
        "teacher/feedback/<int:pk>/reply/",
        views.teacher_feedback_reply,
        name="api_teacher_feedback_reply",
    ),
    path(
        "teacher/feedback/<int:pk>/close/",
        views.teacher_feedback_close,
        name="api_teacher_feedback_close",
    ),
    path("student/me/", views.student_me, name="api_student_me"),
    path("student/dashboard/", views.student_dashboard, name="api_student_dashboard"),
    path(
        "student/profile/",
        views.student_profile_archive,
        name="api_student_profile_archive",
    ),
    path(
        "student/onboarding/", views.student_onboarding, name="api_student_onboarding"
    ),
    path(
        "student/onboarding/classes/",
        views.student_onboarding_classes,
        name="api_student_onboarding_classes",
    ),
    path(
        "student/onboarding/password/",
        views.student_onboarding_password,
        name="api_student_onboarding_password",
    ),
    path(
        "student/onboarding/class/",
        views.student_onboarding_class,
        name="api_student_onboarding_class",
    ),
    path(
        "student/pretests/required/",
        views.student_pretests_required,
        name="api_student_pretests_required",
    ),
    path(
        "student/pretests/<int:subject_id>/",
        views.student_pretests_for_subject,
        name="api_student_pretests_subject",
    ),
    path(
        "student/pretests/papers/<int:paper_id>/",
        views.student_pretest_paper,
        name="api_student_pretest_paper",
    ),
    path("student/resources/", views.student_resources, name="api_student_resources"),
    path(
        "student/resources/<int:pk>/",
        views.student_resource_detail,
        name="api_student_resource_detail",
    ),
    path("student/courses/", views.student_courses, name="api_student_courses"),
    path(
        "student/courses/<int:pk>/",
        views.student_course_detail,
        name="api_student_course_detail",
    ),
    path(
        "student/courses/<int:course_id>/lessons/",
        views.student_course_lessons,
        name="api_student_course_lessons",
    ),
    path(
        "student/lessons/<int:lesson_id>/workspace/",
        views.student_lesson_workspace,
        name="api_student_lesson_workspace",
    ),
    path(
        "student/lessons/<int:lesson_id>/enter/",
        views.student_lesson_enter,
        name="api_student_lesson_enter",
    ),
    path(
        "student/lesson-steps/<int:step_id>/enter/",
        views.student_lesson_step_enter,
        name="api_student_lesson_step_enter",
    ),
    path(
        "student/lesson-steps/<int:step_id>/complete/",
        views.student_lesson_step_complete,
        name="api_student_lesson_step_complete",
    ),
    path(
        "student/lesson-steps/<int:step_id>/answer/",
        views.student_lesson_step_answer,
        name="api_student_lesson_step_answer",
    ),
    path(
        "student/lesson-steps/<int:step_id>/attachments/",
        views.student_lesson_step_attachment,
        name="api_student_lesson_step_attachment",
    ),
    path(
        "learning-pages/<int:pk>/",
        views.learning_web_page_view,
        name="api_learning_web_page_view",
    ),
    path(
        "student/learning-pages/<int:pk>/blocks/viewed/",
        views.student_learning_web_page_block_viewed,
        name="api_student_learning_web_page_block_viewed",
    ),
    path(
        "student/learning-pages/<int:pk>/submit/",
        views.student_learning_web_page_submit,
        name="api_student_learning_web_page_submit",
    ),
    path(
        "student/classroom/current/",
        views.student_current_classroom,
        name="api_student_current_classroom",
    ),
    path(
        "student/classroom/<int:pk>/",
        views.student_classroom_detail,
        name="api_student_classroom_detail",
    ),
    path(
        "student/classroom/<int:pk>/resources/<int:resource_id>/opened/",
        views.student_classroom_resource_opened,
        name="api_student_classroom_resource_opened",
    ),
    path(
        "student/classroom/<int:pk>/resources/<int:resource_id>/video-progress/",
        views.student_classroom_video_progress,
        name="api_student_classroom_video_progress",
    ),
    path(
        "student/classroom/<int:pk>/resources/<int:resource_id>/document-progress/",
        views.student_classroom_document_progress,
        name="api_student_classroom_document_progress",
    ),
    path(
        "student/classroom/<int:pk>/chat/",
        chat_views.student_chat_context,
        name="api_student_chat_context",
    ),
    path(
        "student/classroom/<int:pk>/chat/messages/",
        chat_views.student_chat_messages,
        name="api_student_chat_messages",
    ),
    path(
        "student/classroom/<int:pk>/chat/read/",
        chat_views.student_chat_read,
        name="api_student_chat_read",
    ),
    path(
        "student/classroom/<int:pk>/chat/moderation-feedback/<int:message_id>/ack/",
        chat_views.student_chat_moderation_feedback_ack,
        name="api_student_chat_moderation_feedback_ack",
    ),
    path(
        "student/classroom/<int:pk>/group-collaboration/",
        views.student_classroom_group_collaboration,
        name="api_student_classroom_group_collaboration",
    ),
    path(
        "student/classroom/<int:pk>/group-collaboration/files/",
        views.student_classroom_group_file_upload,
        name="api_student_classroom_group_file_upload",
    ),
    path(
        "student/classroom/<int:pk>/evaluation/",
        views.student_classroom_evaluation,
        name="api_student_classroom_evaluation",
    ),
    path(
        "student/classroom/<int:pk>/evaluation/submit/",
        views.student_classroom_evaluation_submit,
        name="api_student_classroom_evaluation_submit",
    ),
    path(
        "student/classroom/<int:pk>/activities/<int:activity_id>/response/",
        views.student_classroom_activity_response,
        name="api_student_classroom_activity_response",
    ),
    path(
        "student/classroom/<int:pk>/activities/<int:activity_id>/score-feedback/ack/",
        views.student_classroom_score_feedback_ack,
        name="api_student_classroom_score_feedback_ack",
    ),
    path(
        "classroom/groups/<int:group_id>/office-config/",
        views.classroom_group_office_config,
        name="api_classroom_group_office_config",
    ),
    path(
        "classroom/groups/<int:group_id>/office-callback/",
        views.classroom_group_office_callback,
        name="api_classroom_group_office_callback",
    ),
    path("student/notices/", views.student_notices, name="api_student_notices"),
    path("student/feedback/", views.student_feedback, name="api_student_feedback"),
    path(
        "student/feedback/<int:pk>/",
        views.student_feedback_detail,
        name="api_student_feedback_detail",
    ),
    path(
        "student/assessments/",
        assessment_views.student_assessments,
        name="api_student_assessments",
    ),
    path(
        "student/assessments/<int:pk>/",
        assessment_views.student_assessment_detail,
        name="api_student_assessment_detail",
    ),
    path(
        "student/assessments/<int:pk>/start/",
        assessment_views.student_assessment_start,
        name="api_student_assessment_start",
    ),
    path(
        "student/assessments/<int:pk>/answer/",
        assessment_views.student_assessment_answer,
        name="api_student_assessment_answer",
    ),
    path(
        "student/assessments/<int:pk>/submit/",
        assessment_views.student_assessment_submit,
        name="api_student_assessment_submit",
    ),
]
