from django.urls import path

from . import (
    evaluation_ai_views,
    evaluation_views,
    event_views,
    school_admin_views,
    teacher_views,
)

app_name = "analytics_api"
urlpatterns = [
    path(
        "teacher/analytics/learning-summaries/",
        teacher_views.learning_summaries,
        name="teacher_learning_summaries",
    ),
    path(
        "teacher/analytics/learning-summaries/refresh/",
        teacher_views.refresh_learning_summaries,
        name="teacher_learning_summaries_refresh",
    ),
    path(
        "teacher/analytics/learning-summaries/export/",
        teacher_views.export_learning_summaries,
        name="teacher_learning_summaries_export",
    ),
    path(
        "teacher/analytics/stratification/",
        teacher_views.stratification_suggestions,
        name="teacher_stratification_suggestions",
    ),
    path(
        "teacher/analytics/stratification/overview/",
        teacher_views.stratification_overview,
        name="teacher_stratification_overview",
    ),
    path(
        "teacher/analytics/stratification/overview/export/",
        teacher_views.export_stratification_overview,
        name="teacher_stratification_overview_export",
    ),
    path(
        "teacher/analytics/stratification/batch-review/",
        teacher_views.bulk_review_stratification_suggestions,
        name="teacher_stratification_bulk_review",
    ),
    path(
        "teacher/analytics/stratification/<int:pk>/review/",
        teacher_views.review_stratification_suggestion,
        name="teacher_stratification_review",
    ),
    path(
        "teacher/analytics/stratification/manual-adjust/",
        teacher_views.manually_adjust_stratification,
        name="teacher_stratification_manual_adjust",
    ),
    path(
        "teacher/analytics/mastery/",
        teacher_views.mastery_snapshots,
        name="teacher_mastery_snapshots",
    ),
    path(
        "teacher/analytics/learning-target-states/",
        teacher_views.learning_target_states,
        name="teacher_learning_target_states",
    ),
    path(
        "teacher/analytics/mastery/refresh/",
        teacher_views.refresh_mastery_snapshots,
        name="teacher_mastery_snapshots_refresh",
    ),
    path(
        "teacher/evaluations/options/",
        evaluation_views.evaluation_options,
        name="teacher_evaluation_options",
    ),
    path(
        "teacher/evaluations/ai-drafts/options/",
        evaluation_ai_views.ai_draft_options,
        name="teacher_evaluation_ai_draft_options",
    ),
    path(
        "teacher/evaluations/ai-drafts/",
        evaluation_ai_views.ai_drafts,
        name="teacher_evaluation_ai_drafts",
    ),
    path(
        "teacher/evaluations/ai-drafts/<int:pk>/",
        evaluation_ai_views.ai_draft_detail,
        name="teacher_evaluation_ai_draft_detail",
    ),
    path(
        "teacher/evaluations/ai-drafts/<int:pk>/retrieve/",
        evaluation_ai_views.ai_draft_retrieve,
        name="teacher_evaluation_ai_draft_retrieve",
    ),
    path(
        "teacher/evaluations/ai-drafts/<int:pk>/suggest-modes/",
        evaluation_ai_views.ai_draft_suggest_modes,
        name="teacher_evaluation_ai_draft_suggest_modes",
    ),
    path(
        "teacher/evaluations/ai-drafts/<int:pk>/confirm-modes/",
        evaluation_ai_views.ai_draft_confirm_modes,
        name="teacher_evaluation_ai_draft_confirm_modes",
    ),
    path(
        "teacher/evaluations/ai-drafts/<int:pk>/generate/",
        evaluation_ai_views.ai_draft_generate,
        name="teacher_evaluation_ai_draft_generate",
    ),
    path(
        "teacher/evaluations/ai-drafts/<int:pk>/save-plan-draft/",
        evaluation_ai_views.ai_draft_save_plan,
        name="teacher_evaluation_ai_draft_save_plan",
    ),
    path(
        "teacher/evaluations/ai-drafts/<int:pk>/cancel/",
        evaluation_ai_views.ai_draft_cancel,
        name="teacher_evaluation_ai_draft_cancel",
    ),
    path(
        "teacher/evaluations/plans/",
        evaluation_views.plans,
        name="teacher_evaluation_plans",
    ),
    path(
        "teacher/evaluations/plans/<int:pk>/",
        evaluation_views.plan_detail,
        name="teacher_evaluation_plan_detail",
    ),
    path(
        "teacher/evaluations/plans/<int:pk>/review-confirm/",
        evaluation_views.review_confirm_plan_view,
        name="teacher_evaluation_plan_review_confirm",
    ),
    path(
        "teacher/evaluations/plans/<int:pk>/publish/",
        evaluation_views.publish_plan_view,
        name="teacher_evaluation_plan_publish",
    ),
    path(
        "teacher/evaluations/standards/",
        evaluation_views.standards,
        name="teacher_evaluation_standards",
    ),
    path(
        "teacher/evaluations/standards/<int:pk>/",
        evaluation_views.standard_detail,
        name="teacher_evaluation_standard_detail",
    ),
    path(
        "teacher/evaluations/standards/<int:pk>/review-confirm/",
        evaluation_views.review_confirm_standard_view,
        name="teacher_evaluation_standard_review_confirm",
    ),
    path(
        "teacher/evaluations/standards/<int:pk>/publish/",
        evaluation_views.publish_standard_view,
        name="teacher_evaluation_standard_publish",
    ),
    path(
        "teacher/evaluations/trials/",
        evaluation_views.trial_records,
        name="teacher_evaluation_trials",
    ),
    path(
        "teacher/evaluations/trials/export/",
        evaluation_views.export_trial_records,
        name="teacher_evaluation_trials_export",
    ),
    path(
        "teacher/evaluations/trials/<int:pk>/",
        evaluation_views.trial_record_detail,
        name="teacher_evaluation_trial_detail",
    ),
    path(
        "teacher/evaluations/lesson-steps/<int:step_id>/binding/",
        evaluation_views.lesson_step_binding,
        name="teacher_lesson_step_evaluation_binding",
    ),
    path(
        "learning-events/batch/",
        event_views.learning_event_batch,
        name="learning_event_batch",
    ),
    path(
        "school-admin/analytics/quality/",
        school_admin_views.school_quality,
        name="school_admin_analytics_quality",
    ),
    path(
        "school-admin/analytics/quality/run/",
        school_admin_views.run_school_quality,
        name="school_admin_analytics_quality_run",
    ),
    path(
        "school-admin/analytics/quality/export/",
        school_admin_views.export_school_quality,
        name="school_admin_analytics_quality_export",
    ),
    path(
        "school-admin/analytics/preparation/",
        school_admin_views.analysis_preparation,
        name="school_admin_analysis_preparation",
    ),
    path(
        "school-admin/analytics/preparation/decision-points/",
        school_admin_views.create_analysis_decision_point,
        name="school_admin_analysis_decision_point_create",
    ),
    path(
        "school-admin/analytics/preparation/outcomes/refresh/",
        school_admin_views.refresh_analysis_outcomes,
        name="school_admin_analysis_outcomes_refresh",
    ),
    path(
        "school-admin/analytics/preparation/datasets/",
        school_admin_views.create_training_dataset,
        name="school_admin_training_dataset_create",
    ),
    path(
        "school-admin/analytics/preparation/datasets/<int:pk>/export/",
        school_admin_views.export_training_dataset,
        name="school_admin_training_dataset_export",
    ),
    path(
        "school-admin/analytics/models/",
        school_admin_views.model_validation,
        name="school_admin_model_validation",
    ),
    path(
        "school-admin/analytics/content-band-policies/",
        school_admin_views.content_band_policies,
        name="school_admin_content_band_policies",
    ),
    path(
        "school-admin/analytics/content-band-policies/<int:pk>/publish/",
        school_admin_views.publish_content_band_policy_view,
        name="school_admin_content_band_policy_publish",
    ),
    path(
        "school-admin/analytics/mastery/refresh/",
        school_admin_views.refresh_assessment_mastery,
        name="school_admin_mastery_refresh",
    ),
    path(
        "school-admin/analytics/models/longitudinal/",
        school_admin_views.create_longitudinal_analysis,
        name="school_admin_longitudinal_analysis_create",
    ),
    path(
        "school-admin/analytics/models/compare/",
        school_admin_views.create_model_comparison,
        name="school_admin_model_comparison_create",
    ),
    path(
        "school-admin/analytics/models/compare-advanced/",
        school_admin_views.create_model_02_comparison,
        name="school_admin_model_02_comparison_create",
    ),
    path(
        "school-admin/analytics/models/class-calibration/",
        school_admin_views.create_class_calibration,
        name="school_admin_class_calibration_create",
    ),
    path(
        "school-admin/analytics/models/train/",
        school_admin_views.train_stratification_model,
        name="school_admin_stratification_model_train",
    ),
    path(
        "school-admin/analytics/models/class-calibration/<int:pk>/publish/",
        school_admin_views.publish_class_calibration,
        name="school_admin_class_calibration_publish",
    ),
    path(
        "school-admin/analytics/models/releases/<int:pk>/rollback/",
        school_admin_views.rollback_model_release_view,
        name="school_admin_model_release_rollback",
    ),
    path(
        "school-admin/analytics/models/releases/<int:pk>/verify/",
        school_admin_views.verify_model_release_view,
        name="school_admin_model_release_verify",
    ),
    path(
        "school-admin/analytics/models/releases/<int:pk>/package/",
        school_admin_views.download_model_release_package,
        name="school_admin_model_release_package",
    ),
    path(
        "school-admin/analytics/models/<int:pk>/export/",
        school_admin_views.export_model_validation,
        name="school_admin_model_validation_export",
    ),
]
