from django.urls import path

from . import evaluation_views, event_views, school_admin_views, teacher_views

app_name = "analytics_api"
urlpatterns = [
    path(
        "teacher/analytics/learning-summaries/",
        teacher_views.learning_summaries,
        name="teacher_learning_summaries",
    ),
    path(
        "teacher/analytics/learning-summaries/refresh/",
        teacher_views.refresh_learning_summaries,
        name="teacher_learning_summaries_refresh",
    ),
    path(
        "teacher/analytics/learning-summaries/export/",
        teacher_views.export_learning_summaries,
        name="teacher_learning_summaries_export",
    ),
    path(
        "teacher/analytics/stratification/",
        teacher_views.stratification_suggestions,
        name="teacher_stratification_suggestions",
    ),
    path(
        "teacher/analytics/stratification/<int:pk>/review/",
        teacher_views.review_stratification_suggestion,
        name="teacher_stratification_review",
    ),
    path(
        "teacher/evaluations/options/",
        evaluation_views.evaluation_options,
        name="teacher_evaluation_options",
    ),
    path(
        "teacher/evaluations/plans/",
        evaluation_views.plans,
        name="teacher_evaluation_plans",
    ),
    path(
        "teacher/evaluations/plans/<int:pk>/",
        evaluation_views.plan_detail,
        name="teacher_evaluation_plan_detail",
    ),
    path(
        "teacher/evaluations/plans/<int:pk>/publish/",
        evaluation_views.publish_plan_view,
        name="teacher_evaluation_plan_publish",
    ),
    path(
        "teacher/evaluations/standards/",
        evaluation_views.standards,
        name="teacher_evaluation_standards",
    ),
    path(
        "teacher/evaluations/standards/<int:pk>/",
        evaluation_views.standard_detail,
        name="teacher_evaluation_standard_detail",
    ),
    path(
        "teacher/evaluations/standards/<int:pk>/publish/",
        evaluation_views.publish_standard_view,
        name="teacher_evaluation_standard_publish",
    ),
    path(
        "teacher/evaluations/trials/",
        evaluation_views.trial_records,
        name="teacher_evaluation_trials",
    ),
    path(
        "teacher/evaluations/trials/export/",
        evaluation_views.export_trial_records,
        name="teacher_evaluation_trials_export",
    ),
    path(
        "teacher/evaluations/trials/<int:pk>/",
        evaluation_views.trial_record_detail,
        name="teacher_evaluation_trial_detail",
    ),
    path(
        "teacher/evaluations/lesson-steps/<int:step_id>/binding/",
        evaluation_views.lesson_step_binding,
        name="teacher_lesson_step_evaluation_binding",
    ),
    path(
        "learning-events/batch/",
        event_views.learning_event_batch,
        name="learning_event_batch",
    ),
    path(
        "school-admin/analytics/quality/",
        school_admin_views.school_quality,
        name="school_admin_analytics_quality",
    ),
    path(
        "school-admin/analytics/quality/run/",
        school_admin_views.run_school_quality,
        name="school_admin_analytics_quality_run",
    ),
    path(
        "school-admin/analytics/quality/export/",
        school_admin_views.export_school_quality,
        name="school_admin_analytics_quality_export",
    ),
]
