from django.urls import path

from . import views


urlpatterns = [
    path(
        "super-admin/curriculum-standards/",
        views.super_admin_standards,
        name="api_super_admin_curriculum_standards",
    ),
    path(
        "super-admin/curriculum-standards/<int:pk>/",
        views.super_admin_standard_detail,
        name="api_super_admin_curriculum_standard_detail",
    ),
    path(
        "super-admin/curriculum-standards/<int:pk>/versions/",
        views.super_admin_standard_versions,
        name="api_super_admin_curriculum_standard_versions",
    ),
    path(
        "super-admin/curriculum-standard-versions/<int:pk>/",
        views.super_admin_version_detail,
        name="api_super_admin_curriculum_standard_version_detail",
    ),
    path(
        "super-admin/curriculum-standard-versions/<int:pk>/processing-jobs/",
        views.super_admin_create_processing_job,
        name="api_super_admin_curriculum_processing_job_create",
    ),
    path(
        "super-admin/curriculum-processing-jobs/",
        views.super_admin_processing_jobs,
        name="api_super_admin_curriculum_processing_jobs",
    ),
    path(
        "super-admin/curriculum-processing-jobs/<int:pk>/",
        views.super_admin_processing_job_detail,
        name="api_super_admin_curriculum_processing_job_detail",
    ),
    path(
        "super-admin/curriculum-processing-jobs/<int:pk>/cancel/",
        views.super_admin_cancel_processing_job,
        name="api_super_admin_curriculum_processing_job_cancel",
    ),
    path(
        "super-admin/curriculum-processing-jobs/<int:pk>/retry/",
        views.super_admin_retry_processing_job,
        name="api_super_admin_curriculum_processing_job_retry",
    ),
    path(
        "super-admin/curriculum-standard-versions/<int:pk>/nodes/",
        views.super_admin_version_nodes,
        name="api_super_admin_curriculum_standard_version_nodes",
    ),
    path(
        "super-admin/curriculum-standard-versions/<int:pk>/pages/review/",
        views.super_admin_version_pages_review,
        name="api_super_admin_curriculum_standard_version_pages_review",
    ),
    path(
        "super-admin/curriculum-standard-pages/<int:pk>/",
        views.super_admin_page_detail,
        name="api_super_admin_curriculum_standard_page_detail",
    ),
    path(
        "super-admin/curriculum-standard-nodes/<int:pk>/",
        views.super_admin_node_detail,
        name="api_super_admin_curriculum_standard_node_detail",
    ),
    path(
        "super-admin/curriculum-standard-versions/<int:pk>/submit-review/",
        views.super_admin_version_submit_review,
        name="api_super_admin_curriculum_standard_version_submit_review",
    ),
    path(
        "super-admin/curriculum-standard-versions/<int:pk>/review/",
        views.super_admin_version_review,
        name="api_super_admin_curriculum_standard_version_review",
    ),
    path(
        "super-admin/curriculum-standard-versions/<int:pk>/publish/",
        views.super_admin_version_publish,
        name="api_super_admin_curriculum_standard_version_publish",
    ),
    path(
        "super-admin/curriculum-standard-versions/<int:pk>/archive/",
        views.super_admin_version_archive,
        name="api_super_admin_curriculum_standard_version_archive",
    ),
    path(
        "super-admin/curriculum-standard-versions/<int:pk>/restore/",
        views.super_admin_version_restore,
        name="api_super_admin_curriculum_standard_version_restore",
    ),
    path(
        "super-admin/curriculum-standard-versions/<int:pk>/retrieval-index/rebuild/",
        views.super_admin_rebuild_retrieval_index,
        name="api_super_admin_curriculum_retrieval_index_rebuild",
    ),
    path(
        "curriculum-standards/reference-options/",
        views.reference_options,
        name="api_curriculum_standard_reference_options",
    ),
    path(
        "curriculum-standard-nodes/<int:pk>/",
        views.curriculum_node_trace,
        name="api_curriculum_standard_node_trace",
    ),
    path(
        "curriculum-standard-versions/compare/",
        views.curriculum_standard_compare,
        name="api_curriculum_standard_compare",
    ),
    path(
        "curriculum-standard-versions/<int:pk>/pages/",
        views.curriculum_version_pages,
        name="api_curriculum_standard_pages",
    ),
    path(
        "curriculum-standard-versions/<int:pk>/pdf/",
        views.curriculum_standard_pdf,
        name="api_curriculum_standard_pdf",
    ),
    path(
        "curriculum-standard-versions/<int:pk>/structured.md",
        views.curriculum_standard_markdown,
        name="api_curriculum_standard_markdown",
    ),
    path(
        "curriculum-standard-versions/<int:pk>/structured.json",
        views.curriculum_standard_json,
        name="api_curriculum_standard_json",
    ),
    path(
        "curriculum-standard-versions/<int:pk>/structured.jsonl",
        views.curriculum_standard_jsonl,
        name="api_curriculum_standard_jsonl",
    ),
    path(
        "curriculum-standard-versions/<int:pk>/retrieval-chunks/",
        views.curriculum_retrieval_chunks,
        name="api_curriculum_retrieval_chunks",
    ),
    path(
        "curriculum-standard-retrieval/search/",
        views.curriculum_retrieval_search,
        name="api_curriculum_retrieval_search",
    ),
]
